export const Abilities = [
  { dataType: "1", value: "0", label: "Acid Fog" },
  { dataType: "1", value: "845", label: "Acid Orb" },
  { dataType: "1", value: "424", label: "Acid Splash" },
  { dataType: "1", value: "853", label: "Agannazzar's Scorcher" },
  { dataType: "1", value: "1", label: "Aid" },
  { dataType: "1", value: "442", label: "Amplify" },
  { dataType: "2", value: "707", label: "Ancient Red Dragon" },
  { dataType: "1", value: "2", label: "Animate Dead" },
  { dataType: "2", value: "623", label: "Animate Dead" },
  { dataType: "2", value: "604", label: "Arrow of Death" },
  { dataType: "2", value: "195", label: "Aura of Blinding" },
  { dataType: "2", value: "196", label: "Aura of Cold" },
  { dataType: "2", value: "197", label: "Aura of Electricity" },
  { dataType: "2", value: "198", label: "Aura of Fear" },
  { dataType: "2", value: "199", label: "Aura of Fire" },
  { dataType: "1", value: "429", label: "Aura of Glory" },
  { dataType: "1", value: "562", label: "Aura of Glory - Cursed" },
  { dataType: "1", value: "761", label: "Aura of Hellfire" },
  { dataType: "2", value: "200", label: "Aura of Menace" },
  { dataType: "2", value: "201", label: "Aura of Protection" },
  { dataType: "2", value: "202", label: "Aura of Stunning" },
  { dataType: "2", value: "203", label: "Aura of Unearthly Visage" },
  { dataType: "2", value: "204", label: "Aura of Unnatural" },
  { dataType: "1", value: "372", label: "Aura of Vitality" },
  { dataType: "1", value: "323", label: "Aura versus Alignment" },
  { dataType: "2", value: "412", label: "Aura, Dragon Fear" },
  { dataType: "1", value: "363", label: "Awaken" },
  { dataType: "1", value: "140", label: "Bad Strref" },
  { dataType: "2", value: "246", label: "Bad Strref" },
  { dataType: "1", value: "170", label: "Bad Strref" },
  { dataType: "1", value: "85", label: "Bad Strref" },
  { dataType: "1", value: "764", label: "Bad Strref" },
  { dataType: "1", value: "162", label: "Bad Strref" },
  { dataType: "1", value: "730", label: "Bad Strref" },
  { dataType: "2", value: "728", label: "Bad Strref" },
  { dataType: "1", value: "699", label: "Bad Strref" },
  { dataType: "1", value: "136", label: "Bad Strref" },
  { dataType: "1", value: "103", label: "Bad Strref" },
  { dataType: "2", value: "302", label: "Bad Strref" },
  { dataType: "1", value: "108", label: "Bad Strref" },
  { dataType: "1", value: "109", label: "Bad Strref" },
  { dataType: "2", value: "305", label: "Bad Strref" },
  { dataType: "1", value: "112", label: "Bad Strref" },
  { dataType: "1", value: "68", label: "Bad Strref" },
  { dataType: "1", value: "106", label: "Bad Strref" },
  { dataType: "1", value: "22", label: "Bad Strref" },
  { dataType: "1", value: "12", label: "Bad Strref" },
  { dataType: "1", value: "7", label: "Bad Strref" },
  { dataType: "1", value: "436", label: "Balagarn's Iron Horn" },
  { dataType: "1", value: "1005", label: "Baleful Polymorph" },
  { dataType: "1", value: "850", label: "Baleful Transposition" },
  { dataType: "1", value: "516", label: "Ball Lightning" },
  { dataType: "1", value: "449", label: "Bane" },
  { dataType: "1", value: "430", label: "Banishment" },
  { dataType: "1", value: "3", label: "Barkskin" },
  { dataType: "1", value: "517", label: "Battletide" },
  { dataType: "2", value: "731", label: "Bebilith Web" },
  { dataType: "2", value: "727", label: "Beholder Antimagic Cone" },
  { dataType: "2", value: "736", label: "Beholder Special Attacks" },
  { dataType: "1", value: "851", label: "Benign Transposition" },
  { dataType: "1", value: "4", label: "Bestow Curse" },
  { dataType: "1", value: "462", label: "Bigby's Clenched Fist" },
  { dataType: "1", value: "463", label: "Bigby's Crushing Hand" },
  { dataType: "1", value: "460", label: "Bigby's Forceful Hand" },
  { dataType: "1", value: "461", label: "Bigby's Grasping Hand" },
  { dataType: "1", value: "459", label: "Bigby's Interposing Hand" },
  { dataType: "1", value: "533", label: "Black Blade of Disaster" },
  { dataType: "1", value: "541", label: "Blackstaff" },
  { dataType: "1", value: "5", label: "Blade Barrier" },
  { dataType: "1", value: "535", label: "Blade Thirst" },
  { dataType: "1", value: "1060", label: "Bladeweave" },
  { dataType: "1", value: "6", label: "Bless" },
  { dataType: "1", value: "537", label: "Bless Weapon" },
  { dataType: "1", value: "1044", label: "Blighted Vines" },
  { dataType: "2", value: "647", label: "Blinding Speed" },
  { dataType: "1", value: "8", label: "Blindness/Deafness" },
  { dataType: "1", value: "1033", label: "Blizzard" },
  { dataType: "1", value: "422", label: "Blood Frenzy" },
  { dataType: "1", value: "1010", label: "Bodak's Glare" },
  { dataType: "1", value: "1063", label: "Body of True Flame" },
  { dataType: "1", value: "1037", label: "Body of the Sun" },
  { dataType: "2", value: "205", label: "Bolt, Ability Drain Charisma" },
  { dataType: "2", value: "206", label: "Bolt, Ability Drain Constitution" },
  { dataType: "2", value: "207", label: "Bolt, Ability Drain Dexterity" },
  { dataType: "2", value: "208", label: "Bolt, Ability Drain Intelligence" },
  { dataType: "2", value: "209", label: "Bolt, Ability Drain Strength" },
  { dataType: "2", value: "210", label: "Bolt, Ability Drain Wisdom" },
  { dataType: "2", value: "211", label: "Bolt, Acid" },
  { dataType: "2", value: "212", label: "Bolt, Charm" },
  { dataType: "2", value: "213", label: "Bolt, Cold" },
  { dataType: "2", value: "214", label: "Bolt, Confuse" },
  { dataType: "2", value: "215", label: "Bolt, Daze" },
  { dataType: "2", value: "216", label: "Bolt, Death" },
  { dataType: "2", value: "217", label: "Bolt, Disease" },
  { dataType: "2", value: "218", label: "Bolt, Dominate" },
  { dataType: "2", value: "219", label: "Bolt, Fire" },
  { dataType: "2", value: "220", label: "Bolt, Knockdown" },
  { dataType: "2", value: "221", label: "Bolt, Level Drain" },
  { dataType: "2", value: "222", label: "Bolt, Lightning" },
  { dataType: "2", value: "223", label: "Bolt, Paralyze" },
  { dataType: "2", value: "224", label: "Bolt, Poison" },
  { dataType: "2", value: "225", label: "Bolt, Shards" },
  { dataType: "2", value: "226", label: "Bolt, Slow" },
  { dataType: "2", value: "227", label: "Bolt, Stun" },
  { dataType: "2", value: "228", label: "Bolt, Web" },
  { dataType: "1", value: "423", label: "Bombardment" },
  { dataType: "2", value: "495", label: "Breath, Petrification" },
  { dataType: "1", value: "9", label: "Bull's Strength" },
  { dataType: "1", value: "1065", label: "Burning Bonds" },
  { dataType: "1", value: "10", label: "Burning Hands" },
  { dataType: "1", value: "1041", label: "Burning Tempest" },
  { dataType: "1", value: "1034", label: "Burst of Glacial Wrath" },
  { dataType: "1", value: "1055", label: "Cacophonic Burst" },
  { dataType: "1", value: "11", label: "Call Lightning" },
  { dataType: "1", value: "421", label: "Camouflage" },
  { dataType: "2", value: "686", label: "Captivating Song" },
  { dataType: "1", value: "13", label: "Cat's Grace" },
  { dataType: "1", value: "14", label: "Chain Lightning" },
  { dataType: "2", value: "770", label: "Chaos Spittle" },
  { dataType: "1", value: "15", label: "Charm Monster" },
  { dataType: "1", value: "16", label: "Charm Person" },
  { dataType: "1", value: "17", label: "Charm Person or Animal" },
  { dataType: "1", value: "1076", label: "Choir of Recovery" },
  { dataType: "1", value: "18", label: "Circle of Death" },
  { dataType: "1", value: "19", label: "Circle of Doom" },
  { dataType: "1", value: "20", label: "Clairaudience/Clairvoyance" },
  { dataType: "1", value: "21", label: "Clarity" },
  { dataType: "1", value: "569", label: "Cloud of Bewilderment" },
  { dataType: "1", value: "23", label: "Cloudkill" },
  { dataType: "1", value: "846", label: "Cold Orb" },
  { dataType: "1", value: "24", label: "Color Spray" },
  { dataType: "1", value: "518", label: "Combust" },
  { dataType: "2", value: "229", label: "Cone of Acid" },
  { dataType: "1", value: "25", label: "Cone of Cold" },
  { dataType: "2", value: "231", label: "Cone of Disease" },
  { dataType: "2", value: "232", label: "Cone of Fire" },
  { dataType: "2", value: "230", label: "Cone of Frost" },
  { dataType: "2", value: "233", label: "Cone of Lightning" },
  { dataType: "2", value: "234", label: "Cone of Poison" },
  { dataType: "2", value: "235", label: "Cone, Sonic" },
  { dataType: "1", value: "26", label: "Confusion" },
  { dataType: "1", value: "27", label: "Contagion" },
  { dataType: "1", value: "419", label: "Continual Flame" },
  { dataType: "1", value: "877", label: "Continual Flame (Blue)" },
  { dataType: "1", value: "878", label: "Continual Flame (Orange)" },
  { dataType: "1", value: "879", label: "Continual Flame (Purple)" },
  { dataType: "1", value: "28", label: "Control Undead" },
  { dataType: "1", value: "1046", label: "Corpse Explosion" },
  { dataType: "1", value: "29", label: "Create Greater Undead" },
  { dataType: "1", value: "564", label: "Create ShadowFiend" },
  { dataType: "1", value: "30", label: "Create Undead" },
  { dataType: "1", value: "364", label: "Creeping Doom" },
  { dataType: "1", value: "512", label: "Crumble" },
  { dataType: "1", value: "1019", label: "Crushing Despair" },
  { dataType: "1", value: "31", label: "Cure Critical Wounds" },
  { dataType: "1", value: "567", label: "Cure Critical Wounds - Others" },
  { dataType: "1", value: "32", label: "Cure Light Wounds" },
  { dataType: "1", value: "33", label: "Cure Minor Wounds" },
  { dataType: "1", value: "34", label: "Cure Moderate Wounds" },
  { dataType: "1", value: "35", label: "Cure Serious Wounds" },
  { dataType: "2", value: "820", label: "DM Tool 1" },
  { dataType: "2", value: "829", label: "DM Tool 10" },
  { dataType: "2", value: "821", label: "DM Tool 2" },
  { dataType: "2", value: "822", label: "DM Tool 3" },
  { dataType: "2", value: "823", label: "DM Tool 4" },
  { dataType: "2", value: "824", label: "DM Tool 5" },
  { dataType: "2", value: "825", label: "DM Tool 6" },
  { dataType: "2", value: "826", label: "DM Tool 7" },
  { dataType: "2", value: "827", label: "DM Tool 8" },
  { dataType: "2", value: "828", label: "DM Tool 9" },
  { dataType: "1", value: "548", label: "Darkfire" },
  { dataType: "1", value: "688", label: "Darkness" },
  { dataType: "1", value: "36", label: "Darkness" },
  { dataType: "1", value: "37", label: "Daze" },
  { dataType: "1", value: "536", label: "Deafening Clang" },
  { dataType: "1", value: "519", label: "Death Armor" },
  { dataType: "1", value: "383", label: "Death Domain, Negative Plane Avatar" },
  { dataType: "1", value: "38", label: "Death Ward" },
  { dataType: "2", value: "628", label: "Deathless Master Touch" },
  { dataType: "2", value: "774", label: "Deflecting Force" },
  { dataType: "1", value: "39", label: "Delayed Blast Fireball" },
  { dataType: "1", value: "366", label: "Destruction" },
  { dataType: "1", value: "445", label: "Dirge" },
  { dataType: "1", value: "1043", label: "Disintegrate" },
  { dataType: "1", value: "40", label: "Dismissal" },
  { dataType: "1", value: "41", label: "Dispel Magic" },
  { dataType: "1", value: "458", label: "Displacement" },
  { dataType: "1", value: "1002", label: "Disrobe" },
  { dataType: "1", value: "414", label: "Divine Favor" },
  { dataType: "1", value: "42", label: "Divine Power" },
  { dataType: "2", value: "622", label: "Divine Wrath" },
  { dataType: "1", value: "43", label: "Dominate Animal" },
  { dataType: "1", value: "44", label: "Dominate Monster" },
  { dataType: "1", value: "45", label: "Dominate Person" },
  { dataType: "1", value: "46", label: "Doom" },
  { dataType: "2", value: "690", label: "Dragon Breath" },
  { dataType: "2", value: "236", label: "Dragon Breath, Acid" },
  { dataType: "2", value: "237", label: "Dragon Breath, Cold" },
  { dataType: "2", value: "238", label: "Dragon Breath, Fear" },
  { dataType: "2", value: "797", label: "Dragon Breath, Fire" },
  { dataType: "2", value: "239", label: "Dragon Breath, Fire" },
  { dataType: "2", value: "798", label: "Dragon Breath, Gas" },
  { dataType: "2", value: "240", label: "Dragon Breath, Gas" },
  { dataType: "2", value: "796", label: "Dragon Breath, Lightning" },
  { dataType: "2", value: "241", label: "Dragon Breath, Lightning" },
  { dataType: "2", value: "242", label: "Dragon Breath, Paralysis" },
  { dataType: "2", value: "771", label: "Dragon Breath, Prismatic" },
  { dataType: "2", value: "243", label: "Dragon Breath, Sleep" },
  { dataType: "2", value: "244", label: "Dragon Breath, Slow" },
  { dataType: "2", value: "245", label: "Dragon Breath, Weaken" },
  { dataType: "2", value: "698", label: "Dragonbreath, Negative Energy" },
  { dataType: "1", value: "437", label: "Drown" },
  { dataType: "1", value: "354", label: "Eagle's Splendor" },
  { dataType: "1", value: "426", label: "Earthquake" },
  { dataType: "1", value: "439", label: "Electric Jolt" },
  { dataType: "1", value: "847", label: "Electric Orb" },
  { dataType: "1", value: "47", label: "Elemental Shield" },
  { dataType: "1", value: "48", label: "Elemental Swarm" },
  { dataType: "1", value: "49", label: "Endurance" },
  { dataType: "1", value: "50", label: "Endure Elements" },
  { dataType: "1", value: "369", label: "Energy Buffer" },
  { dataType: "1", value: "51", label: "Energy Drain" },
  { dataType: "1", value: "52", label: "Enervation" },
  { dataType: "1", value: "53", label: "Entangle" },
  { dataType: "1", value: "418", label: "Entropic Shield" },
  { dataType: "2", value: "638", label: "Epic Spell: Dragon Knight" },
  { dataType: "2", value: "639", label: "Epic Spell: Epic Mage Armor" },
  { dataType: "2", value: "695", label: "Epic Spell: Epic Warding" },
  { dataType: "2", value: "640", label: "Epic Spell: Greater Ruin" },
  { dataType: "2", value: "636", label: "Epic Spell: Hellball" },
  { dataType: "2", value: "637", label: "Epic Spell: Mummy Dust" },
  { dataType: "1", value: "121", label: "Ethereal Visage" },
  { dataType: "2", value: "724", label: "Etherealness" },
  { dataType: "1", value: "375", label: "Evard's Black Tentacles" },
  { dataType: "1", value: "566", label: "Evil Blight" },
  { dataType: "2", value: "803", label: "Evil Eye" },
  { dataType: "1", value: "456", label: "Expeditious Retreat" },
  { dataType: "1", value: "716", label: "Extract Brain" },
  { dataType: "2", value: "712", label: "Eyeball Flame Ray Attack" },
  { dataType: "2", value: "710", label: "Eyeball Frost Ray Attack" },
  { dataType: "2", value: "711", label: "Eyeball Inflict Wounds Ray" },
  { dataType: "1", value: "1014", label: "False Life" },
  { dataType: "1", value: "1004", label: "Falsify Self" },
  { dataType: "1", value: "1071", label: "Fascinate" },
  { dataType: "1", value: "54", label: "Fear" },
  { dataType: "1", value: "808", label: "Fear" },
  { dataType: "1", value: "55", label: "Feeblemind" },
  { dataType: "2", value: "247", label: "Ferocity" },
  { dataType: "2", value: "249", label: "Ferocity, Greater" },
  { dataType: "2", value: "248", label: "Ferocity, Improved" },
  { dataType: "1", value: "377", label: "Find Traps" },
  { dataType: "1", value: "56", label: "Finger of Death" },
  { dataType: "1", value: "848", label: "Fire Orb" },
  { dataType: "1", value: "57", label: "Fire Storm" },
  { dataType: "2", value: "801", label: "Fire Stream" },
  { dataType: "1", value: "58", label: "Fireball" },
  { dataType: "1", value: "440", label: "Firebrand" },
  { dataType: "1", value: "1038", label: "Fireburst" },
  { dataType: "1", value: "59", label: "Flame Arrow" },
  { dataType: "1", value: "60", label: "Flame Lash" },
  { dataType: "1", value: "61", label: "Flame Strike" },
  { dataType: "1", value: "542", label: "Flame Weapon" },
  { dataType: "1", value: "1040", label: "Flamespear" },
  { dataType: "1", value: "416", label: "Flare" },
  { dataType: "1", value: "485", label: "Flesh to Stone" },
  { dataType: "1", value: "356", label: "Fox's Cunning" },
  { dataType: "1", value: "62", label: "Freedom of Movement" },
  { dataType: "1", value: "63", label: "Gate" },
  { dataType: "2", value: "250", label: "Gaze, Charm" },
  { dataType: "2", value: "251", label: "Gaze, Confusion" },
  { dataType: "2", value: "252", label: "Gaze, Daze" },
  { dataType: "2", value: "253", label: "Gaze, Death" },
  { dataType: "2", value: "254", label: "Gaze, Destroy Chaos" },
  { dataType: "2", value: "255", label: "Gaze, Destroy Evil" },
  { dataType: "2", value: "256", label: "Gaze, Destroy Good" },
  { dataType: "2", value: "257", label: "Gaze, Destroy Law" },
  { dataType: "2", value: "258", label: "Gaze, Dominate" },
  { dataType: "2", value: "800", label: "Gaze, Dominate" },
  { dataType: "2", value: "259", label: "Gaze, Doom" },
  { dataType: "2", value: "260", label: "Gaze, Fear" },
  { dataType: "2", value: "261", label: "Gaze, Paralysis" },
  { dataType: "2", value: "497", label: "Gaze, Petrification" },
  { dataType: "2", value: "687", label: "Gaze, Petrification" },
  { dataType: "2", value: "262", label: "Gaze, Stunned" },
  { dataType: "1", value: "520", label: "Gedlee's Electric Loop" },
  { dataType: "1", value: "120", label: "Ghostly Visage" },
  { dataType: "1", value: "64", label: "Ghoul Touch" },
  { dataType: "1", value: "65", label: "Globe of Invulnerability" },
  { dataType: "1", value: "549", label: "Glyph of Warding" },
  { dataType: "1", value: "715", label: "Golem Slam" },
  { dataType: "1", value: "66", label: "Grease" },
  { dataType: "1", value: "515", label: "Great Thunderclap" },
  { dataType: "1", value: "360", label: "Greater Bull's Strength" },
  { dataType: "1", value: "361", label: "Greater Cat's Grace" },
  { dataType: "1", value: "67", label: "Greater Dispelling" },
  { dataType: "1", value: "357", label: "Greater Eagle's Splendor" },
  { dataType: "1", value: "362", label: "Greater Endurance" },
  { dataType: "1", value: "1039", label: "Greater Fireburst" },
  { dataType: "1", value: "359", label: "Greater Fox's Cunning" },
  { dataType: "1", value: "1077", label: "Greater Life Shift" },
  { dataType: "1", value: "453", label: "Greater Magic Fang" },
  { dataType: "1", value: "545", label: "Greater Magic Weapon" },
  { dataType: "1", value: "358", label: "Greater Owl's Wisdom" },
  { dataType: "1", value: "69", label: "Greater Planar Binding" },
  { dataType: "1", value: "70", label: "Greater Restoration" },
  { dataType: "1", value: "443", label: "Greater Sanctuary" },
  { dataType: "1", value: "71", label: "Greater Shadow Conjuration" },
  { dataType: "1", value: "350", label: "Greater Shadow Conjuration, Acid Arrow" },
  { dataType: "1", value: "351", label: "Greater Shadow Conjuration, Ghostly Visage" },
  { dataType: "1", value: "353", label: "Greater Shadow Conjuration, Minor Globe of Invulnerability" },
  { dataType: "1", value: "349", label: "Greater Shadow Conjuration, Summon Shadow" },
  { dataType: "1", value: "352", label: "Greater Shadow Conjuration, Web" },
  { dataType: "1", value: "1032", label: "Greater Shout" },
  { dataType: "1", value: "72", label: "Greater Spell Breach" },
  { dataType: "1", value: "73", label: "Greater Spell Mantle" },
  { dataType: "1", value: "74", label: "Greater Stoneskin" },
  { dataType: "1", value: "75", label: "Gust of Wind" },
  { dataType: "2", value: "603", label: "Hail of Arrows" },
  { dataType: "1", value: "1066", label: "Hail of Fire" },
  { dataType: "1", value: "76", label: "Hammer of the Gods" },
  { dataType: "1", value: "77", label: "Harm" },
  { dataType: "2", value: "759", label: "Harm Self (Undead)" },
  { dataType: "1", value: "78", label: "Haste" },
  { dataType: "1", value: "563", label: "Haste-Slow" },
  { dataType: "1", value: "79", label: "Heal" },
  { dataType: "1", value: "80", label: "Healing Circle" },
  { dataType: "1", value: "514", label: "Healing Sting" },
  { dataType: "2", value: "264", label: "Hell Hound Fire Breath" },
  { dataType: "1", value: "762", label: "Hell Inferno" },
  { dataType: "1", value: "81", label: "Hold Animal" },
  { dataType: "1", value: "82", label: "Hold Monster" },
  { dataType: "1", value: "83", label: "Hold Person" },
  { dataType: "1", value: "84", label: "Holy Aura" },
  { dataType: "1", value: "538", label: "Holy Sword" },
  { dataType: "1", value: "521", label: "Horizikaul's Boom" },
  { dataType: "1", value: "367", label: "Horrid Wilting" },
  { dataType: "2", value: "804", label: "Horrific Appearance" },
  { dataType: "2", value: "265", label: "Howl, Confusion" },
  { dataType: "2", value: "266", label: "Howl, Daze" },
  { dataType: "2", value: "267", label: "Howl, Death" },
  { dataType: "2", value: "268", label: "Howl, Doom" },
  { dataType: "2", value: "269", label: "Howl, Fear" },
  { dataType: "2", value: "270", label: "Howl, Paralysis" },
  { dataType: "2", value: "271", label: "Howl, Sonic" },
  { dataType: "2", value: "272", label: "Howl, Stunning" },
  { dataType: "2", value: "775", label: "Hurl Rocks" },
  { dataType: "1", value: "1003", label: "Hypothermia" },
  { dataType: "1", value: "543", label: "Ice Dagger" },
  { dataType: "1", value: "368", label: "Ice Storm" },
  { dataType: "1", value: "1074", label: "Ice Wall" },
  { dataType: "1", value: "86", label: "Identify" },
  { dataType: "2", value: "789", label: "Illithid Mind Blast" },
  { dataType: "2", value: "600", label: "Imbue Arrow" },
  { dataType: "1", value: "87", label: "Implosion" },
  { dataType: "1", value: "88", label: "Improved Invisibility" },
  { dataType: "1", value: "89", label: "Incendiary Cloud" },
  { dataType: "1", value: "1064", label: "Incinerating Pillar" },
  { dataType: "1", value: "446", label: "Inferno" },
  { dataType: "1", value: "513", label: "Infestation of Maggots" },
  { dataType: "1", value: "435", label: "Inflict Critical Wounds" },
  { dataType: "1", value: "432", label: "Inflict Light Wounds" },
  { dataType: "1", value: "431", label: "Inflict Minor Wounds" },
  { dataType: "1", value: "433", label: "Inflict Moderate Wounds" },
  { dataType: "1", value: "434", label: "Inflict Serious Wounds" },
  { dataType: "2", value: "273", label: "Intensity" },
  { dataType: "2", value: "275", label: "Intensity, Greater" },
  { dataType: "2", value: "274", label: "Intensity, Improved" },
  { dataType: "2", value: "799", label: "Invisibility" },
  { dataType: "1", value: "90", label: "Invisibility" },
  { dataType: "1", value: "91", label: "Invisibility Purge" },
  { dataType: "1", value: "92", label: "Invisibility Sphere" },
  { dataType: "2", value: "263", label: "Iron Golem Poison Gas" },
  { dataType: "1", value: "522", label: "Ironguts" },
  { dataType: "1", value: "448", label: "Isaac's Greater Missile Storm" },
  { dataType: "1", value: "447", label: "Isaac's Lesser Missile Storm" },
  { dataType: "1", value: "1057", label: "Joyful Noise" },
  { dataType: "1", value: "539", label: "Keen Edge" },
  { dataType: "1", value: "93", label: "Knock" },
  { dataType: "2", value: "276", label: "Krenshar, Fear Gaze" },
  { dataType: "1", value: "1000", label: "Land Womb" },
  { dataType: "1", value: "376", label: "Legend Lore" },
  { dataType: "1", value: "840", label: "Lesser Acid Orb" },
  { dataType: "2", value: "277", label: "Lesser Body Adjustment" },
  { dataType: "1", value: "841", label: "Lesser Cold Orb" },
  { dataType: "1", value: "94", label: "Lesser Dispel" },
  { dataType: "1", value: "842", label: "Lesser Electric Orb" },
  { dataType: "1", value: "843", label: "Lesser Fire Orb" },
  { dataType: "1", value: "95", label: "Lesser Mind Blank" },
  { dataType: "1", value: "96", label: "Lesser Planar Binding" },
  { dataType: "1", value: "97", label: "Lesser Restoration" },
  { dataType: "1", value: "844", label: "Lesser Sonic Orb" },
  { dataType: "1", value: "98", label: "Lesser Spell Breach" },
  { dataType: "1", value: "99", label: "Lesser Spell Mantle" },
  { dataType: "1", value: "1047", label: "Life Shift" },
  { dataType: "1", value: "100", label: "Light" },
  { dataType: "1", value: "872", label: "Light (Blue)" },
  { dataType: "1", value: "873", label: "Light (Orange)" },
  { dataType: "1", value: "874", label: "Light (Purple)" },
  { dataType: "1", value: "875", label: "Light (Red)" },
  { dataType: "1", value: "876", label: "Light (Yellow)" },
  { dataType: "1", value: "101", label: "Lightning Bolt" },
  { dataType: "1", value: "102", label: "Mage Armor" },
  { dataType: "1", value: "1042", label: "Mage Hand" },
  { dataType: "1", value: "322", label: "Magic Circle against Alignment" },
  { dataType: "1", value: "104", label: "Magic Circle against Evil" },
  { dataType: "1", value: "105", label: "Magic Circle against Good" },
  { dataType: "1", value: "452", label: "Magic Fang" },
  { dataType: "1", value: "107", label: "Magic Missile" },
  { dataType: "1", value: "546", label: "Magic Vestment" },
  { dataType: "1", value: "544", label: "Magic Weapon" },
  { dataType: "2", value: "692", label: "Manticore Spikes" },
  { dataType: "2", value: "498", label: "Manticore Spikes" },
  { dataType: "1", value: "110", label: "Mass Blindness/Deafness" },
  { dataType: "1", value: "854", label: "Mass Bull's Strength" },
  { dataType: "1", value: "455", label: "Mass Camouflage" },
  { dataType: "1", value: "855", label: "Mass Cat's Grace" },
  { dataType: "1", value: "111", label: "Mass Charm" },
  { dataType: "1", value: "864", label: "Mass Cure Critical Wounds" },
  { dataType: "1", value: "861", label: "Mass Cure Light Wounds" },
  { dataType: "1", value: "862", label: "Mass Cure Moderate Wounds" },
  { dataType: "1", value: "863", label: "Mass Cure Serious Wounds" },
  { dataType: "1", value: "856", label: "Mass Eagle Splendor" },
  { dataType: "1", value: "857", label: "Mass Endurance" },
  { dataType: "1", value: "858", label: "Mass Fox's Cunning" },
  { dataType: "1", value: "113", label: "Mass Haste" },
  { dataType: "1", value: "114", label: "Mass Heal" },
  { dataType: "1", value: "868", label: "Mass Inflict Critical Wounds" },
  { dataType: "1", value: "865", label: "Mass Inflict Light Wounds" },
  { dataType: "1", value: "866", label: "Mass Inflict Moderate Wounds" },
  { dataType: "1", value: "867", label: "Mass Inflict Serious Wounds" },
  { dataType: "1", value: "1023", label: "Mass Light" },
  { dataType: "1", value: "859", label: "Mass Owl's Wisdom" },
  { dataType: "1", value: "860", label: "Mass Ultravision" },
  { dataType: "1", value: "115", label: "Melf's Acid Arrow" },
  { dataType: "2", value: "278", label: "Mephit, Salt Breath" },
  { dataType: "2", value: "279", label: "Mephit, Steam Breath" },
  { dataType: "1", value: "523", label: "Mestil's Acid Breath" },
  { dataType: "1", value: "524", label: "Mestil's Acid Sheath" },
  { dataType: "1", value: "116", label: "Meteor Swarm" },
  { dataType: "1", value: "117", label: "Mind Blank" },
  { dataType: "1", value: "118", label: "Mind Fog" },
  { dataType: "1", value: "119", label: "Minor Globe of Invulnerability" },
  { dataType: "1", value: "1087", label: "Mirror Image" },
  { dataType: "1", value: "525", label: "Monstrous Regeneration" },
  { dataType: "1", value: "122", label: "Mordenkainen's Disjunction" },
  { dataType: "1", value: "871", label: "Mordenkainen's Magnificent Mansion" },
  { dataType: "1", value: "123", label: "Mordenkainen's Sword" },
  { dataType: "2", value: "280", label: "Mummy, Bolster Undead" },
  { dataType: "1", value: "124", label: "Nature's Balance" },
  { dataType: "1", value: "370", label: "Negative Energy Burst" },
  { dataType: "1", value: "125", label: "Negative Energy Protection" },
  { dataType: "1", value: "371", label: "Negative Energy Ray" },
  { dataType: "1", value: "126", label: "Neutralize Poison" },
  { dataType: "2", value: "819", label: "Nightmare, Smoke" },
  { dataType: "1", value: "809", label: "Oath of Wrath" },
  { dataType: "1", value: "420", label: "One with the Land" },
  { dataType: "1", value: "1068", label: "Open / Close" },
  { dataType: "1", value: "438", label: "Owl's Insight" },
  { dataType: "1", value: "355", label: "Owl's Wisdom" },
  { dataType: "1", value: "127", label: "Phantasmal Killer" },
  { dataType: "1", value: "451", label: "Planar Ally" },
  { dataType: "1", value: "128", label: "Planar Binding" },
  { dataType: "2", value: "830", label: "Player Tool 1" },
  { dataType: "2", value: "839", label: "Player Tool 10" },
  { dataType: "2", value: "831", label: "Player Tool 2" },
  { dataType: "2", value: "832", label: "Player Tool 3" },
  { dataType: "2", value: "833", label: "Player Tool 4" },
  { dataType: "2", value: "834", label: "Player Tool 5" },
  { dataType: "2", value: "835", label: "Player Tool 6" },
  { dataType: "2", value: "836", label: "Player Tool 7" },
  { dataType: "2", value: "837", label: "Player Tool 8" },
  { dataType: "2", value: "838", label: "Player Tool 9" },
  { dataType: "1", value: "129", label: "Poison" },
  { dataType: "1", value: "852", label: "Polar Ray" },
  { dataType: "1", value: "130", label: "Polymorph Self" },
  { dataType: "1", value: "390", label: "Polymorph, Fey" },
  { dataType: "1", value: "387", label: "Polymorph, Giant Spider" },
  { dataType: "1", value: "388", label: "Polymorph, Troll" },
  { dataType: "1", value: "389", label: "Polymorph, Umber Hulk" },
  { dataType: "1", value: "391", label: "Polymorph, Zombie" },
  { dataType: "1", value: "131", label: "Power Word, Kill" },
  { dataType: "1", value: "132", label: "Power Word, Stun" },
  { dataType: "1", value: "133", label: "Prayer" },
  { dataType: "1", value: "134", label: "Premonition" },
  { dataType: "1", value: "135", label: "Prismatic Spray" },
  { dataType: "1", value: "382", label: "Protection Domain, Divine Protection" },
  { dataType: "1", value: "321", label: "Protection from Alignment" },
  { dataType: "1", value: "137", label: "Protection from Elements" },
  { dataType: "1", value: "138", label: "Protection from Evil" },
  { dataType: "1", value: "139", label: "Protection from Good" },
  { dataType: "1", value: "141", label: "Protection from Spells" },
  { dataType: "2", value: "552", label: "Psionic Charm Monster" },
  { dataType: "2", value: "741", label: "Psionic Inertial Barrier" },
  { dataType: "2", value: "763", label: "Psionic Mass Concussion" },
  { dataType: "2", value: "551", label: "Psionic Mind Blast" },
  { dataType: "2", value: "714", label: "Psionic Mind Blast (Paragon)" },
  { dataType: "2", value: "713", label: "Psionic Mind Blast 10m Radius" },
  { dataType: "2", value: "292", label: "Pulse, Ability Drain Charisma" },
  { dataType: "2", value: "293", label: "Pulse, Ability Drain Constitution" },
  { dataType: "2", value: "294", label: "Pulse, Ability Drain Dexterity" },
  { dataType: "2", value: "291", label: "Pulse, Ability Drain Intelligence" },
  { dataType: "2", value: "295", label: "Pulse, Ability Drain Strength" },
  { dataType: "2", value: "296", label: "Pulse, Ability Drain Wisdom" },
  { dataType: "2", value: "283", label: "Pulse, Air Elemental Whirlwind" },
  { dataType: "2", value: "286", label: "Pulse, Cold" },
  { dataType: "2", value: "289", label: "Pulse, Death" },
  { dataType: "2", value: "298", label: "Pulse, Disease" },
  { dataType: "2", value: "284", label: "Pulse, Fire" },
  { dataType: "2", value: "288", label: "Pulse, Holy" },
  { dataType: "2", value: "290", label: "Pulse, Level Drain" },
  { dataType: "2", value: "285", label: "Pulse, Lightning" },
  { dataType: "2", value: "287", label: "Pulse, Negative" },
  { dataType: "2", value: "297", label: "Pulse, Poison" },
  { dataType: "2", value: "282", label: "Pulse, Vrock Spores" },
  { dataType: "2", value: "281", label: "Pulse, Water Elemental Drown" },
  { dataType: "1", value: "425", label: "Quillfire" },
  { dataType: "2", value: "299", label: "Rage" },
  { dataType: "2", value: "301", label: "Rage, Greater" },
  { dataType: "2", value: "300", label: "Rage, Improved" },
  { dataType: "1", value: "1067", label: "Raging Inferno" },
  { dataType: "1", value: "142", label: "Raise Dead" },
  { dataType: "1", value: "143", label: "Ray of Enfeeblement" },
  { dataType: "1", value: "144", label: "Ray of Frost" },
  { dataType: "1", value: "374", label: "Regenerate" },
  { dataType: "1", value: "145", label: "Remove Blindness/Deafness" },
  { dataType: "1", value: "146", label: "Remove Curse" },
  { dataType: "1", value: "147", label: "Remove Disease" },
  { dataType: "1", value: "148", label: "Remove Fear" },
  { dataType: "1", value: "149", label: "Remove Paralysis" },
  { dataType: "1", value: "150", label: "Resist Elements" },
  { dataType: "1", value: "151", label: "Resistance" },
  { dataType: "1", value: "152", label: "Restoration" },
  { dataType: "1", value: "568", label: "Restoration - Other" },
  { dataType: "1", value: "153", label: "Resurrection" },
  { dataType: "1", value: "385", label: "Rogue's Cunning" },
  { dataType: "1", value: "154", label: "Sanctuary" },
  { dataType: "1", value: "155", label: "Scare" },
  { dataType: "1", value: "526", label: "Scintillating Sphere" },
  { dataType: "1", value: "156", label: "Searing Light" },
  { dataType: "1", value: "157", label: "See Invisibility" },
  { dataType: "2", value: "601", label: "Seeker Arrow I" },
  { dataType: "2", value: "602", label: "Seeker Arrow II" },
  { dataType: "1", value: "158", label: "Shades" },
  { dataType: "1", value: "340", label: "Shades, Cone of Cold" },
  { dataType: "1", value: "341", label: "Shades, Fireball" },
  { dataType: "1", value: "342", label: "Shades, Stoneskin" },
  { dataType: "1", value: "343", label: "Shades, Wall of Fire" },
  { dataType: "1", value: "159", label: "Shadow Conjuration" },
  { dataType: "1", value: "345", label: "Shadow Conjuration, Darkness" },
  { dataType: "1", value: "346", label: "Shadow Conjuration, Invisibility" },
  { dataType: "1", value: "347", label: "Shadow Conjuration, Mage Armor" },
  { dataType: "1", value: "348", label: "Shadow Conjuration, Magic Missile" },
  { dataType: "1", value: "344", label: "Shadow Conjuration, Summon Shadow" },
  { dataType: "1", value: "160", label: "Shadow Shield" },
  { dataType: "1", value: "769", label: "Shadow attack" },
  { dataType: "1", value: "802", label: "Shadow attack" },
  { dataType: "2", value: "757", label: "Shadowblend" },
  { dataType: "1", value: "161", label: "Shapechange" },
  { dataType: "1", value: "394", label: "Shapechange, Balor" },
  { dataType: "1", value: "395", label: "Shapechange, Death Slaad" },
  { dataType: "1", value: "393", label: "Shapechange, Fire Giant" },
  { dataType: "1", value: "396", label: "Shapechange, Iron Golem" },
  { dataType: "1", value: "392", label: "Shapechange, Red Dragon" },
  { dataType: "1", value: "1082", label: "Shards of Winter" },
  { dataType: "1", value: "534", label: "Shelgarn's Persistent Blade" },
  { dataType: "1", value: "417", label: "Shield" },
  { dataType: "1", value: "450", label: "Shield of Faith" },
  { dataType: "1", value: "1031", label: "Shout" },
  { dataType: "1", value: "163", label: "Silence" },
  { dataType: "1", value: "164", label: "Slay Living" },
  { dataType: "1", value: "165", label: "Sleep" },
  { dataType: "1", value: "166", label: "Slow" },
  { dataType: "1", value: "1086", label: "Slow Time" },
  { dataType: "1", value: "1058", label: "Song of Discord" },
  { dataType: "1", value: "849", label: "Sonic Orb" },
  { dataType: "1", value: "167", label: "Sound Burst" },
  { dataType: "1", value: "169", label: "Spell Mantle" },
  { dataType: "1", value: "168", label: "Spell Resistance" },
  { dataType: "1", value: "454", label: "Spike Growth" },
  { dataType: "1", value: "171", label: "Stinking Cloud" },
  { dataType: "1", value: "527", label: "Stone Bones" },
  { dataType: "1", value: "486", label: "Stone to Flesh" },
  { dataType: "1", value: "547", label: "Stonehold" },
  { dataType: "1", value: "172", label: "Stoneskin" },
  { dataType: "1", value: "173", label: "Storm of Vengeance" },
  { dataType: "1", value: "381", label: "Strength Domain, Divine Strength" },
  { dataType: "2", value: "701", label: "Summon Baatezu" },
  { dataType: "1", value: "379", label: "Summon Celestial" },
  { dataType: "1", value: "174", label: "Summon Creature I" },
  { dataType: "1", value: "175", label: "Summon Creature II" },
  { dataType: "1", value: "176", label: "Summon Creature III" },
  { dataType: "1", value: "177", label: "Summon Creature IV" },
  { dataType: "1", value: "178", label: "Summon Creature IX" },
  { dataType: "1", value: "179", label: "Summon Creature V" },
  { dataType: "1", value: "180", label: "Summon Creature VI" },
  { dataType: "1", value: "181", label: "Summon Creature VII" },
  { dataType: "1", value: "182", label: "Summon Creature VIII" },
  { dataType: "2", value: "627", label: "Summon Greater Undead" },
  { dataType: "2", value: "378", label: "Summon Mephit" },
  { dataType: "1", value: "324", label: "Summon Shadow" },
  { dataType: "2", value: "303", label: "Summon Slaad" },
  { dataType: "2", value: "304", label: "Summon Tanarri" },
  { dataType: "2", value: "624", label: "Summon Undead" },
  { dataType: "1", value: "183", label: "Sunbeam" },
  { dataType: "1", value: "427", label: "Sunburst" },
  { dataType: "1", value: "1062", label: "Swap Gender" },
  { dataType: "1", value: "1052", label: "Symbol of Death" },
  { dataType: "1", value: "1053", label: "Symbol of Sleep" },
  { dataType: "1", value: "1027", label: "Synthesis" },
  { dataType: "1", value: "457", label: "Tasha's Hideous Laughter" },
  { dataType: "1", value: "184", label: "Tenser's Transformation" },
  { dataType: "1", value: "565", label: "Tide of Battle" },
  { dataType: "1", value: "185", label: "Time Stop" },
  { dataType: "2", value: "496", label: "Touch, Petrification" },
  { dataType: "1", value: "1080", label: "Tree Shape" },
  { dataType: "1", value: "384", label: "Trickery Domain, Divine Trickery" },
  { dataType: "2", value: "805", label: "Troglodyte Stench" },
  { dataType: "1", value: "186", label: "True Seeing" },
  { dataType: "1", value: "415", label: "True Strike" },
  { dataType: "2", value: "306", label: "Tyrant Fog Zombie Mist" },
  { dataType: "1", value: "365", label: "Ultravision" },
  { dataType: "2", value: "625", label: "Undead Graft I" },
  { dataType: "2", value: "626", label: "Undead Graft II" },
  { dataType: "1", value: "528", label: "Undeath to Death" },
  { dataType: "1", value: "444", label: "Undeath's Eternal Foe" },
  { dataType: "1", value: "1006", label: "Unhallowed Soil" },
  { dataType: "1", value: "187", label: "Unholy Aura" },
  { dataType: "1", value: "188", label: "Vampiric Touch" },
  { dataType: "1", value: "529", label: "Vine Mine" },
  { dataType: "1", value: "532", label: "Vine Mine, Camouflage" },
  { dataType: "1", value: "530", label: "Vine Mine, Entangle" },
  { dataType: "1", value: "531", label: "Vine Mine, Hamper Movement" },
  { dataType: "1", value: "189", label: "Virtue" },
  { dataType: "1", value: "190", label: "Wail of the Banshee" },
  { dataType: "1", value: "1016", label: "Wall of Dispel Magic" },
  { dataType: "1", value: "191", label: "Wall of Fire" },
  { dataType: "1", value: "1017", label: "Wall of Greater Dispel Magic" },
  { dataType: "1", value: "373", label: "War Cry" },
  { dataType: "1", value: "380", label: "War Domain, Battle Mastery" },
  { dataType: "1", value: "192", label: "Web" },
  { dataType: "1", value: "193", label: "Weird" },
  { dataType: "1", value: "1075", label: "Wind Wall" },
  { dataType: "1", value: "1025", label: "Wings of the Phoenix" },
  { dataType: "1", value: "194", label: "Word of Faith" },
  { dataType: "1", value: "441", label: "Wounding Whispers" },
  { dataType: "2", value: "664", label: "Wyrmling Breath, Acid" },
  { dataType: "2", value: "663", label: "Wyrmling Breath, Cold" },
  { dataType: "2", value: "665", label: "Wyrmling Breath, Fire" },
  { dataType: "2", value: "666", label: "Wyrmling Breath, Gas" },
  { dataType: "2", value: "667", label: "Wyrmling Breath, Lightning" },
];
