import { DropdownListItem } from ".";

export const AmbientSounds: DropdownListItem[] = [
  { value: "0", label: "(No Ambient Sound)()" },
  { value: "1", label: "Men Whisper Inside(al_pl_whispersm)" },
  { value: "2", label: "Women Whisper Inside(al_pl_whispersf)" },
  { value: "3", label: "People Whisper Inside(al_pl_whispers)" },
  { value: "4", label: "Small Group Talks Inside(al_pl_talkingsml)" },
  { value: "5", label: "Medium Group Talks Inside(al_pl_talkingmed)" },
  { value: "6", label: "Large Group Talks Inside(al_pl_talkinglrg)" },
  { value: "7", label: "Commoner Tavern Talk(al_pl_tavhubbub1)" },
  { value: "8", label: "Noble Tavern Talk(al_pl_tavhubbub2)" },
  { value: "9", label: "City Slums Day Crowded(al_pl_slumday1)" },
  { value: "10", label: "City Slums Day Sparse(al_pl_slumday2)" },
  { value: "11", label: "City Slums Night(al_pl_slumnite)" },
  { value: "12", label: "City Day Crowded(al_pl_cityday1)" },
  { value: "13", label: "City Day Sparse(al_pl_cityday2)" },
  { value: "14", label: "City Night(al_pl_citynite)" },
  { value: "15", label: "City Market(al_pl_marketday)" },
  { value: "16", label: "City Temple District(al_pl_templesday)" },
  { value: "17", label: "Town Day Crowded(al_pl_townday1)" },
  { value: "18", label: "Town Day Sparse(al_pl_townday2)" },
  { value: "19", label: "Town Night(al_pl_townnite)" },
  { value: "20", label: "Bordello Women(al_pl_bordello1)" },
  { value: "21", label: "Bordello Men and Women(al_pl_bordello2)" },
  { value: "22", label: "Riot Outside(al_pl_riot1)" },
  { value: "23", label: "Riot Muffled(al_pl_riot2)" },
  { value: "24", label: "Combat Outside 1(al_pl_combat1)" },
  { value: "25", label: "Combat Outside 2(al_pl_combat2)" },
  { value: "26", label: "Combat Muffled 1(al_pl_combatmuf1)" },
  { value: "27", label: "Combat Muffled 2(al_pl_combatmuf2)" },
  { value: "28", label: "Dungeon Lava Lake(al_na_lavalake1)" },
  { value: "29", label: "Sewer Sludge Lake(al_na_sludglake1)" },
  { value: "30", label: "Wind Soft(al_wt_windsoft1)" },
  { value: "31", label: "Wind Medium(al_wt_windmed1)" },
  { value: "32", label: "Wind Strong(al_wt_windstrng1)" },
  { value: "33", label: "Wind Forest(al_wt_windforst1)" },
  { value: "34", label: "Wind Chasm(al_wt_gustchasm1)" },
  { value: "35", label: "Wind Cavern(al_wt_gustcavrn1)" },
  { value: "36", label: "Wind Grass(al_wt_gustgrass1)" },
  { value: "37", label: "Wind Draft(al_wt_gustdraft1)" },
  { value: "38", label: "Rain Light(al_wt_rainlight1)" },
  { value: "39", label: "Rain Hard(al_wt_rainhard1)" },
  { value: "40", label: "Rainstorm Small(al_wt_stormsm1)" },
  { value: "41", label: "Rainstorm Big(al_wt_stormlg1)" },
  { value: "42", label: "Cave Insects 1(al_an_bugscave1)" },
  { value: "43", label: "Cave Insects 2(al_an_bugscave2)" },
  { value: "44", label: "Interior Insects 1(al_an_bughouse1)" },
  { value: "45", label: "Interior Insects 2(al_an_bughouse2)" },
  { value: "46", label: "Lizardfolk Cave Crystals(al_an_lizrdflk1)" },
  { value: "47", label: "Sewers 1(al_cv_seweramb1)" },
  { value: "48", label: "Sewers 2(al_cv_seweramb2)" },
  { value: "49", label: "Forest Day 1(al_na_frstdyamb1)" },
  { value: "50", label: "Forest Day 2(al_na_frstdyamb2)" },
  { value: "51", label: "Forest Day 3(al_na_frstdyamb3)" },
  { value: "52", label: "Forest Day Scary(al_na_frstdyscr1)" },
  { value: "53", label: "Forest Night 1(al_na_frstntamb1)" },
  { value: "54", label: "Forest Night 2(al_na_frstntamb2)" },
  { value: "55", label: "Forest Night Scary(al_na_frstntscr1)" },
  { value: "56", label: "Forest Magical(al_na_frstmagic1)" },
  { value: "57", label: "Evil Dungeon Small(al_cv_evldunamb1)" },
  { value: "58", label: "Evil Dungeon Medium(al_cv_evldunamb2)" },
  { value: "59", label: "Evil Dungeon Large(al_cv_evldunamb3)" },
  { value: "60", label: "Cave Small(al_cv_caveamb1)" },
  { value: "61", label: "Cave Medium(al_cv_caveamb2)" },
  { value: "62", label: "Cave Large(al_cv_caveamb3)" },
  { value: "63", label: "Mine Small(al_cv_mineamb1)" },
  { value: "64", label: "Mine Medium(al_cv_mineamb2)" },
  { value: "65", label: "Mine Large(al_cv_mineamb3)" },
  { value: "66", label: "Castle Interior Small(al_cv_castleamb1)" },
  { value: "67", label: "Castle Interior Medium(al_cv_castleamb2)" },
  { value: "68", label: "Castle Interior Large(al_cv_castleamb3)" },
  { value: "69", label: "Crypt Small(al_cv_cryptamb1)" },
  { value: "70", label: "Crypt Medium 1(al_cv_cryptamb2)" },
  { value: "71", label: "Crypt Medium 2(al_cv_cryptamb3)" },
  { value: "72", label: "House Interior 1(al_cv_houseamb1)" },
  { value: "73", label: "House Interior 2(al_cv_houseamb2)" },
  { value: "74", label: "House Interior 3(al_cv_houseamb3)" },
  { value: "75", label: "Kitchen Interior Small(al_cv_kitchamb1)" },
  { value: "76", label: "Kitchen Interior Large(al_cv_kitchamb2)" },
  { value: "77", label: "Haunted Interior 1(al_cv_hauntamb1)" },
  { value: "78", label: "Haunted Interior 2(al_cv_hauntamb2)" },
  { value: "79", label: "Haunted Interior 3(al_cv_hauntamb3)" },
  { value: "80", label: "Blacksmith Shop(al_pl_blacksmith)" },
  { value: "81", label: "Pit Cries(al_mg_pitcry1)" },
  { value: "82", label: "Magical Interior Small(al_mg_magicint1)" },
  { value: "83", label: "Magical Interior Medium(al_mg_magicint2)" },
  { value: "84", label: "Magical Interior Large(al_mg_magicint3)" },
  { value: "85", label: "Magical Interior Evil(al_mg_magicint4)" },
  { value: "86", label: "Magical Interior Firelab(al_mg_firelab1)" },
  { value: "87", label: "Magical Interior Earthlab(al_mg_earthlab1)" },
  { value: "88", label: "Magical Interior Airlab(al_mg_airlab1)" },
  { value: "89", label: "Magical Interior Waterlab(al_mg_waterlab1)" },
  { value: "90", label: "Winter Day Wet(al_na_x0snw1)" },
  { value: "91", label: "Winter Day Windy(al_na_x0snw2)" },
  { value: "92", label: "Desert Day(al_na_x0des1)" },
  { value: "93", label: "Desert Night(al_na_x0des2)" },
  { value: "94", label: "Monastery Interior(al_mg_x0ssan)" },
  { value: "96", label: "Ruins, Wet(al_mg_x0rui1)" },
  { value: "97", label: "Ruins, Rumbling(al_mg_x0rui2)" },
  { value: "98", label: "Ruins, Haunted(al_mg_x0rui3)" },
  { value: "99", label: "Sandstorm, Light(al_na_x0sstm1)" },
  { value: "100", label: "Sandstorm, Extreme(al_na_x0sstm2)" },
  { value: "101", label: "Evil Drone(al_mg_x2evdrone)" },
  { value: "102", label: "Plane of Fire(al_mg_x2fireplan)" },
  { value: "103", label: "Frozen Hell(al_mg_x2frznhell)" },
  { value: "104", label: "Cave Evil 1(al_na_x2evcavlrg)" },
  { value: "105", label: "Cave Evil 2(al_na_x2evcavmed)" },
  { value: "106", label: "Cave Evil 3(al_na_x2evcavsml)" },
  { value: "107", label: "Tavern, Rowdy(al_pl_x2tavern)" },
  { value: "108", label: "Sea Surf Small(al_na_seawaves)" },
  { value: "109", label: "Sea Surf Large(al_na_seawaves2)" },
  { value: "110", label: "Crow Caws(al_wt_windcrows)" },
  { value: "111", label: "Crow Caws(al_wt_windcrows2)" },
  { value: "112", label: "Owl Hoots(al_wt_windowls)" },
  { value: "113", label: "Owl HootsNIGHT(al_wt_windowls2)" },
];
