import { DropdownListItem } from ".";

export const EnvironmentalEffects: DropdownListItem[] = [
  { value: "0", label: "(Generic)" },
  { value: "1", label: "Padded Cell" },
  { value: "2", label: "Room" },
  { value: "3", label: "Bathroom" },
  { value: "4", label: "Living Room" },
  { value: "5", label: "Stone Room" },
  { value: "6", label: "Auditorium" },
  { value: "7", label: "Concert Hall" },
  { value: "8", label: "Cave" },
  { value: "9", label: "Arena" },
  { value: "10", label: "Hangar" },
  { value: "11", label: "Carpeted Hallway" },
  { value: "12", label: "Hallway" },
  { value: "13", label: "Stone Corridor" },
  { value: "14", label: "Alley" },
  { value: "15", label: "Forest" },
  { value: "16", label: "City" },
  { value: "17", label: "Mountains" },
  { value: "18", label: "Quarry" },
  { value: "19", label: "Plain" },
  { value: "20", label: "Parking Lot" },
  { value: "21", label: "Sewer Pipe" },
  { value: "22", label: "Underwater" },
  { value: "23", label: "Drugged" },
  { value: "24", label: "Dizzy" },
  { value: "25", label: "Psychotic" },
  { value: "26", label: "Castle, small room" },
  { value: "27", label: "Castle, short passage" },
  { value: "28", label: "Castle, medium room" },
  { value: "29", label: "Castle, long passage" },
  { value: "30", label: "Castle, large room" },
  { value: "31", label: "Castle, hall" },
  { value: "32", label: "Castle, cupboard" },
  { value: "33", label: "Castle, courtyard" },
  { value: "34", label: "Castle, alcove" },
  { value: "35", label: "Factory, alcove" },
  { value: "36", label: "Factory, short passage" },
  { value: "37", label: "Factory, medium room" },
  { value: "38", label: "Factory, long passage" },
  { value: "39", label: "Factory, large room" },
  { value: "40", label: "Factory, hall" },
  { value: "41", label: "Factory, cupboard" },
  { value: "42", label: "Factory, courtyard" },
  { value: "43", label: "Factory, small room" },
  { value: "44", label: "Ice palace, alcove" },
  { value: "45", label: "Ice palace, short passage" },
  { value: "46", label: "Ice palace, medium room" },
  { value: "47", label: "Ice palace, long passage" },
  { value: "48", label: "Ice palace, large room" },
  { value: "49", label: "Ice palace, hall" },
  { value: "50", label: "Ice palace, cupboard" },
  { value: "51", label: "Ice palace, courtyard" },
  { value: "52", label: "Ice palace, small room" },
  { value: "53", label: "Space station, alcove" },
  { value: "54", label: "Space station, medium room" },
  { value: "55", label: "Space station, short passage" },
  { value: "56", label: "Space station, long passage" },
  { value: "57", label: "Space station, large room" },
  { value: "58", label: "Space station, hall" },
  { value: "59", label: "Space station, cupboard" },
  { value: "60", label: "Space station, small room" },
  { value: "61", label: "Wooden, alcove" },
  { value: "62", label: "Wooden, short passage" },
  { value: "63", label: "Wooden, medium room" },
  { value: "64", label: "Wooden, long passage" },
  { value: "65", label: "Wooden, large room" },
  { value: "66", label: "Wooden, hall" },
  { value: "67", label: "Wooden, cupboard" },
  { value: "68", label: "Wooden, small room" },
  { value: "69", label: "Wooden, courtyard" },
  { value: "70", label: "Sport, empty stadium" },
  { value: "71", label: "Sport, squash court" },
  { value: "72", label: "Sport, small swimming pool" },
  { value: "73", label: "Sport, large swimming pool" },
  { value: "74", label: "Sport, gymnasium" },
  { value: "75", label: "Sport, full stadium" },
  { value: "76", label: "Sport, stadium tannoy" },
  { value: "77", label: "Prefab, workshop" },
  { value: "78", label: "Prefab, school room" },
  { value: "79", label: "Prefab, practise room" },
  { value: "80", label: "Prefab, outhouse" },
  { value: "81", label: "Prefab, caravan" },
  { value: "82", label: "Dome, tomb" },
  { value: "83", label: "Dome, saint paul's" },
  { value: "84", label: "Pipe, small" },
  { value: "85", label: "Pipe, long and thin" },
  { value: "86", label: "Pipe, large" },
  { value: "87", label: "Pipe, resonant" },
  { value: "88", label: "Outdoors, backyard" },
  { value: "89", label: "Outdoors, rolling plains" },
  { value: "90", label: "Outdoors, deep canyon" },
  { value: "91", label: "Outdoors, creek" },
  { value: "92", label: "Outdoors, valley" },
  { value: "93", label: "Mood, heaven" },
  { value: "94", label: "Mood, hell" },
  { value: "95", label: "Mood, memory" },
  { value: "96", label: "Driving, commentator" },
  { value: "97", label: "Driving, pit garage" },
  { value: "98", label: "Driving, incar racer" },
  { value: "99", label: "Driving, incar sports" },
  { value: "100", label: "Driving, incar luxury" },
  { value: "101", label: "Driving, full grandstand" },
  { value: "102", label: "Driving, empty grandstand" },
  { value: "103", label: "Driving, tunnel" },
  { value: "104", label: "City, streets" },
  { value: "105", label: "City, subway" },
  { value: "106", label: "City, museum" },
  { value: "107", label: "City, library" },
  { value: "108", label: "City, underpass" },
  { value: "109", label: "City, abandoned" },
  { value: "110", label: "Dusty room" },
  { value: "111", label: "Chapel" },
  { value: "112", label: "Small water room" },
];
