import { DropdownListItem } from ".";

export const Feats: DropdownListItem[] = [
  { value: "311", label: "Air Domain Powers" },
  { value: "0", label: "Alertness" },
  { value: "1", label: "Ambidexterity" },
  { value: "199", label: "Animal Companion" },
  { value: "312", label: "Animal Domain Powers" },
  { value: "889", label: "Animate Dead" },
  { value: "415", label: "Arcane Defense (Abjuration)" },
  { value: "416", label: "Arcane Defense (Conjuration)" },
  { value: "417", label: "Arcane Defense (Divination)" },
  { value: "418", label: "Arcane Defense (Enchantment)" },
  { value: "419", label: "Arcane Defense (Evocation)" },
  { value: "420", label: "Arcane Defense (Illusion)" },
  { value: "421", label: "Arcane Defense (Necromancy)" },
  { value: "422", label: "Arcane Defense (Transmutation)" },
  { value: "2", label: "Armor Proficiency (heavy)" },
  { value: "3", label: "Armor Proficiency (light)" },
  { value: "4", label: "Armor Proficiency (medium)" },
  { value: "490", label: "Armor Skin" },
  { value: "454", label: "Arrow of Death" },
  { value: "378", label: "Artist" },
  { value: "1094", label: "Assign Mount" },
  { value: "300", label: "Aura of Courage" },
  { value: "857", label: "Automatic Quicken Spell I" },
  { value: "858", label: "Automatic Quicken Spell II" },
  { value: "859", label: "Automatic Quicken Spell III" },
  { value: "860", label: "Automatic Silent Spell I" },
  { value: "861", label: "Automatic Silent Spell II" },
  { value: "862", label: "Automatic Silent Spell III" },
  { value: "863", label: "Automatic Still Spell I" },
  { value: "864", label: "Automatic Still Spell II" },
  { value: "865", label: "Automatic Still Spell III" },
  { value: "855", label: "Bane of Enemies" },
  { value: "194", label: "Barbarian Fast Movement" },
  { value: "293", label: "Barbarian Rage (1x per day)" },
  { value: "326", label: "Barbarian Rage (2x per day)" },
  { value: "327", label: "Barbarian Rage (3x per day)" },
  { value: "328", label: "Barbarian Rage (4x per day)" },
  { value: "359", label: "Bard Song" },
  { value: "365", label: "Bard Song" },
  { value: "373", label: "Bard Song" },
  { value: "372", label: "Bard Song" },
  { value: "371", label: "Bard Song" },
  { value: "370", label: "Bard Song" },
  { value: "369", label: "Bard Song" },
  { value: "368", label: "Bard Song" },
  { value: "367", label: "Bard Song" },
  { value: "366", label: "Bard Song" },
  { value: "360", label: "Bard Song" },
  { value: "358", label: "Bard Song" },
  { value: "257", label: "Bard Song" },
  { value: "364", label: "Bard Song" },
  { value: "363", label: "Bard Song" },
  { value: "362", label: "Bard Song" },
  { value: "361", label: "Bard Song" },
  { value: "355", label: "Bard Song" },
  { value: "356", label: "Bard Song" },
  { value: "357", label: "Bard Song" },
  { value: "197", label: "Bardic Knowledge" },
  { value: "233", label: "Battle Training vs. Giants" },
  { value: "232", label: "Battle Training vs. Goblins" },
  { value: "231", label: "Battle Training vs. Orcs" },
  { value: "242", label: "Battle Training vs. Reptilians" },
  { value: "408", label: "Blind-Fight" },
  { value: "491", label: "Blinding Speed" },
  { value: "488", label: "Blindsight, 60 foot radius" },
  { value: "379", label: "Blooded" },
  { value: "886", label: "Bone Skin" },
  { value: "944", label: "Brew Potion" },
  { value: "478", label: "Bull's Strength" },
  { value: "380", label: "Bullheaded" },
  { value: "5", label: "Called Shot" },
  { value: "442", label: "Cat's Grace" },
  { value: "409", label: "Circle Kick" },
  { value: "6", label: "Cleave" },
  { value: "7", label: "Combat Casting" },
  { value: "1061", label: "Construct Shape" },
  { value: "479", label: "Contagion" },
  { value: "381", label: "Courteous Magocracy" },
  { value: "440", label: "Craft Harper Item" },
  { value: "946", label: "Craft Wand" },
  { value: "474", label: "Create Undead" },
  { value: "222", label: "Crippling Strike" },
  { value: "871", label: "Curse Song" },
  { value: "1096", label: "DM Tool 1" },
  { value: "1105", label: "DM Tool 10" },
  { value: "1097", label: "DM Tool 2" },
  { value: "1098", label: "DM Tool 3" },
  { value: "1099", label: "DM Tool 4" },
  { value: "1100", label: "DM Tool 5" },
  { value: "1101", label: "DM Tool 6" },
  { value: "1102", label: "DM Tool 7" },
  { value: "1103", label: "DM Tool 8" },
  { value: "1104", label: "DM Tool 9" },
  { value: "196", label: "Damage Reduction 1" },
  { value: "332", label: "Damage Reduction 2" },
  { value: "333", label: "Damage Reduction 3" },
  { value: "334", label: "Damage Reduction 4" },
  { value: "473", label: "Dark Blessing" },
  { value: "469", label: "Darkness" },
  { value: "228", label: "Darkvision" },
  { value: "1020", label: "Death Attack (+10d6)" },
  { value: "1021", label: "Death Attack (+11d6)" },
  { value: "1022", label: "Death Attack (+12d6)" },
  { value: "1023", label: "Death Attack (+13d6)" },
  { value: "1024", label: "Death Attack (+14d6)" },
  { value: "1025", label: "Death Attack (+15d6)" },
  { value: "1026", label: "Death Attack (+16d6)" },
  { value: "1027", label: "Death Attack (+17d6)" },
  { value: "1028", label: "Death Attack (+18d6)" },
  { value: "1029", label: "Death Attack (+19d6)" },
  { value: "455", label: "Death Attack (+1d6)" },
  { value: "1030", label: "Death Attack (+20d6)" },
  { value: "456", label: "Death Attack (+2d6)" },
  { value: "457", label: "Death Attack (+3d6)" },
  { value: "458", label: "Death Attack (+4d6)" },
  { value: "459", label: "Death Attack (+5d6)" },
  { value: "1004", label: "Death Attack (+6d6)" },
  { value: "1005", label: "Death Attack (+7d6)" },
  { value: "1006", label: "Death Attack (+8d6)" },
  { value: "1019", label: "Death Attack (+9d6)" },
  { value: "310", label: "Death Domain Powers" },
  { value: "897", label: "Deathless Master Touch" },
  { value: "896", label: "Deathless Mastery" },
  { value: "891", label: "Deathless Vigor" },
  { value: "949", label: "Defensive Awareness (1)" },
  { value: "950", label: "Defensive Awareness (2)" },
  { value: "951", label: "Defensive Awareness (3)" },
  { value: "223", label: "Defensive Roll" },
  { value: "947", label: "Defensive Stance" },
  { value: "8", label: "Deflect Arrows" },
  { value: "437", label: "Deneir's Eye" },
  { value: "313", label: "Destruction Domain Powers" },
  { value: "528", label: "Devastating Critical (bastard sword)" },
  { value: "516", label: "Devastating Critical (battleaxe)" },
  { value: "495", label: "Devastating Critical (club)" },
  { value: "532", label: "Devastating Critical (creature)" },
  { value: "496", label: "Devastating Critical (dagger)" },
  { value: "497", label: "Devastating Critical (dart)" },
  { value: "529", label: "Devastating Critical (dire mace)" },
  { value: "530", label: "Devastating Critical (double axe)" },
  { value: "955", label: "Devastating Critical (dwarven waraxe)" },
  { value: "517", label: "Devastating Critical (greataxe)" },
  { value: "513", label: "Devastating Critical (greatsword)" },
  { value: "518", label: "Devastating Critical (halberd)" },
  { value: "514", label: "Devastating Critical (handaxe)" },
  { value: "498", label: "Devastating Critical (heavy crossbow)" },
  { value: "522", label: "Devastating Critical (heavy flail)" },
  { value: "523", label: "Devastating Critical (kama)" },
  { value: "527", label: "Devastating Critical (katana)" },
  { value: "524", label: "Devastating Critical (kukri)" },
  { value: "499", label: "Devastating Critical (light crossbow)" },
  { value: "520", label: "Devastating Critical (light flail)" },
  { value: "519", label: "Devastating Critical (light hammer)" },
  { value: "507", label: "Devastating Critical (longbow)" },
  { value: "512", label: "Devastating Critical (longsword)" },
  { value: "500", label: "Devastating Critical (mace)" },
  { value: "501", label: "Devastating Critical (morningstar)" },
  { value: "502", label: "Devastating Critical (quarterstaff)" },
  { value: "510", label: "Devastating Critical (rapier)" },
  { value: "511", label: "Devastating Critical (scimitar)" },
  { value: "526", label: "Devastating Critical (scythe)" },
  { value: "508", label: "Devastating Critical (shortbow)" },
  { value: "509", label: "Devastating Critical (shortsword)" },
  { value: "525", label: "Devastating Critical (shuriken)" },
  { value: "504", label: "Devastating Critical (sickle)" },
  { value: "505", label: "Devastating Critical (sling)" },
  { value: "503", label: "Devastating Critical (spear)" },
  { value: "515", label: "Devastating Critical (throwing axe)" },
  { value: "1075", label: "Devastating Critical (trident)" },
  { value: "531", label: "Devastating Critical (two-bladed sword)" },
  { value: "506", label: "Devastating Critical (unarmed strike)" },
  { value: "521", label: "Devastating Critical (warhammer)" },
  { value: "996", label: "Devastating Critical (whip)" },
  { value: "214", label: "Diamond Body" },
  { value: "215", label: "Diamond Soul" },
  { value: "425", label: "Dirty Fighting" },
  { value: "9", label: "Disarm" },
  { value: "217", label: "Divine Grace" },
  { value: "219", label: "Divine Health" },
  { value: "413", label: "Divine Might" },
  { value: "414", label: "Divine Shield" },
  { value: "909", label: "Divine Wrath" },
  { value: "10", label: "Dodge" },
  { value: "961", label: "Draconic Armor" },
  { value: "962", label: "Dragon Abilities" },
  { value: "965", label: "Dragon Breath" },
  { value: "873", label: "Dragon Shape" },
  { value: "374", label: "Dual-Wield" },
  { value: "948", label: "Dwarven Defender Damage Reduction" },
  { value: "443", label: "Eagle's Splendor" },
  { value: "314", label: "Earth Domain Powers" },
  { value: "304", label: "Elemental Shape" },
  { value: "340", label: "Elemental Shape (2x day)" },
  { value: "341", label: "Elemental Shape (3x day)" },
  { value: "11", label: "Empower Spell" },
  { value: "297", label: "Empty Body" },
  { value: "445", label: "Enchant Arrow I" },
  { value: "446", label: "Enchant Arrow II" },
  { value: "447", label: "Enchant Arrow III" },
  { value: "448", label: "Enchant Arrow IV" },
  { value: "1048", label: "Enchant Arrow IX" },
  { value: "449", label: "Enchant Arrow V" },
  { value: "1045", label: "Enchant Arrow VI" },
  { value: "1046", label: "Enchant Arrow VII" },
  { value: "1047", label: "Enchant Arrow VIII" },
  { value: "1049", label: "Enchant Arrow X" },
  { value: "1050", label: "Enchant Arrow XI" },
  { value: "1051", label: "Enchant Arrow XII" },
  { value: "1052", label: "Enchant Arrow XIII" },
  { value: "1053", label: "Enchant Arrow XIV" },
  { value: "1058", label: "Enchant Arrow XIX" },
  { value: "1054", label: "Enchant Arrow XV" },
  { value: "1055", label: "Enchant Arrow XVI" },
  { value: "1056", label: "Enchant Arrow XVII" },
  { value: "1057", label: "Enchant Arrow XVIII" },
  { value: "1059", label: "Enchant Arrow XX" },
  { value: "543", label: "Energy Resistance, Acid I" },
  { value: "544", label: "Energy Resistance, Acid II" },
  { value: "545", label: "Energy Resistance, Acid III" },
  { value: "546", label: "Energy Resistance, Acid IV" },
  { value: "551", label: "Energy Resistance, Acid IX" },
  { value: "547", label: "Energy Resistance, Acid V" },
  { value: "548", label: "Energy Resistance, Acid VI" },
  { value: "549", label: "Energy Resistance, Acid VII" },
  { value: "550", label: "Energy Resistance, Acid VIII" },
  { value: "552", label: "Energy Resistance, Acid X" },
  { value: "533", label: "Energy Resistance, Cold I" },
  { value: "534", label: "Energy Resistance, Cold II" },
  { value: "535", label: "Energy Resistance, Cold III" },
  { value: "536", label: "Energy Resistance, Cold IV" },
  { value: "541", label: "Energy Resistance, Cold IX" },
  { value: "537", label: "Energy Resistance, Cold V" },
  { value: "538", label: "Energy Resistance, Cold VI" },
  { value: "539", label: "Energy Resistance, Cold VII" },
  { value: "540", label: "Energy Resistance, Cold VIII" },
  { value: "542", label: "Energy Resistance, Cold X" },
  { value: "563", label: "Energy Resistance, Electrical I" },
  { value: "564", label: "Energy Resistance, Electrical II" },
  { value: "565", label: "Energy Resistance, Electrical III" },
  { value: "566", label: "Energy Resistance, Electrical IV" },
  { value: "571", label: "Energy Resistance, Electrical IX" },
  { value: "567", label: "Energy Resistance, Electrical V" },
  { value: "568", label: "Energy Resistance, Electrical VI" },
  { value: "569", label: "Energy Resistance, Electrical VII" },
  { value: "570", label: "Energy Resistance, Electrical VIII" },
  { value: "572", label: "Energy Resistance, Electrical X" },
  { value: "553", label: "Energy Resistance, Fire I" },
  { value: "554", label: "Energy Resistance, Fire II" },
  { value: "555", label: "Energy Resistance, Fire III" },
  { value: "556", label: "Energy Resistance, Fire IV" },
  { value: "561", label: "Energy Resistance, Fire IX" },
  { value: "557", label: "Energy Resistance, Fire V" },
  { value: "558", label: "Energy Resistance, Fire VI" },
  { value: "559", label: "Energy Resistance, Fire VII" },
  { value: "560", label: "Energy Resistance, Fire VIII" },
  { value: "562", label: "Energy Resistance, Fire X" },
  { value: "573", label: "Energy Resistance, Sonic I" },
  { value: "574", label: "Energy Resistance, Sonic II" },
  { value: "575", label: "Energy Resistance, Sonic III" },
  { value: "576", label: "Energy Resistance, Sonic IV" },
  { value: "581", label: "Energy Resistance, Sonic IX" },
  { value: "577", label: "Energy Resistance, Sonic V" },
  { value: "578", label: "Energy Resistance, Sonic VI" },
  { value: "579", label: "Energy Resistance, Sonic VII" },
  { value: "580", label: "Energy Resistance, Sonic VIII" },
  { value: "582", label: "Energy Resistance, Sonic X" },
  { value: "977", label: "Epic Arcane Archer" },
  { value: "978", label: "Epic Assassin" },
  { value: "967", label: "Epic Barbarian" },
  { value: "1067", label: "Epic Barbarian Damage Reduction" },
  { value: "968", label: "Epic Bard" },
  { value: "979", label: "Epic Blackguard" },
  { value: "982", label: "Epic Champion of Torm" },
  { value: "1001", label: "Epic Character" },
  { value: "969", label: "Epic Cleric" },
  { value: "492", label: "Epic Damage Reduction I" },
  { value: "493", label: "Epic Damage Reduction II" },
  { value: "494", label: "Epic Damage Reduction III" },
  { value: "856", label: "Epic Dodge" },
  { value: "970", label: "Epic Druid" },
  { value: "985", label: "Epic Dwarven Defender" },
  { value: "1003", label: "Epic Fiendish Servant" },
  { value: "966", label: "Epic Fighter" },
  { value: "583", label: "Epic Fortitude" },
  { value: "971", label: "Epic Monk" },
  { value: "972", label: "Epic Paladin" },
  { value: "984", label: "Epic Palemaster" },
  { value: "584", label: "Epic Prowess" },
  { value: "973", label: "Epic Ranger" },
  { value: "987", label: "Epic Red Dragon Disciple" },
  { value: "585", label: "Epic Reflexes" },
  { value: "586", label: "Epic Reputation" },
  { value: "974", label: "Epic Rogue" },
  { value: "980", label: "Epic Shadowdancer" },
  { value: "1002", label: "Epic Shadowlord" },
  { value: "986", label: "Epic Shifter" },
  { value: "587", label: "Epic Skill Focus (Animal Empathy)" },
  { value: "588", label: "Epic Skill Focus (Appraise)" },
  { value: "917", label: "Epic Skill Focus (Bluff)" },
  { value: "589", label: "Epic Skill Focus (Concentration)" },
  { value: "913", label: "Epic Skill Focus (Craft Armor)" },
  { value: "590", label: "Epic Skill Focus (Craft Trap)" },
  { value: "914", label: "Epic Skill Focus (Craft Weapon)" },
  { value: "591", label: "Epic Skill Focus (Disable Trap)" },
  { value: "592", label: "Epic Skill Focus (Discipline)" },
  { value: "593", label: "Epic Skill Focus (Heal)" },
  { value: "594", label: "Epic Skill Focus (Hide)" },
  { value: "918", label: "Epic Skill Focus (Intimidate)" },
  { value: "595", label: "Epic Skill Focus (Listen)" },
  { value: "596", label: "Epic Skill Focus (Lore)" },
  { value: "597", label: "Epic Skill Focus (Move Silently)" },
  { value: "598", label: "Epic Skill Focus (Open Lock)" },
  { value: "599", label: "Epic Skill Focus (Parry)" },
  { value: "600", label: "Epic Skill Focus (Perform)" },
  { value: "601", label: "Epic Skill Focus (Persuade)" },
  { value: "602", label: "Epic Skill Focus (Pick Pocket)" },
  { value: "603", label: "Epic Skill Focus (Search)" },
  { value: "604", label: "Epic Skill Focus (Set Trap)" },
  { value: "605", label: "Epic Skill Focus (Spellcraft)" },
  { value: "606", label: "Epic Skill Focus (Spot)" },
  { value: "607", label: "Epic Skill Focus (Taunt)" },
  { value: "608", label: "Epic Skill Focus (Tumble)" },
  { value: "609", label: "Epic Skill Focus (Use Magic Device)" },
  { value: "975", label: "Epic Sorcerer" },
  { value: "610", label: "Epic Spell Focus (Abjuration)" },
  { value: "611", label: "Epic Spell Focus (Conjuration)" },
  { value: "612", label: "Epic Spell Focus (Divination)" },
  { value: "613", label: "Epic Spell Focus (Enchantment)" },
  { value: "614", label: "Epic Spell Focus (Evocation)" },
  { value: "615", label: "Epic Spell Focus (Illusion)" },
  { value: "616", label: "Epic Spell Focus (Necromancy)" },
  { value: "617", label: "Epic Spell Focus (Transmutation)" },
  { value: "618", label: "Epic Spell Penetration" },
  { value: "875", label: "Epic Spell: Dragon Knight" },
  { value: "877", label: "Epic Spell: Epic Mage Armor" },
  { value: "990", label: "Epic Spell: Epic Warding" },
  { value: "878", label: "Epic Spell: Greater Ruin" },
  { value: "876", label: "Epic Spell: Hellball" },
  { value: "874", label: "Epic Spell: Mummy Dust" },
  { value: "1071", label: "Epic Superior Weapon Focus" },
  { value: "754", label: "Epic Toughness I" },
  { value: "755", label: "Epic Toughness II" },
  { value: "756", label: "Epic Toughness III" },
  { value: "757", label: "Epic Toughness IV" },
  { value: "762", label: "Epic Toughness IX" },
  { value: "758", label: "Epic Toughness V" },
  { value: "759", label: "Epic Toughness VI" },
  { value: "760", label: "Epic Toughness VII" },
  { value: "761", label: "Epic Toughness VIII" },
  { value: "763", label: "Epic Toughness X" },
  { value: "652", label: "Epic Weapon Focus (bastard sword)" },
  { value: "640", label: "Epic Weapon Focus (battleaxe)" },
  { value: "619", label: "Epic Weapon Focus (club)" },
  { value: "656", label: "Epic Weapon Focus (creature weapon)" },
  { value: "620", label: "Epic Weapon Focus (dagger)" },
  { value: "621", label: "Epic Weapon Focus (dart)" },
  { value: "653", label: "Epic Weapon Focus (dire mace)" },
  { value: "654", label: "Epic Weapon Focus (double axe)" },
  { value: "956", label: "Epic Weapon Focus (dwarven waraxe)" },
  { value: "641", label: "Epic Weapon Focus (greataxe)" },
  { value: "637", label: "Epic Weapon Focus (greatsword)" },
  { value: "642", label: "Epic Weapon Focus (halberd)" },
  { value: "638", label: "Epic Weapon Focus (handaxe)" },
  { value: "622", label: "Epic Weapon Focus (heavy crossbow)" },
  { value: "646", label: "Epic Weapon Focus (heavy flail)" },
  { value: "647", label: "Epic Weapon Focus (kama)" },
  { value: "651", label: "Epic Weapon Focus (katana)" },
  { value: "648", label: "Epic Weapon Focus (kukri)" },
  { value: "623", label: "Epic Weapon Focus (light crossbow)" },
  { value: "644", label: "Epic Weapon Focus (light flail)" },
  { value: "643", label: "Epic Weapon Focus (light hammer)" },
  { value: "631", label: "Epic Weapon Focus (longbow)" },
  { value: "636", label: "Epic Weapon Focus (longsword)" },
  { value: "624", label: "Epic Weapon Focus (mace)" },
  { value: "625", label: "Epic Weapon Focus (morningstar)" },
  { value: "626", label: "Epic Weapon Focus (quarterstaff)" },
  { value: "634", label: "Epic Weapon Focus (rapier)" },
  { value: "635", label: "Epic Weapon Focus (scimitar)" },
  { value: "650", label: "Epic Weapon Focus (scythe)" },
  { value: "632", label: "Epic Weapon Focus (shortbow)" },
  { value: "633", label: "Epic Weapon Focus (shortsword)" },
  { value: "649", label: "Epic Weapon Focus (shuriken)" },
  { value: "628", label: "Epic Weapon Focus (sickle)" },
  { value: "629", label: "Epic Weapon Focus (sling)" },
  { value: "627", label: "Epic Weapon Focus (spear)" },
  { value: "639", label: "Epic Weapon Focus (throwing axe)" },
  { value: "1076", label: "Epic Weapon Focus (trident)" },
  { value: "655", label: "Epic Weapon Focus (two-bladed sword)" },
  { value: "630", label: "Epic Weapon Focus (unarmed strike)" },
  { value: "645", label: "Epic Weapon Focus (warhammer)" },
  { value: "997", label: "Epic Weapon Focus (whip)" },
  { value: "983", label: "Epic Weapon Master" },
  { value: "690", label: "Epic Weapon Specialization (bastard sword)" },
  { value: "678", label: "Epic Weapon Specialization (battleaxe)" },
  { value: "657", label: "Epic Weapon Specialization (club)" },
  { value: "694", label: "Epic Weapon Specialization (creature weapon)" },
  { value: "658", label: "Epic Weapon Specialization (dagger)" },
  { value: "659", label: "Epic Weapon Specialization (dart)" },
  { value: "691", label: "Epic Weapon Specialization (dire mace)" },
  { value: "692", label: "Epic Weapon Specialization (double axe)" },
  { value: "957", label: "Epic Weapon Specialization (dwarven waraxe)" },
  { value: "679", label: "Epic Weapon Specialization (greataxe)" },
  { value: "675", label: "Epic Weapon Specialization (greatsword)" },
  { value: "680", label: "Epic Weapon Specialization (halberd)" },
  { value: "676", label: "Epic Weapon Specialization (handaxe)" },
  { value: "660", label: "Epic Weapon Specialization (heavy crossbow)" },
  { value: "684", label: "Epic Weapon Specialization (heavy flail)" },
  { value: "685", label: "Epic Weapon Specialization (kama)" },
  { value: "689", label: "Epic Weapon Specialization (katana)" },
  { value: "686", label: "Epic Weapon Specialization (kukri)" },
  { value: "661", label: "Epic Weapon Specialization (light crossbow)" },
  { value: "682", label: "Epic Weapon Specialization (light flail)" },
  { value: "681", label: "Epic Weapon Specialization (light hammer)" },
  { value: "669", label: "Epic Weapon Specialization (longbow)" },
  { value: "674", label: "Epic Weapon Specialization (longsword)" },
  { value: "662", label: "Epic Weapon Specialization (mace)" },
  { value: "663", label: "Epic Weapon Specialization (morningstar)" },
  { value: "664", label: "Epic Weapon Specialization (quarterstaff)" },
  { value: "672", label: "Epic Weapon Specialization (rapier)" },
  { value: "673", label: "Epic Weapon Specialization (scimitar)" },
  { value: "688", label: "Epic Weapon Specialization (scythe)" },
  { value: "670", label: "Epic Weapon Specialization (shortbow)" },
  { value: "671", label: "Epic Weapon Specialization (shortsword)" },
  { value: "687", label: "Epic Weapon Specialization (shuriken)" },
  { value: "666", label: "Epic Weapon Specialization (sickle)" },
  { value: "667", label: "Epic Weapon Specialization (sling)" },
  { value: "665", label: "Epic Weapon Specialization (spear)" },
  { value: "677", label: "Epic Weapon Specialization (throwing axe)" },
  { value: "1077", label: "Epic Weapon Specialization (trident)" },
  { value: "693", label: "Epic Weapon Specialization (two-bladed sword)" },
  { value: "668", label: "Epic Weapon Specialization (unarmed strike)" },
  { value: "683", label: "Epic Weapon Specialization (warhammer)" },
  { value: "998", label: "Epic Weapon Specialization (whip)" },
  { value: "695", label: "Epic Will" },
  { value: "976", label: "Epic Wizard" },
  { value: "206", label: "Evasion" },
  { value: "315", label: "Evil Domain Powers" },
  { value: "389", label: "Expertise" },
  { value: "12", label: "Extend Spell" },
  { value: "423", label: "Extra Music" },
  { value: "910", label: "Extra Smiting" },
  { value: "410", label: "Extra Stunning Attacks" },
  { value: "13", label: "Extra Turning" },
  { value: "268", label: "Favored Enemy: Aberrations" },
  { value: "269", label: "Favored Enemy: Animals" },
  { value: "270", label: "Favored Enemy: Beasts" },
  { value: "271", label: "Favored Enemy: Constructs" },
  { value: "272", label: "Favored Enemy: Dragons" },
  { value: "261", label: "Favored Enemy: Dwarves" },
  { value: "277", label: "Favored Enemy: Elementals" },
  { value: "262", label: "Favored Enemy: Elves" },
  { value: "278", label: "Favored Enemy: Fey" },
  { value: "279", label: "Favored Enemy: Giants" },
  { value: "263", label: "Favored Enemy: Gnomes" },
  { value: "273", label: "Favored Enemy: Goblinoids" },
  { value: "265", label: "Favored Enemy: Half-Elves" },
  { value: "266", label: "Favored Enemy: Half-Orcs" },
  { value: "264", label: "Favored Enemy: Halflings" },
  { value: "267", label: "Favored Enemy: Humans" },
  { value: "280", label: "Favored Enemy: Magical Beasts" },
  { value: "274", label: "Favored Enemy: Monstrous Humanoids" },
  { value: "275", label: "Favored Enemy: Orcs" },
  { value: "281", label: "Favored Enemy: Outsiders" },
  { value: "276", label: "Favored Enemy: Reptilian Humanoids" },
  { value: "284", label: "Favored Enemy: Shapechangers" },
  { value: "285", label: "Favored Enemy: Undead" },
  { value: "286", label: "Favored Enemy: Vermin" },
  { value: "1082", label: "Fear" },
  { value: "249", label: "Fearless" },
  { value: "1084", label: "Final Stand" },
  { value: "316", label: "Fire Domain Powers" },
  { value: "204", label: "Flurry of Blows" },
  { value: "468", label: "Ghostly Visage" },
  { value: "250", label: "Good Aim" },
  { value: "317", label: "Good Domain Powers" },
  { value: "764", label: "Great Charisma I" },
  { value: "765", label: "Great Charisma II" },
  { value: "766", label: "Great Charisma III" },
  { value: "767", label: "Great Charisma IV" },
  { value: "772", label: "Great Charisma IX" },
  { value: "768", label: "Great Charisma V" },
  { value: "769", label: "Great Charisma VI" },
  { value: "770", label: "Great Charisma VII" },
  { value: "771", label: "Great Charisma VIII" },
  { value: "773", label: "Great Charisma X" },
  { value: "391", label: "Great Cleave" },
  { value: "774", label: "Great Constitution I" },
  { value: "775", label: "Great Constitution II" },
  { value: "776", label: "Great Constitution III" },
  { value: "777", label: "Great Constitution IV" },
  { value: "782", label: "Great Constitution IX" },
  { value: "778", label: "Great Constitution V" },
  { value: "779", label: "Great Constitution VI" },
  { value: "780", label: "Great Constitution VII" },
  { value: "781", label: "Great Constitution VIII" },
  { value: "783", label: "Great Constitution X" },
  { value: "784", label: "Great Dexterity I" },
  { value: "785", label: "Great Dexterity II" },
  { value: "786", label: "Great Dexterity III" },
  { value: "787", label: "Great Dexterity IV" },
  { value: "792", label: "Great Dexterity IX" },
  { value: "788", label: "Great Dexterity V" },
  { value: "789", label: "Great Dexterity VI" },
  { value: "790", label: "Great Dexterity VII" },
  { value: "791", label: "Great Dexterity VIII" },
  { value: "793", label: "Great Dexterity X" },
  { value: "14", label: "Great Fortitude" },
  { value: "794", label: "Great Intelligence I" },
  { value: "795", label: "Great Intelligence II" },
  { value: "796", label: "Great Intelligence III" },
  { value: "797", label: "Great Intelligence IV" },
  { value: "802", label: "Great Intelligence IX" },
  { value: "798", label: "Great Intelligence V" },
  { value: "799", label: "Great Intelligence VI" },
  { value: "800", label: "Great Intelligence VII" },
  { value: "801", label: "Great Intelligence VIII" },
  { value: "803", label: "Great Intelligence X" },
  { value: "824", label: "Great Smiting I" },
  { value: "825", label: "Great Smiting II" },
  { value: "826", label: "Great Smiting III" },
  { value: "827", label: "Great Smiting IV" },
  { value: "832", label: "Great Smiting IX" },
  { value: "828", label: "Great Smiting V" },
  { value: "829", label: "Great Smiting VI" },
  { value: "830", label: "Great Smiting VII" },
  { value: "831", label: "Great Smiting VIII" },
  { value: "833", label: "Great Smiting X" },
  { value: "814", label: "Great Strength I" },
  { value: "815", label: "Great Strength II" },
  { value: "816", label: "Great Strength III" },
  { value: "817", label: "Great Strength IV" },
  { value: "822", label: "Great Strength IX" },
  { value: "818", label: "Great Strength V" },
  { value: "819", label: "Great Strength VI" },
  { value: "820", label: "Great Strength VII" },
  { value: "821", label: "Great Strength VIII" },
  { value: "823", label: "Great Strength X" },
  { value: "804", label: "Great Wisdom I" },
  { value: "805", label: "Great Wisdom II" },
  { value: "806", label: "Great Wisdom III" },
  { value: "807", label: "Great Wisdom IV" },
  { value: "812", label: "Great Wisdom IX" },
  { value: "808", label: "Great Wisdom V" },
  { value: "809", label: "Great Wisdom VI" },
  { value: "810", label: "Great Wisdom VII" },
  { value: "811", label: "Great Wisdom VIII" },
  { value: "813", label: "Great Wisdom X" },
  { value: "331", label: "Greater Rage" },
  { value: "329", label: "Greater Rage (4x per day)" },
  { value: "330", label: "Greater Rage (5x per day)" },
  { value: "393", label: "Greater Spell Focus (Abjuration)" },
  { value: "394", label: "Greater Spell Focus (Conjuration)" },
  { value: "395", label: "Greater Spell Focus (Divination)" },
  { value: "396", label: "Greater Spell Focus (Enchantment)" },
  { value: "397", label: "Greater Spell Focus (Evocation)" },
  { value: "398", label: "Greater Spell Focus (Illusion)" },
  { value: "399", label: "Greater Spell Focus (Necromancy)" },
  { value: "400", label: "Greater Spell Focus (Transmutation)" },
  { value: "401", label: "Greater Spell Penetration" },
  { value: "898", label: "Greater Wildshape I (wyrmling shape)" },
  { value: "900", label: "Greater Wildshape II" },
  { value: "901", label: "Greater Wildshape III" },
  { value: "903", label: "Greater Wildshape IV" },
  { value: "453", label: "Hail of Arrows" },
  { value: "236", label: "Hardiness vs. Enchantments" },
  { value: "241", label: "Hardiness vs. Illusions" },
  { value: "229", label: "Hardiness vs. Poisons" },
  { value: "230", label: "Hardiness vs. Spells" },
  { value: "318", label: "Healing Domain Powers" },
  { value: "1081", label: "Heroic Shield" },
  { value: "433", label: "Hide in Plain Sight" },
  { value: "1044", label: "Hit Die Increase (d10)" },
  { value: "1042", label: "Hit Die Increase (d6)" },
  { value: "1043", label: "Hit Die Increase (d8)" },
  { value: "902", label: "Humanoid Shape" },
  { value: "450", label: "Imbue Arrow" },
  { value: "235", label: "Immunity To Sleep" },
  { value: "964", label: "Immunity to Fire" },
  { value: "963", label: "Immunity to Paralysis" },
  { value: "696", label: "Improved Combat Casting" },
  { value: "85", label: "Improved Critical (bastard sword)" },
  { value: "72", label: "Improved Critical (battleaxe)" },
  { value: "15", label: "Improved Critical (club)" },
  { value: "292", label: "Improved Critical (creature)" },
  { value: "52", label: "Improved Critical (dagger)" },
  { value: "53", label: "Improved Critical (dart)" },
  { value: "87", label: "Improved Critical (dire mace)" },
  { value: "88", label: "Improved Critical (double axe)" },
  { value: "954", label: "Improved Critical (dwarven waraxe)" },
  { value: "73", label: "Improved Critical (greataxe)" },
  { value: "69", label: "Improved Critical (greatsword)" },
  { value: "74", label: "Improved Critical (halberd)" },
  { value: "70", label: "Improved Critical (handaxe)" },
  { value: "54", label: "Improved Critical (heavy crossbow)" },
  { value: "78", label: "Improved Critical (heavy flail)" },
  { value: "79", label: "Improved Critical (kama)" },
  { value: "84", label: "Improved Critical (katana)" },
  { value: "80", label: "Improved Critical (kukri)" },
  { value: "55", label: "Improved Critical (light crossbow)" },
  { value: "76", label: "Improved Critical (light flail)" },
  { value: "75", label: "Improved Critical (light hammer)" },
  { value: "63", label: "Improved Critical (longbow)" },
  { value: "68", label: "Improved Critical (longsword)" },
  { value: "56", label: "Improved Critical (mace)" },
  { value: "57", label: "Improved Critical (morningstar)" },
  { value: "58", label: "Improved Critical (quarterstaff)" },
  { value: "66", label: "Improved Critical (rapier)" },
  { value: "67", label: "Improved Critical (scimitar)" },
  { value: "83", label: "Improved Critical (scythe)" },
  { value: "65", label: "Improved Critical (short sword)" },
  { value: "64", label: "Improved Critical (shortbow)" },
  { value: "82", label: "Improved Critical (shuriken)" },
  { value: "60", label: "Improved Critical (sickle)" },
  { value: "61", label: "Improved Critical (sling)" },
  { value: "59", label: "Improved Critical (spear)" },
  { value: "71", label: "Improved Critical (throwing axe)" },
  { value: "1074", label: "Improved Critical (trident)" },
  { value: "89", label: "Improved Critical (two-bladed sword)" },
  { value: "62", label: "Improved Critical (unarmed strike)" },
  { value: "77", label: "Improved Critical (warhammer)" },
  { value: "995", label: "Improved Critical (whip)" },
  { value: "16", label: "Improved Disarm" },
  { value: "342", label: "Improved Elemental Shape" },
  { value: "212", label: "Improved Evasion" },
  { value: "390", label: "Improved Expertise" },
  { value: "377", label: "Improved Initiative" },
  { value: "471", label: "Improved Invisibility" },
  { value: "697", label: "Improved Ki Strike +4" },
  { value: "698", label: "Improved Ki Strike +5" },
  { value: "17", label: "Improved Knockdown" },
  { value: "18", label: "Improved Parry" },
  { value: "19", label: "Improved Power Attack" },
  { value: "834", label: "Improved Sneak Attack I" },
  { value: "835", label: "Improved Sneak Attack II" },
  { value: "836", label: "Improved Sneak Attack III" },
  { value: "837", label: "Improved Sneak Attack IV" },
  { value: "842", label: "Improved Sneak Attack IX" },
  { value: "838", label: "Improved Sneak Attack V" },
  { value: "839", label: "Improved Sneak Attack VI" },
  { value: "840", label: "Improved Sneak Attack VII" },
  { value: "841", label: "Improved Sneak Attack VIII" },
  { value: "843", label: "Improved Sneak Attack X" },
  { value: "699", label: "Improved Spell Resistance I" },
  { value: "700", label: "Improved Spell Resistance II" },
  { value: "701", label: "Improved Spell Resistance III" },
  { value: "702", label: "Improved Spell Resistance IV" },
  { value: "707", label: "Improved Spell Resistance IX" },
  { value: "703", label: "Improved Spell Resistance V" },
  { value: "704", label: "Improved Spell Resistance VI" },
  { value: "705", label: "Improved Spell Resistance VII" },
  { value: "706", label: "Improved Spell Resistance VIII" },
  { value: "708", label: "Improved Spell Resistance X" },
  { value: "844", label: "Improved Stunning Fist I" },
  { value: "845", label: "Improved Stunning Fist II" },
  { value: "846", label: "Improved Stunning Fist III" },
  { value: "847", label: "Improved Stunning Fist IV" },
  { value: "852", label: "Improved Stunning Fist IX" },
  { value: "848", label: "Improved Stunning Fist V" },
  { value: "849", label: "Improved Stunning Fist VI" },
  { value: "850", label: "Improved Stunning Fist VII" },
  { value: "851", label: "Improved Stunning Fist VIII" },
  { value: "853", label: "Improved Stunning Fist X" },
  { value: "20", label: "Improved Two-Weapon Fighting" },
  { value: "21", label: "Improved Unarmed Strike" },
  { value: "868", label: "Improved Whirlwind Attack" },
  { value: "883", label: "Increased Multiplier" },
  { value: "1091", label: "Individual Dismount" },
  { value: "1090", label: "Individual Mount" },
  { value: "1069", label: "Infinite Elemental Shape" },
  { value: "1062", label: "Infinite Greater Wildshape I" },
  { value: "1063", label: "Infinite Greater Wildshape II" },
  { value: "1064", label: "Infinite Greater Wildshape III" },
  { value: "1065", label: "Infinite Greater Wildshape IV" },
  { value: "1066", label: "Infinite Humanoid Shape" },
  { value: "1068", label: "Infinite Wildshape" },
  { value: "477", label: "Inflict Critical Wounds" },
  { value: "476", label: "Inflict Serious Wounds" },
  { value: "1086", label: "Inspire Courage" },
  { value: "1085", label: "Inspire Courage" },
  { value: "470", label: "Invisibility" },
  { value: "444", label: "Invisibility" },
  { value: "22", label: "Iron Will" },
  { value: "240", label: "Keen Sense" },
  { value: "885", label: "Ki Critical" },
  { value: "882", label: "Ki Damage" },
  { value: "213", label: "Ki Strike +1" },
  { value: "343", label: "Ki Strike +2" },
  { value: "344", label: "Ki Strike +3" },
  { value: "23", label: "Knockdown" },
  { value: "319", label: "Knowledge Domain Powers" },
  { value: "870", label: "Lasting Inspiration" },
  { value: "299", label: "Lay on Hands" },
  { value: "24", label: "Lightning Reflexes" },
  { value: "424", label: "Lingering Song" },
  { value: "439", label: "Lliira's Heart" },
  { value: "354", label: "Low-light Vision" },
  { value: "382", label: "Luck of Heroes" },
  { value: "248", label: "Lucky" },
  { value: "320", label: "Magic Domain Powers" },
  { value: "25", label: "Maximize Spell" },
  { value: "869", label: "Mighty Rage" },
  { value: "26", label: "Mobility" },
  { value: "260", label: "Monk AC Bonus" },
  { value: "207", label: "Monk Speed" },
  { value: "226", label: "Monster Uncanny Reflex" },
  { value: "1089", label: "Mount Actions" },
  { value: "1088", label: "Mounted Archery" },
  { value: "1087", label: "Mounted Combat" },
  { value: "198", label: "Nature Sense" },
  { value: "1083", label: "Oath of Wrath" },
  { value: "224", label: "Opportunist" },
  { value: "1060", label: "Outsider Shape" },
  { value: "742", label: "Overwhelming Critical (bastard sword)" },
  { value: "730", label: "Overwhelming Critical (battleaxe)" },
  { value: "709", label: "Overwhelming Critical (club)" },
  { value: "746", label: "Overwhelming Critical (creature weapon)" },
  { value: "710", label: "Overwhelming Critical (dagger)" },
  { value: "711", label: "Overwhelming Critical (dart)" },
  { value: "743", label: "Overwhelming Critical (dire mace)" },
  { value: "744", label: "Overwhelming Critical (double axe)" },
  { value: "958", label: "Overwhelming Critical (dwarven waraxe)" },
  { value: "731", label: "Overwhelming Critical (greataxe)" },
  { value: "727", label: "Overwhelming Critical (greatsword)" },
  { value: "732", label: "Overwhelming Critical (halberd)" },
  { value: "728", label: "Overwhelming Critical (handaxe)" },
  { value: "712", label: "Overwhelming Critical (heavy crossbow)" },
  { value: "736", label: "Overwhelming Critical (heavy flail)" },
  { value: "737", label: "Overwhelming Critical (kama)" },
  { value: "741", label: "Overwhelming Critical (katana)" },
  { value: "738", label: "Overwhelming Critical (kukri)" },
  { value: "713", label: "Overwhelming Critical (light crossbow)" },
  { value: "734", label: "Overwhelming Critical (light flail)" },
  { value: "733", label: "Overwhelming Critical (light hammer)" },
  { value: "721", label: "Overwhelming Critical (longbow)" },
  { value: "726", label: "Overwhelming Critical (longsword)" },
  { value: "714", label: "Overwhelming Critical (mace)" },
  { value: "715", label: "Overwhelming Critical (morningstar)" },
  { value: "716", label: "Overwhelming Critical (quarterstaff)" },
  { value: "724", label: "Overwhelming Critical (rapier)" },
  { value: "725", label: "Overwhelming Critical (scimitar)" },
  { value: "740", label: "Overwhelming Critical (scythe)" },
  { value: "722", label: "Overwhelming Critical (shortbow)" },
  { value: "723", label: "Overwhelming Critical (shortsword)" },
  { value: "739", label: "Overwhelming Critical (shuriken)" },
  { value: "718", label: "Overwhelming Critical (sickle)" },
  { value: "719", label: "Overwhelming Critical (sling)" },
  { value: "717", label: "Overwhelming Critical (spear)" },
  { value: "729", label: "Overwhelming Critical (throwing axe)" },
  { value: "1078", label: "Overwhelming Critical (trident)" },
  { value: "745", label: "Overwhelming Critical (two-bladed sword)" },
  { value: "720", label: "Overwhelming Critical (unarmed strike)" },
  { value: "735", label: "Overwhelming Critical (warhammer)" },
  { value: "999", label: "Overwhelming Critical (whip)" },
  { value: "244", label: "Partial Skill Affinity (Listen)" },
  { value: "245", label: "Partial Skill Affinity (Search)" },
  { value: "246", label: "Partial Skill Affinity (Spot)" },
  { value: "1093", label: "Party Dismount" },
  { value: "1092", label: "Party Mount" },
  { value: "747", label: "Perfect Health" },
  { value: "216", label: "Perfect Self" },
  { value: "854", label: "Planar Turning" },
  { value: "321", label: "Plant Domain Powers" },
  { value: "1106", label: "Player Tool 1" },
  { value: "1115", label: "Player Tool 10" },
  { value: "1107", label: "Player Tool 2" },
  { value: "1108", label: "Player Tool 3" },
  { value: "1109", label: "Player Tool 4" },
  { value: "1110", label: "Player Tool 5" },
  { value: "1111", label: "Player Tool 6" },
  { value: "1112", label: "Player Tool 7" },
  { value: "1113", label: "Player Tool 8" },
  { value: "1114", label: "Player Tool 9" },
  { value: "27", label: "Point Blank Shot" },
  { value: "463", label: "Poison Save I" },
  { value: "464", label: "Poison Save II" },
  { value: "465", label: "Poison Save III" },
  { value: "466", label: "Poison Save IV" },
  { value: "467", label: "Poison Save V" },
  { value: "1070", label: "Poison Save VI+" },
  { value: "28", label: "Power Attack" },
  { value: "308", label: "Protection Domain Powers" },
  { value: "209", label: "Purity of Body" },
  { value: "258", label: "Quick To Master" },
  { value: "29", label: "Quicken Spell" },
  { value: "296", label: "Quivering Palm" },
  { value: "1080", label: "Rallying Cry" },
  { value: "411", label: "Rapid Reload" },
  { value: "30", label: "Rapid Shot" },
  { value: "302", label: "Remove Disease" },
  { value: "428", label: "Resist Acid Energy" },
  { value: "427", label: "Resist Cold Energy" },
  { value: "426", label: "Resist Disease" },
  { value: "430", label: "Resist Electrical Energy" },
  { value: "429", label: "Resist Fire Energy" },
  { value: "202", label: "Resist Nature's Lure" },
  { value: "383", label: "Resist Poison" },
  { value: "431", label: "Resist Sonic Energy" },
  { value: "904", label: "Sacred Defense" },
  { value: "31", label: "Sap" },
  { value: "945", label: "Scribe Scroll" },
  { value: "451", label: "Seeker Arrow I" },
  { value: "452", label: "Seeker Arrow II" },
  { value: "748", label: "Self-Concealment I" },
  { value: "749", label: "Self-Concealment II" },
  { value: "750", label: "Self-Concealment III" },
  { value: "751", label: "Self-Concealment IV" },
  { value: "752", label: "Self-Concealment V" },
  { value: "434", label: "Shadow Daze" },
  { value: "436", label: "Shadow Evade" },
  { value: "32", label: "Shield Proficiency" },
  { value: "33", label: "Silent Spell" },
  { value: "384", label: "Silver Palm" },
  { value: "243", label: "Skill Affinity (Concentration)" },
  { value: "237", label: "Skill Affinity (Listen)" },
  { value: "234", label: "Skill Affinity (Lore)" },
  { value: "247", label: "Skill Affinity (Move Silently)" },
  { value: "238", label: "Skill Affinity (Search)" },
  { value: "239", label: "Skill Affinity (Spot)" },
  { value: "34", label: "Skill Focus (Animal Empathy)" },
  { value: "404", label: "Skill Focus (Appraise)" },
  { value: "915", label: "Skill Focus (Bluff)" },
  { value: "173", label: "Skill Focus (Concentration)" },
  { value: "911", label: "Skill Focus (Craft Armor)" },
  { value: "407", label: "Skill Focus (Craft Trap)" },
  { value: "912", label: "Skill Focus (Craft Weapon)" },
  { value: "174", label: "Skill Focus (Disable Trap)" },
  { value: "175", label: "Skill Focus (Discipline)" },
  { value: "177", label: "Skill Focus (Heal)" },
  { value: "178", label: "Skill Focus (Hide)" },
  { value: "916", label: "Skill Focus (Intimidate)" },
  { value: "179", label: "Skill Focus (Listen)" },
  { value: "180", label: "Skill Focus (Lore)" },
  { value: "181", label: "Skill Focus (Move Silently)" },
  { value: "182", label: "Skill Focus (Open Lock)" },
  { value: "183", label: "Skill Focus (Parry)" },
  { value: "184", label: "Skill Focus (Perform)" },
  { value: "185", label: "Skill Focus (Persuade)" },
  { value: "186", label: "Skill Focus (Pick Pocket)" },
  { value: "187", label: "Skill Focus (Search)" },
  { value: "188", label: "Skill Focus (Set Trap)" },
  { value: "189", label: "Skill Focus (Spellcraft)" },
  { value: "190", label: "Skill Focus (Spot)" },
  { value: "192", label: "Skill Focus (Taunt)" },
  { value: "406", label: "Skill Focus (Tumble)" },
  { value: "193", label: "Skill Focus (Use Magic Device)" },
  { value: "225", label: "Skill Mastery" },
  { value: "441", label: "Sleep" },
  { value: "259", label: "Slippery Mind" },
  { value: "375", label: "Small Stature" },
  { value: "301", label: "Smite Evil" },
  { value: "472", label: "Smite Good" },
  { value: "386", label: "Snake Blood" },
  { value: "353", label: "Sneak Attack (+10d6)" },
  { value: "1032", label: "Sneak Attack (+11d6)" },
  { value: "1033", label: "Sneak Attack (+12d6)" },
  { value: "1034", label: "Sneak Attack (+13d6)" },
  { value: "1035", label: "Sneak Attack (+14d6)" },
  { value: "1036", label: "Sneak Attack (+15d6)" },
  { value: "1037", label: "Sneak Attack (+16d6)" },
  { value: "1038", label: "Sneak Attack (+17d6)" },
  { value: "1039", label: "Sneak Attack (+18d6)" },
  { value: "1040", label: "Sneak Attack (+19d6)" },
  { value: "221", label: "Sneak Attack (+1d6)" },
  { value: "1041", label: "Sneak Attack (+20d6)" },
  { value: "345", label: "Sneak Attack (+2d6)" },
  { value: "346", label: "Sneak Attack (+3d6)" },
  { value: "347", label: "Sneak Attack (+4d6)" },
  { value: "348", label: "Sneak Attack (+5d6)" },
  { value: "349", label: "Sneak Attack (+6d6)" },
  { value: "350", label: "Sneak Attack (+7d6)" },
  { value: "351", label: "Sneak Attack (+8d6)" },
  { value: "352", label: "Sneak Attack (+9d6)" },
  { value: "1013", label: "Sneak Attack, Blackguard (+10d6)" },
  { value: "1014", label: "Sneak Attack, Blackguard (+11d6)" },
  { value: "1015", label: "Sneak Attack, Blackguard (+12d6)" },
  { value: "1016", label: "Sneak Attack, Blackguard (+13d6)" },
  { value: "1017", label: "Sneak Attack, Blackguard (+14d6)" },
  { value: "1018", label: "Sneak Attack, Blackguard (+15d6)" },
  { value: "460", label: "Sneak Attack, Blackguard (+1d6)" },
  { value: "461", label: "Sneak Attack, Blackguard (+2d6)" },
  { value: "462", label: "Sneak Attack, Blackguard (+3d6)" },
  { value: "1007", label: "Sneak Attack, Blackguard (+4d6)" },
  { value: "1008", label: "Sneak Attack, Blackguard (+5d6)" },
  { value: "1009", label: "Sneak Attack, Blackguard (+6d6)" },
  { value: "1010", label: "Sneak Attack, Blackguard (+7d6)" },
  { value: "1011", label: "Sneak Attack, Blackguard (+8d6)" },
  { value: "1012", label: "Sneak Attack, Blackguard (+9d6)" },
  { value: "35", label: "Spell Focus (Abjuration)" },
  { value: "166", label: "Spell Focus (Conjuration)" },
  { value: "167", label: "Spell Focus (Divination)" },
  { value: "168", label: "Spell Focus (Enchantment)" },
  { value: "169", label: "Spell Focus (Evocation)" },
  { value: "170", label: "Spell Focus (Illusion)" },
  { value: "171", label: "Spell Focus (Necromancy)" },
  { value: "172", label: "Spell Focus (Transmutation)" },
  { value: "36", label: "Spell Penetration" },
  { value: "392", label: "Spring Attack" },
  { value: "387", label: "Stealthy" },
  { value: "208", label: "Still Mind" },
  { value: "37", label: "Still Spell" },
  { value: "227", label: "Stonecunning" },
  { value: "307", label: "Strength Domain Powers" },
  { value: "388", label: "Strong Soul" },
  { value: "39", label: "Stunning Fist" },
  { value: "303", label: "Summon Familiar" },
  { value: "475", label: "Summon Fiend" },
  { value: "895", label: "Summon Greater Undead" },
  { value: "1095", label: "Summon Mount" },
  { value: "435", label: "Summon Shadow" },
  { value: "890", label: "Summon Undead" },
  { value: "322", label: "Sun Domain Powers" },
  { value: "753", label: "Superior Initiative" },
  { value: "884", label: "Superior Weapon Focus" },
  { value: "989", label: "Terrifying Rage" },
  { value: "402", label: "Thug" },
  { value: "988", label: "Thundering Rage" },
  { value: "894", label: "Tough as Bone" },
  { value: "40", label: "Toughness" },
  { value: "201", label: "Trackless Step" },
  { value: "323", label: "Travel Domain Powers" },
  { value: "324", label: "Trickery Domain Powers" },
  { value: "294", label: "Turn Undead" },
  { value: "41", label: "Two-Weapon Fighting" },
  { value: "438", label: "Tymora's Smile" },
  { value: "195", label: "Uncanny Dodge I" },
  { value: "251", label: "Uncanny Dodge II" },
  { value: "252", label: "Uncanny Dodge III" },
  { value: "253", label: "Uncanny Dodge IV" },
  { value: "254", label: "Uncanny Dodge V" },
  { value: "255", label: "Uncanny Dodge VI+" },
  { value: "892", label: "Undead Graft I" },
  { value: "893", label: "Undead Graft II" },
  { value: "872", label: "Undead Shape" },
  { value: "960", label: "Use Poison" },
  { value: "203", label: "Venom Immunity" },
  { value: "306", label: "War Domain Powers" },
  { value: "325", label: "Water Domain Powers" },
  { value: "42", label: "Weapon Finesse" },
  { value: "123", label: "Weapon Focus (bastard sword)" },
  { value: "110", label: "Weapon Focus (battleaxe)" },
  { value: "43", label: "Weapon Focus (club)" },
  { value: "291", label: "Weapon Focus (creature)" },
  { value: "90", label: "Weapon Focus (dagger)" },
  { value: "91", label: "Weapon Focus (dart)" },
  { value: "125", label: "Weapon Focus (dire mace)" },
  { value: "126", label: "Weapon Focus (double axe)" },
  { value: "952", label: "Weapon Focus (dwarven waraxe)" },
  { value: "111", label: "Weapon Focus (greataxe)" },
  { value: "107", label: "Weapon Focus (greatsword)" },
  { value: "112", label: "Weapon Focus (halberd)" },
  { value: "108", label: "Weapon Focus (handaxe)" },
  { value: "92", label: "Weapon Focus (heavy crossbow)" },
  { value: "116", label: "Weapon Focus (heavy flail)" },
  { value: "117", label: "Weapon Focus (kama)" },
  { value: "122", label: "Weapon Focus (katana)" },
  { value: "118", label: "Weapon Focus (kukri)" },
  { value: "93", label: "Weapon Focus (light crossbow)" },
  { value: "114", label: "Weapon Focus (light flail)" },
  { value: "113", label: "Weapon Focus (light hammer)" },
  { value: "101", label: "Weapon Focus (longbow)" },
  { value: "106", label: "Weapon Focus (longsword)" },
  { value: "94", label: "Weapon Focus (mace)" },
  { value: "95", label: "Weapon Focus (morningstar)" },
  { value: "96", label: "Weapon Focus (quarterstaff)" },
  { value: "104", label: "Weapon Focus (rapier)" },
  { value: "105", label: "Weapon Focus (scimitar)" },
  { value: "121", label: "Weapon Focus (scythe)" },
  { value: "103", label: "Weapon Focus (short sword)" },
  { value: "102", label: "Weapon Focus (shortbow)" },
  { value: "120", label: "Weapon Focus (shuriken)" },
  { value: "98", label: "Weapon Focus (sickle)" },
  { value: "99", label: "Weapon Focus (sling)" },
  { value: "97", label: "Weapon Focus (spear)" },
  { value: "109", label: "Weapon Focus (throwing axe)" },
  { value: "1072", label: "Weapon Focus (trident)" },
  { value: "127", label: "Weapon Focus (two-bladed sword)" },
  { value: "100", label: "Weapon Focus (unarmed strike)" },
  { value: "115", label: "Weapon Focus (warhammer)" },
  { value: "993", label: "Weapon Focus (whip)" },
  { value: "256", label: "Weapon Proficiency (Elf)" },
  { value: "289", label: "Weapon Proficiency (creature)" },
  { value: "48", label: "Weapon Proficiency (druid)" },
  { value: "44", label: "Weapon Proficiency (exotic)" },
  { value: "45", label: "Weapon Proficiency (martial)" },
  { value: "49", label: "Weapon Proficiency (monk)" },
  { value: "50", label: "Weapon Proficiency (rogue)" },
  { value: "46", label: "Weapon Proficiency (simple)" },
  { value: "51", label: "Weapon Proficiency (wizard)" },
  { value: "161", label: "Weapon Specialization (bastard sword)" },
  { value: "148", label: "Weapon Specialization (battleaxe)" },
  { value: "47", label: "Weapon Specialization (club)" },
  { value: "290", label: "Weapon Specialization (creature)" },
  { value: "128", label: "Weapon Specialization (dagger)" },
  { value: "129", label: "Weapon Specialization (dart)" },
  { value: "163", label: "Weapon Specialization (dire mace)" },
  { value: "164", label: "Weapon Specialization (double axe)" },
  { value: "953", label: "Weapon Specialization (dwarven waraxe)" },
  { value: "149", label: "Weapon Specialization (greataxe)" },
  { value: "145", label: "Weapon Specialization (greatsword)" },
  { value: "150", label: "Weapon Specialization (halberd)" },
  { value: "146", label: "Weapon Specialization (handaxe)" },
  { value: "130", label: "Weapon Specialization (heavy crossbow)" },
  { value: "154", label: "Weapon Specialization (heavy flail)" },
  { value: "155", label: "Weapon Specialization (kama)" },
  { value: "160", label: "Weapon Specialization (katana)" },
  { value: "156", label: "Weapon Specialization (kukri)" },
  { value: "131", label: "Weapon Specialization (light crossbow)" },
  { value: "152", label: "Weapon Specialization (light flail)" },
  { value: "151", label: "Weapon Specialization (light hammer)" },
  { value: "139", label: "Weapon Specialization (longbow)" },
  { value: "144", label: "Weapon Specialization (longsword)" },
  { value: "132", label: "Weapon Specialization (mace)" },
  { value: "133", label: "Weapon Specialization (morningstar)" },
  { value: "134", label: "Weapon Specialization (quarterstaff)" },
  { value: "142", label: "Weapon Specialization (rapier)" },
  { value: "143", label: "Weapon Specialization (scimitar)" },
  { value: "159", label: "Weapon Specialization (scythe)" },
  { value: "141", label: "Weapon Specialization (short sword)" },
  { value: "140", label: "Weapon Specialization (shortbow)" },
  { value: "158", label: "Weapon Specialization (shuriken)" },
  { value: "136", label: "Weapon Specialization (sickle)" },
  { value: "137", label: "Weapon Specialization (sling)" },
  { value: "135", label: "Weapon Specialization (spear)" },
  { value: "147", label: "Weapon Specialization (throwing axe)" },
  { value: "1073", label: "Weapon Specialization (trident)" },
  { value: "165", label: "Weapon Specialization (two-bladed sword)" },
  { value: "138", label: "Weapon Specialization (unarmed strike)" },
  { value: "153", label: "Weapon Specialization (warhammer)" },
  { value: "994", label: "Weapon Specialization (whip)" },
  { value: "940", label: "Weapon of Choice (bastard sword)" },
  { value: "931", label: "Weapon of Choice (battleaxe)" },
  { value: "919", label: "Weapon of Choice (club)" },
  { value: "920", label: "Weapon of Choice (dagger)" },
  { value: "941", label: "Weapon of Choice (dire mace)" },
  { value: "942", label: "Weapon of Choice (double axe)" },
  { value: "959", label: "Weapon of Choice (dwarven waraxe)" },
  { value: "932", label: "Weapon of Choice (greataxe)" },
  { value: "929", label: "Weapon of Choice (greatsword)" },
  { value: "933", label: "Weapon of Choice (halberd)" },
  { value: "930", label: "Weapon of Choice (handaxe)" },
  { value: "937", label: "Weapon of Choice (heavy flail)" },
  { value: "880", label: "Weapon of Choice (kama)" },
  { value: "939", label: "Weapon of Choice (katana)" },
  { value: "881", label: "Weapon of Choice (kukri)" },
  { value: "935", label: "Weapon of Choice (light flail)" },
  { value: "934", label: "Weapon of Choice (light hammer)" },
  { value: "928", label: "Weapon of Choice (longsword)" },
  { value: "921", label: "Weapon of Choice (mace)" },
  { value: "922", label: "Weapon of Choice (morningstar)" },
  { value: "923", label: "Weapon of Choice (quarterstaff)" },
  { value: "926", label: "Weapon of Choice (rapier)" },
  { value: "927", label: "Weapon of Choice (scimitar)" },
  { value: "938", label: "Weapon of Choice (scythe)" },
  { value: "925", label: "Weapon of Choice (short sword)" },
  { value: "879", label: "Weapon of Choice (sickle)" },
  { value: "924", label: "Weapon of Choice (spear)" },
  { value: "1079", label: "Weapon of Choice (trident)" },
  { value: "943", label: "Weapon of Choice (two-bladed sword)" },
  { value: "936", label: "Weapon of Choice (warhammer)" },
  { value: "1000", label: "Weapon of Choice (whip)" },
  { value: "867", label: "Whirlwind Attack" },
  { value: "211", label: "Wholeness of Body" },
  { value: "339", label: "Wild Shape" },
  { value: "305", label: "Wild Shape" },
  { value: "335", label: "Wild Shape (2x day)" },
  { value: "336", label: "Wild Shape (3x day)" },
  { value: "337", label: "Wild Shape (4x day)" },
  { value: "338", label: "Wild Shape (5x day)" },
  { value: "200", label: "Woodland Stride" },
  { value: "412", label: "Zen Archery" },
];
