export const ipType = [
  { value: "1", displayString: "Armor Bonus:", subType: "", valueType: "2", valueParamType: "", label: "AC Bonus" },
  {
    value: "2",
    displayString: "Armor Bonus vs.:",
    subType: "iprp_aligngrp",
    valueType: "2",
    valueParamType: "",
    label: "AC Bonus vs. Alignment Group",
  },
  {
    value: "3",
    displayString: "Armor Bonus vs.:",
    subType: "iprp_combatdam",
    valueType: "2",
    valueParamType: "",
    label: "AC Bonus vs. Damage Type",
  },
  {
    value: "4",
    displayString: "Armor Bonus vs.:",
    subType: "racialtypes",
    valueType: "2",
    valueParamType: "",
    label: "AC Bonus vs. Racial Group",
  },
  {
    value: "5",
    displayString: "Armor Bonus vs.:",
    subType: "iprp_alignment",
    valueType: "2",
    valueParamType: "",
    label: "AC Bonus vs. Specific Alignment",
  },
  {
    value: "0",
    displayString: "Enhancement Bonus:",
    subType: "iprp_abilities",
    valueType: "1",
    valueParamType: "",
    label: "Ability Bonus",
  },
  {
    value: "87",
    displayString: "Additional Property:",
    subType: "",
    valueType: "30",
    valueParamType: "",
    label: "Additional Property",
  },
  {
    value: "84",
    displayString: "Arcane Spell Failure:",
    subType: "",
    valueType: "27",
    valueParamType: "",
    label: "Arcane Spell Failure",
  },
  { value: "56", displayString: "Attack Bonus:", subType: "", valueType: "2", valueParamType: "", label: "Attack Bonus" },
  {
    value: "57",
    displayString: "Attack Bonus vs.:",
    subType: "iprp_aligngrp",
    valueType: "2",
    valueParamType: "",
    label: "Attack Bonus vs. Alignment Group",
  },
  {
    value: "58",
    displayString: "Attack Bonus vs.:",
    subType: "racialtypes",
    valueType: "2",
    valueParamType: "",
    label: "Attack Bonus vs. Racial Group",
  },
  {
    value: "59",
    displayString: "Attack Bonus vs.:",
    subType: "iprp_alignment",
    valueType: "2",
    valueParamType: "",
    label: "Attack Bonus vs. Specific Alignment",
  },
  {
    value: "10",
    displayString: "Enhancement Penalty:",
    subType: "",
    valueType: "20",
    valueParamType: "",
    label: "Attack and Damage Penalty",
  },
  {
    value: "11",
    displayString: "Weight Reduction:",
    subType: "",
    valueType: "10",
    valueParamType: "",
    label: "Base Item Weight Reduction",
  },
  { value: "12", displayString: "Bonus Feat:", subType: "iprp_feats", valueType: "", valueParamType: "", label: "Bonus Feat" },
  {
    value: "13",
    displayString: "Bonus Spell Slot:",
    subType: "classes",
    valueType: "13",
    valueParamType: "",
    label: "Bonus Spell Slot of Level",
  },
  { value: "14", displayString: "Boomerang", subType: "", valueType: "", valueParamType: "", label: "Boomerang" },
  { value: "15", displayString: "Use:", subType: "iprp_spells", valueType: "3", valueParamType: "", label: "Cast Spell" },
  {
    value: "16",
    displayString: "Damage Bonus:",
    subType: "iprp_damagetype",
    valueType: "4",
    valueParamType: "",
    label: "Damage Bonus",
  },
  {
    value: "17",
    displayString: "Damage Bonus vs.:",
    subType: "iprp_aligngrp",
    valueType: "4",
    valueParamType: "0",
    label: "Damage Bonus vs. Alignment Group",
  },
  {
    value: "18",
    displayString: "Damage Bonus vs.:",
    subType: "racialtypes",
    valueType: "4",
    valueParamType: "0",
    label: "Damage Bonus vs. Racial Type",
  },
  {
    value: "19",
    displayString: "Damage Bonus vs.:",
    subType: "iprp_alignment",
    valueType: "4",
    valueParamType: "0",
    label: "Damage Bonus vs. Specific Alignment",
  },
  {
    value: "22",
    displayString: "Damage Reduction:",
    subType: "iprp_protection",
    valueType: "6",
    valueParamType: "",
    label: "Damage Reduction",
  },
  {
    value: "23",
    displayString: "Damage Resistance:",
    subType: "iprp_damagetype",
    valueType: "7",
    valueParamType: "",
    label: "Damage Resistance",
  },
  {
    value: "24",
    displayString: "Damage Vulnerability:",
    subType: "iprp_damagetype",
    valueType: "22",
    valueParamType: "",
    label: "Damage Vulnerability",
  },
  { value: "25", displayString: "Dancing", subType: "", valueType: "8", valueParamType: "", label: "Dancing" },
  { value: "26", displayString: "Darkvision", subType: "", valueType: "", valueParamType: "", label: "Darkvision" },
  {
    value: "28",
    displayString: "Decreased AC:",
    subType: "iprp_acmodtype",
    valueType: "20",
    valueParamType: "",
    label: "Decreased AC",
  },
  {
    value: "27",
    displayString: "Ability Score Penalty:",
    subType: "iprp_abilities",
    valueType: "21",
    valueParamType: "",
    label: "Decreased Ability Score",
  },
  {
    value: "60",
    displayString: "Attack Penalty:",
    subType: "",
    valueType: "20",
    valueParamType: "",
    label: "Decreased Attack Modifier",
  },
  { value: "21", displayString: "Damage Penalty:", subType: "", valueType: "20", valueParamType: "", label: "Decreased Damage" },
  {
    value: "49",
    displayString: "Reduced Saving Throws:",
    subType: "iprp_saveelement",
    valueType: "20",
    valueParamType: "",
    label: "Decreased Saving Throws",
  },
  {
    value: "50",
    displayString: "Reduced Saving Throws:",
    subType: "iprp_savingthrow",
    valueType: "20",
    valueParamType: "",
    label: "Decreased Saving Throws: Specific",
  },
  {
    value: "29",
    displayString: "Decreased Skill Modifier:",
    subType: "skills",
    valueType: "21",
    valueParamType: "",
    label: "Decreased Skill Modifier",
  },
  { value: "30", displayString: "Double Stack:", subType: "", valueType: "", valueParamType: "", label: "Double Stack" },
  {
    value: "32",
    displayString: "Reduced Container Weight:",
    subType: "",
    valueType: "15",
    valueParamType: "",
    label: "Enhanced Container: Reduced Weight",
  },
  {
    value: "6",
    displayString: "Enhancement Bonus:",
    subType: "",
    valueType: "2",
    valueParamType: "",
    label: "Enhancement Bonus",
  },
  {
    value: "7",
    displayString: "Enhancement Bonus vs.:",
    subType: "iprp_aligngrp",
    valueType: "2",
    valueParamType: "",
    label: "Enhancement Bonus vs. Alignment Group",
  },
  {
    value: "8",
    displayString: "Enhancement Bonus vs.:",
    subType: "racialtypes",
    valueType: "2",
    valueParamType: "",
    label: "Enhancement Bonus vs. Racial Group",
  },
  {
    value: "9",
    displayString: "Enhancement Bonus vs.:",
    subType: "iprp_alignment",
    valueType: "2",
    valueParamType: "",
    label: "Enhancement Bonus vs. Specific Alignment",
  },
  {
    value: "33",
    displayString: "Extra Melee Damage:",
    subType: "iprp_combatdam",
    valueType: "",
    valueParamType: "",
    label: "Extra Melee Damage Type",
  },
  {
    value: "34",
    displayString: "Extra Ranged Damage:",
    subType: "iprp_combatdam",
    valueType: "",
    valueParamType: "",
    label: "Extra Ranged Damage Type",
  },
  { value: "75", displayString: "Freedom", subType: "", valueType: "", valueParamType: "", label: "Freedom of Movement" },
  { value: "35", displayString: "Haste", subType: "", valueType: "", valueParamType: "", label: "Haste" },
  { value: "80", displayString: "Healer's Kit", subType: "", valueType: "25", valueParamType: "", label: "Healer's Kit" },
  { value: "36", displayString: "Holy Avenger", subType: "", valueType: "", valueParamType: "", label: "Holy Avenger" },
  {
    value: "20",
    displayString: "Damage Immunity:",
    subType: "iprp_damagetype",
    valueType: "5",
    valueParamType: "",
    label: "Immunity: Damage Type",
  },
  {
    value: "37",
    displayString: "Immunity:",
    subType: "iprp_immunity",
    valueType: "",
    valueParamType: "",
    label: "Immunity: Miscellaneous",
  },
  {
    value: "53",
    displayString: "Spell Immunity:",
    subType: "",
    valueType: "16",
    valueParamType: "",
    label: "Immunity: Specific Spell",
  },
  {
    value: "54",
    displayString: "Spell School Immunity:",
    subType: "iprp_spellshl",
    valueType: "",
    valueParamType: "",
    label: "Immunity: Spell School",
  },
  {
    value: "78",
    displayString: "Immunity to Spell by Level:",
    subType: "",
    valueType: "23",
    valueParamType: "",
    label: "Immunity: Spells by Level",
  },
  { value: "38", displayString: "Improved Evasion", subType: "", valueType: "", valueParamType: "", label: "Improved Evasion" },
  { value: "43", displayString: "Keen", subType: "", valueType: "", valueParamType: "", label: "Keen" },
  { value: "44", displayString: "Light", subType: "", valueType: "18", valueParamType: "9", label: "Light" },
  {
    value: "74",
    displayString: "Massive Criticals:",
    subType: "",
    valueType: "4",
    valueParamType: "",
    label: "Massive Criticals",
  },
  { value: "85", displayString: "Material:", subType: "", valueType: "28", valueParamType: "", label: "Material" },
  { value: "45", displayString: "Mighty", subType: "", valueType: "2", valueParamType: "", label: "Mighty" },
  { value: "46", displayString: "Mind Blank", subType: "", valueType: "", valueParamType: "", label: "Mind Blank" },
  { value: "77", displayString: "Monster Damage:", subType: "", valueType: "19", valueParamType: "", label: "Monster Damage" },
  { value: "47", displayString: "No Damage", subType: "", valueType: "", valueParamType: "", label: "No Combat Damage" },
  { value: "48", displayString: "On Hit:", subType: "iprp_onhit", valueType: "24", valueParamType: "", label: "On Hit" },
  {
    value: "82",
    displayString: "On Hit:",
    subType: "iprp_onhitspell",
    valueType: "26",
    valueParamType: "",
    label: "On Hit Cast Spell",
  },
  {
    value: "72",
    displayString: "Monster Hit Ability:",
    subType: "iprp_monsterhit",
    valueType: "",
    valueParamType: "",
    label: "On Monster Hit",
  },
  { value: "76", displayString: "Poison:", subType: "poison", valueType: "", valueParamType: "10", label: "Poison" },
  { value: "86", displayString: "Quality:", subType: "", valueType: "29", valueParamType: "", label: "Quality" },
  { value: "51", displayString: "Regeneration:", subType: "", valueType: "2", valueParamType: "", label: "Regeneration" },
  {
    value: "67",
    displayString: "Vampiric Regeneration:",
    subType: "",
    valueType: "2",
    valueParamType: "",
    label: "Regeneration: Vampiric",
  },
  {
    value: "40",
    displayString: "Improved Saving Throws:",
    subType: "iprp_saveelement",
    valueType: "2",
    valueParamType: "",
    label: "Saving Throw Bonus",
  },
  {
    value: "41",
    displayString: "Improved Saving Throws:",
    subType: "iprp_savingthrow",
    valueType: "2",
    valueParamType: "",
    label: "Saving Throw Bonus: Specific",
  },
  { value: "52", displayString: "Skill Bonus:", subType: "skills", valueType: "25", valueParamType: "", label: "Skill Bonus" },
  { value: "79", displayString: "Special Walk", subType: "iprp_walk", valueType: "", valueParamType: "", label: "Special Walk" },
  {
    value: "39",
    displayString: "Spell Resistance:",
    subType: "",
    valueType: "11",
    valueParamType: "",
    label: "Spell Resistance",
  },
  { value: "55", displayString: "Thieves' Tools:", subType: "", valueType: "25", valueParamType: "", label: "Thieves' Tools" },
  { value: "70", displayString: "Trap Type:", subType: "iprp_traps", valueType: "17", valueParamType: "", label: "Trap" },
  { value: "71", displayString: "True Seeing", subType: "", valueType: "", valueParamType: "", label: "True Seeing" },
  { value: "73", displayString: "Turn Resistance:", subType: "", valueType: "25", valueParamType: "", label: "Turn Resistance" },
  {
    value: "61",
    displayString: "Unlimited Ammo:",
    subType: "iprp_ammotype",
    valueType: "14",
    valueParamType: "",
    label: "Unlimited Ammunition",
  },
  {
    value: "62",
    displayString: "Only Useable By:",
    subType: "iprp_aligngrp",
    valueType: "",
    valueParamType: "",
    label: "Use Limitation: Alignment Group",
  },
  {
    value: "63",
    displayString: "Only Useable By:",
    subType: "classes",
    valueType: "",
    valueParamType: "",
    label: "Use Limitation: Class",
  },
  {
    value: "64",
    displayString: "Only Useable By:",
    subType: "racialtypes",
    valueType: "",
    valueParamType: "",
    label: "Use Limitation: Racial Type",
  },
  {
    value: "65",
    displayString: "Only Useable By:",
    subType: "iprp_alignment",
    valueType: "",
    valueParamType: "",
    label: "Use Limitation: Specific Alignment",
  },
  { value: "83", displayString: "On Hit:", subType: "iprp_visualfx", valueType: "", valueParamType: "", label: "Visual Effect" },
  { value: "81", displayString: "Weight Increase", subType: "", valueType: "", valueParamType: "11", label: "Weight Increase" },
];
