export const ipValueParamType = [
  { value: "0", valueParamType: "0", label: "Bludgeoning" },
  { value: "1", valueParamType: "0", label: "Piercing" },
  { value: "2", valueParamType: "0", label: "Slashing" },
  { value: "5", valueParamType: "0", label: "Magical" },
  { value: "6", valueParamType: "0", label: "Acid" },
  { value: "7", valueParamType: "0", label: "Cold" },
  { value: "8", valueParamType: "0", label: "Divine" },
  { value: "9", valueParamType: "0", label: "Electrical" },
  { value: "10", valueParamType: "0", label: "Fire" },
  { value: "11", valueParamType: "0", label: "Negative Energy" },
  { value: "12", valueParamType: "0", label: "Positive Energy" },
  { value: "13", valueParamType: "0", label: "Sonic" },
  { value: "0", valueParamType: "1", label: "5% / 5 Rounds" },
  { value: "1", valueParamType: "1", label: "10% / 4 Rounds" },
  { value: "2", valueParamType: "1", label: "25% / 3 Rounds" },
  { value: "3", valueParamType: "1", label: "50% / 2 Rounds" },
  { value: "4", valueParamType: "1", label: "75% / 1 Round" },
  { value: "0", valueParamType: "2", label: "Strength" },
  { value: "1", valueParamType: "2", label: "Dexterity" },
  { value: "2", valueParamType: "2", label: "Constitution" },
  { value: "3", valueParamType: "2", label: "Intelligence" },
  { value: "4", valueParamType: "2", label: "Wisdom" },
  { value: "5", valueParamType: "2", label: "Charisma" },
  { value: "1", valueParamType: "3", label: "Neutral" },
  { value: "2", valueParamType: "3", label: "Lawful" },
  { value: "3", valueParamType: "3", label: "Chaotic" },
  { value: "4", valueParamType: "3", label: "Good" },
  { value: "5", valueParamType: "3", label: "Evil" },
  { value: "0", valueParamType: "4", label: "Lawful Good" },
  { value: "1", valueParamType: "4", label: "Lawful Neutral" },
  { value: "2", valueParamType: "4", label: "Lawful Evil" },
  { value: "3", valueParamType: "4", label: "Neutral Good" },
  { value: "4", valueParamType: "4", label: "True Neutral" },
  { value: "5", valueParamType: "4", label: "Neutral Evil" },
  { value: "6", valueParamType: "4", label: "Chaotic Good" },
  { value: "7", valueParamType: "4", label: "Chaotic Neutral" },
  { value: "8", valueParamType: "4", label: "Chaotic Evil" },
  { value: "0", valueParamType: "5", label: "Dwarf" },
  { value: "1", valueParamType: "5", label: "Elf" },
  { value: "2", valueParamType: "5", label: "Gnome" },
  { value: "3", valueParamType: "5", label: "Halfling" },
  { value: "4", valueParamType: "5", label: "Half-Elf" },
  { value: "5", valueParamType: "5", label: "Half-Orc" },
  { value: "6", valueParamType: "5", label: "Human" },
  { value: "7", valueParamType: "5", label: "Aberration" },
  { value: "8", valueParamType: "5", label: "Animal" },
  { value: "9", valueParamType: "5", label: "Beast" },
  { value: "10", valueParamType: "5", label: "Construct" },
  { value: "11", valueParamType: "5", label: "Dragon" },
  { value: "12", valueParamType: "5", label: "Goblinoid" },
  { value: "13", valueParamType: "5", label: "Monstrous" },
  { value: "14", valueParamType: "5", label: "Orc" },
  { value: "15", valueParamType: "5", label: "Reptilian" },
  { value: "16", valueParamType: "5", label: "Elemental" },
  { value: "17", valueParamType: "5", label: "Fey" },
  { value: "18", valueParamType: "5", label: "Giant" },
  { value: "19", valueParamType: "5", label: "Magical Beast" },
  { value: "20", valueParamType: "5", label: "Outsider" },
  { value: "23", valueParamType: "5", label: "Shapechanger" },
  { value: "24", valueParamType: "5", label: "Undead" },
  { value: "25", valueParamType: "5", label: "Vermin" },
  { value: "29", valueParamType: "5", label: "Ooze" },
  { value: "0", valueParamType: "6", label: "Blinding Sickness" },
  { value: "1", valueParamType: "6", label: "Cackle Fever" },
  { value: "2", valueParamType: "6", label: "Demon Fever" },
  { value: "3", valueParamType: "6", label: "Devil Chills" },
  { value: "4", valueParamType: "6", label: "Filth Fever" },
  { value: "5", valueParamType: "6", label: "Mindfire" },
  { value: "6", valueParamType: "6", label: "Mummy Rot" },
  { value: "7", valueParamType: "6", label: "Red Ache" },
  { value: "8", valueParamType: "6", label: "Shakes" },
  { value: "9", valueParamType: "6", label: "Slimy Doom" },
  { value: "10", valueParamType: "6", label: "Red Slaad Eggs" },
  { value: "11", valueParamType: "6", label: "Ghoul Rot" },
  { value: "12", valueParamType: "6", label: "Zombie Creep" },
  { value: "13", valueParamType: "6", label: "Dread Blisters" },
  { value: "14", valueParamType: "6", label: "Burrow Maggots" },
  { value: "15", valueParamType: "6", label: "Soldier Shakes" },
  { value: "16", valueParamType: "6", label: "Vermin Madness" },
  { value: "0", valueParamType: "7", label: "Amount: 1" },
  { value: "1", valueParamType: "7", label: "Amount: 2" },
  { value: "2", valueParamType: "7", label: "Amount: 3" },
  { value: "3", valueParamType: "7", label: "Amount: 4" },
  { value: "4", valueParamType: "7", label: "Amount: 5" },
  { value: "0", valueParamType: "8", label: "Nightshade" },
  { value: "1", valueParamType: "8", label: "Small Centipede Poison" },
  { value: "2", valueParamType: "8", label: "Blade Bane" },
  { value: "3", valueParamType: "8", label: "Greenblood Oil" },
  { value: "4", valueParamType: "8", label: "Bloodroot" },
  { value: "5", valueParamType: "8", label: "Purple Worm Poison" },
  { value: "6", valueParamType: "8", label: "Large Scorpion Venom" },
  { value: "7", valueParamType: "8", label: "Wyvern Poison" },
  { value: "8", valueParamType: "8", label: "Blue Whinnis" },
  { value: "9", valueParamType: "8", label: "Giant Wasp Poison" },
  { value: "10", valueParamType: "8", label: "Shadow Essence" },
  { value: "11", valueParamType: "8", label: "Black Adder Venom" },
  { value: "12", valueParamType: "8", label: "Deathblade" },
  { value: "13", valueParamType: "8", label: "Malyss Root Paste" },
  { value: "14", valueParamType: "8", label: "Nitharit" },
  { value: "15", valueParamType: "8", label: "Dragon Bile" },
  { value: "16", valueParamType: "8", label: "Sassone Leaf Residue" },
  { value: "17", valueParamType: "8", label: "Terinav Root" },
  { value: "18", valueParamType: "8", label: "Carrion Crawler Brain Juice" },
  { value: "19", valueParamType: "8", label: "Black Lotus Extract" },
  { value: "20", valueParamType: "8", label: "Oil of Taggit" },
  { value: "21", valueParamType: "8", label: "Id Moss" },
  { value: "22", valueParamType: "8", label: "Striped Toadstool" },
  { value: "23", valueParamType: "8", label: "Arsenic" },
  { value: "24", valueParamType: "8", label: "Lich Dust" },
  { value: "25", valueParamType: "8", label: "Dark Reaver Powder" },
  { value: "26", valueParamType: "8", label: "Ungol Dust" },
  { value: "27", valueParamType: "8", label: "Burnt Othur Fumes" },
  { value: "28", valueParamType: "8", label: "Chaos Mist" },
  { value: "29", valueParamType: "8", label: "Bebilith Venom" },
  { value: "30", valueParamType: "8", label: "Quasit Venom" },
  { value: "31", valueParamType: "8", label: "Pit Fiend Ichor" },
  { value: "32", valueParamType: "8", label: "Ettercap Venom" },
  { value: "33", valueParamType: "8", label: "Aranea Venom" },
  { value: "34", valueParamType: "8", label: "Tiny Spider Venom" },
  { value: "35", valueParamType: "8", label: "Small Spider Venom" },
  { value: "36", valueParamType: "8", label: "Medium Spider Venom" },
  { value: "37", valueParamType: "8", label: "Large Spider Venom" },
  { value: "38", valueParamType: "8", label: "Huge Spider Venom" },
  { value: "39", valueParamType: "8", label: "Gargantuan Spider Venom" },
  { value: "40", valueParamType: "8", label: "Colossal Spider Venom" },
  { value: "41", valueParamType: "8", label: "Phase Spider Venom" },
  { value: "42", valueParamType: "8", label: "Wraith Spider Venom" },
  { value: "43", valueParamType: "8", label: "Iron Golem Fumes" },
  { value: "44", valueParamType: "8", label: "Wyvern Poison" },
  { value: "0", valueParamType: "9", label: "Blue" },
  { value: "1", valueParamType: "9", label: "Yellow" },
  { value: "2", valueParamType: "9", label: "Purple" },
  { value: "3", valueParamType: "9", label: "Red" },
  { value: "4", valueParamType: "9", label: "Green" },
  { value: "5", valueParamType: "9", label: "Orange" },
  { value: "6", valueParamType: "9", label: "White" },
  { value: "0", valueParamType: "10", label: "1d2 Strength Damage" },
  { value: "1", valueParamType: "10", label: "1d2 Dexterity Damage" },
  { value: "2", valueParamType: "10", label: "1d2 Constitution Damage" },
  { value: "3", valueParamType: "10", label: "1d2 Intelligence Damage" },
  { value: "4", valueParamType: "10", label: "1d2 Wisdom Damage" },
  { value: "5", valueParamType: "10", label: "1d2 Charisma Damage" },
  { value: "0", valueParamType: "11", label: "5 lbs." },
  { value: "1", valueParamType: "11", label: "10 lbs." },
  { value: "2", valueParamType: "11", label: "15 lbs." },
  { value: "3", valueParamType: "11", label: "30 lbs." },
  { value: "4", valueParamType: "11", label: "50 lbs." },
  { value: "5", valueParamType: "11", label: "100 lbs." },
];
