export const ipValueType = [
  { value: "1", valueType: "1", label: "+1" },
  { value: "2", valueType: "1", label: "+2" },
  { value: "3", valueType: "1", label: "+3" },
  { value: "4", valueType: "1", label: "+4" },
  { value: "5", valueType: "1", label: "+5" },
  { value: "6", valueType: "1", label: "+6" },
  { value: "7", valueType: "1", label: "+7" },
  { value: "8", valueType: "1", label: "+8" },
  { value: "9", valueType: "1", label: "+9" },
  { value: "10", valueType: "1", label: "+10" },
  { value: "11", valueType: "1", label: "+11" },
  { value: "12", valueType: "1", label: "+12" },
  { value: "1", valueType: "2", label: "+1" },
  { value: "2", valueType: "2", label: "+2" },
  { value: "3", valueType: "2", label: "+3" },
  { value: "4", valueType: "2", label: "+4" },
  { value: "5", valueType: "2", label: "+5" },
  { value: "6", valueType: "2", label: "+6" },
  { value: "7", valueType: "2", label: "+7" },
  { value: "8", valueType: "2", label: "+8" },
  { value: "9", valueType: "2", label: "+9" },
  { value: "10", valueType: "2", label: "+10" },
  { value: "11", valueType: "2", label: "+11" },
  { value: "12", valueType: "2", label: "+12" },
  { value: "13", valueType: "2", label: "+13" },
  { value: "14", valueType: "2", label: "+14" },
  { value: "15", valueType: "2", label: "+15" },
  { value: "16", valueType: "2", label: "+16" },
  { value: "17", valueType: "2", label: "+17" },
  { value: "18", valueType: "2", label: "+18" },
  { value: "19", valueType: "2", label: "+19" },
  { value: "20", valueType: "2", label: "+20" },
  { value: "1", valueType: "3", label: "Single Use" },
  { value: "2", valueType: "3", label: "5 Charges/Use" },
  { value: "3", valueType: "3", label: "4 Charges/Use" },
  { value: "4", valueType: "3", label: "3 Charges/Use" },
  { value: "5", valueType: "3", label: "2 Charges/Use" },
  { value: "6", valueType: "3", label: "1 Charge/Use" },
  { value: "7", valueType: "3", label: "0 Charges/Use" },
  { value: "8", valueType: "3", label: "1 Use/Day" },
  { value: "9", valueType: "3", label: "2 Uses/Day" },
  { value: "10", valueType: "3", label: "3 Uses/Day" },
  { value: "11", valueType: "3", label: "4 Uses/Day" },
  { value: "12", valueType: "3", label: "5 Uses/Day" },
  { value: "13", valueType: "3", label: "Unlimited Uses/Day" },
  { value: "1", valueType: "4", label: "1 Damage" },
  { value: "2", valueType: "4", label: "2 Damage" },
  { value: "3", valueType: "4", label: "3 Damage" },
  { value: "4", valueType: "4", label: "4 Damage" },
  { value: "5", valueType: "4", label: "5 Damage" },
  { value: "6", valueType: "4", label: "1d4 Damage" },
  { value: "7", valueType: "4", label: "1d6 Damage" },
  { value: "8", valueType: "4", label: "1d8 Damage" },
  { value: "9", valueType: "4", label: "1d10 Damage" },
  { value: "10", valueType: "4", label: "2d6 Damage" },
  { value: "11", valueType: "4", label: "2d8 Damage" },
  { value: "12", valueType: "4", label: "2d4 Damage" },
  { value: "13", valueType: "4", label: "2d10 Damage" },
  { value: "14", valueType: "4", label: "1d12 Damage" },
  { value: "15", valueType: "4", label: "2d12 Damage" },
  { value: "16", valueType: "4", label: "6 Damage" },
  { value: "17", valueType: "4", label: "7 Damage" },
  { value: "18", valueType: "4", label: "8 Damage" },
  { value: "19", valueType: "4", label: "9 Damage" },
  { value: "20", valueType: "4", label: "10 Damage" },
  { value: "21", valueType: "4", label: "11 Damage" },
  { value: "22", valueType: "4", label: "12 Damage" },
  { value: "23", valueType: "4", label: "13 Damage" },
  { value: "24", valueType: "4", label: "14 Damage" },
  { value: "25", valueType: "4", label: "15 Damage" },
  { value: "26", valueType: "4", label: "16 Damage" },
  { value: "27", valueType: "4", label: "17 Damage" },
  { value: "28", valueType: "4", label: "18 Damage" },
  { value: "29", valueType: "4", label: "19 Damage" },
  { value: "30", valueType: "4", label: "20 Damage" },
  { value: "1", valueType: "5", label: "5% Immunity Bonus" },
  { value: "2", valueType: "5", label: "10% Immunity Bonus" },
  { value: "3", valueType: "5", label: "25% Immunity Bonus" },
  { value: "4", valueType: "5", label: "50% Immunity Bonus" },
  { value: "5", valueType: "5", label: "75% Immunity Bonus" },
  { value: "6", valueType: "5", label: "90% Immunity Bonus" },
  { value: "7", valueType: "5", label: "100% Immunity Bonus" },
  { value: "1", valueType: "6", label: "Soak 5 Damage" },
  { value: "2", valueType: "6", label: "Soak 10 Damage" },
  { value: "3", valueType: "6", label: "Soak 15 Damage" },
  { value: "4", valueType: "6", label: "Soak 20 Damage" },
  { value: "5", valueType: "6", label: "Soak 25 Damage" },
  { value: "6", valueType: "6", label: "Soak 30 Damage" },
  { value: "7", valueType: "6", label: "Soak 35 damage" },
  { value: "8", valueType: "6", label: "Soak 40 damage" },
  { value: "9", valueType: "6", label: "Soak 45 damage" },
  { value: "10", valueType: "6", label: "Soak 50 damage" },
  { value: "1", valueType: "7", label: "Resist 5 / -" },
  { value: "2", valueType: "7", label: "Resist 10 / -" },
  { value: "3", valueType: "7", label: "Resist 15 / -" },
  { value: "4", valueType: "7", label: "Resist 20 / -" },
  { value: "5", valueType: "7", label: "Resist 25 / -" },
  { value: "6", valueType: "7", label: "Resist 30 / -" },
  { value: "7", valueType: "7", label: "Resist 35 / -" },
  { value: "8", valueType: "7", label: "Resist 40 / -" },
  { value: "9", valueType: "7", label: "Resist 45 / -" },
  { value: "10", valueType: "7", label: "Resist 50 / -" },
  { value: "1", valueType: "8", label: "Dancing Blade +1" },
  { value: "2", valueType: "8", label: "Dancing Blade +2" },
  { value: "3", valueType: "8", label: "Dancing Blade +3" },
  { value: "4", valueType: "8", label: "Dancing Blade +4" },
  { value: "5", valueType: "8", label: "Dancing Blade +5" },
  { value: "1", valueType: "10", label: "80% of Weight" },
  { value: "2", valueType: "10", label: "60% of Weight" },
  { value: "3", valueType: "10", label: "40% of Weight" },
  { value: "4", valueType: "10", label: "20% of Weight" },
  { value: "5", valueType: "10", label: "10% of Weight" },
  { value: "0", valueType: "11", label: "10" },
  { value: "1", valueType: "11", label: "12" },
  { value: "2", valueType: "11", label: "14" },
  { value: "3", valueType: "11", label: "16" },
  { value: "4", valueType: "11", label: "18" },
  { value: "5", valueType: "11", label: "20" },
  { value: "6", valueType: "11", label: "22" },
  { value: "7", valueType: "11", label: "24" },
  { value: "8", valueType: "11", label: "26" },
  { value: "9", valueType: "11", label: "28" },
  { value: "10", valueType: "11", label: "30" },
  { value: "11", valueType: "11", label: "32" },
  { value: "0", valueType: "13", label: "Level 0" },
  { value: "1", valueType: "13", label: "Level 1" },
  { value: "2", valueType: "13", label: "Level 2" },
  { value: "3", valueType: "13", label: "Level 3" },
  { value: "4", valueType: "13", label: "Level 4" },
  { value: "5", valueType: "13", label: "Level 5" },
  { value: "6", valueType: "13", label: "Level 6" },
  { value: "7", valueType: "13", label: "Level 7" },
  { value: "8", valueType: "13", label: "Level 8" },
  { value: "9", valueType: "13", label: "Level 9" },
  { value: "1", valueType: "14", label: "Ammo: Basic" },
  { value: "2", valueType: "14", label: "Ammo: +1d6 Fire" },
  { value: "3", valueType: "14", label: "Ammo: +1d6 Cold" },
  { value: "4", valueType: "14", label: "Ammo: +1d6 Lightning" },
  { value: "11", valueType: "14", label: "Ammo: +1 Enhancement to Damage" },
  { value: "12", valueType: "14", label: "Ammo: +2 Enhancement to Damage" },
  { value: "13", valueType: "14", label: "Ammo: +3 Enhancement to Damage" },
  { value: "14", valueType: "14", label: "Ammo: +4 Enhancement to Damage" },
  { value: "15", valueType: "14", label: "Ammo: +5 Enhancement to Damage" },
  { value: "1", valueType: "15", label: "Content weight: -20%" },
  { value: "2", valueType: "15", label: "Content Weight: -40%" },
  { value: "3", valueType: "15", label: "Content Weight: -60%" },
  { value: "4", valueType: "15", label: "Content Weight: -80%" },
  { value: "5", valueType: "15", label: "Content Weight: -100%" },
  { value: "0", valueType: "16", label: "Acid Fog" },
  { value: "1", valueType: "16", label: "Aid" },
  { value: "2", valueType: "16", label: "Barkskin" },
  { value: "3", valueType: "16", label: "Bestow Curse" },
  { value: "6", valueType: "16", label: "Blindness/Deafness" },
  { value: "8", valueType: "16", label: "Burning Hands" },
  { value: "9", valueType: "16", label: "Call Lightning" },
  { value: "12", valueType: "16", label: "Chain Lightning" },
  { value: "13", valueType: "16", label: "Charm Monster" },
  { value: "14", valueType: "16", label: "Charm Person" },
  { value: "15", valueType: "16", label: "Charm Person or Animal" },
  { value: "16", valueType: "16", label: "Circle of Death" },
  { value: "17", valueType: "16", label: "Circle of Doom" },
  { value: "21", valueType: "16", label: "Cloudkill" },
  { value: "22", valueType: "16", label: "Color Spray" },
  { value: "23", valueType: "16", label: "Cone of Cold" },
  { value: "24", valueType: "16", label: "Confusion" },
  { value: "25", valueType: "16", label: "Contagion" },
  { value: "26", valueType: "16", label: "Control Undead" },
  { value: "27", valueType: "16", label: "Cure Critical Wounds" },
  { value: "28", valueType: "16", label: "Cure Light Wounds" },
  { value: "29", valueType: "16", label: "Cure Minor Wounds" },
  { value: "30", valueType: "16", label: "Cure Moderate Wounds" },
  { value: "31", valueType: "16", label: "Cure Serious Wounds" },
  { value: "32", valueType: "16", label: "Darkness" },
  { value: "33", valueType: "16", label: "Daze" },
  { value: "34", valueType: "16", label: "Death Ward" },
  { value: "35", valueType: "16", label: "Delayed Blast Fireball" },
  { value: "36", valueType: "16", label: "Dismissal" },
  { value: "37", valueType: "16", label: "Dispel Magic" },
  { value: "39", valueType: "16", label: "Dominate Animal" },
  { value: "40", valueType: "16", label: "Dominate Monster" },
  { value: "41", valueType: "16", label: "Dominate Person" },
  { value: "42", valueType: "16", label: "Doom" },
  { value: "46", valueType: "16", label: "Energy Drain" },
  { value: "47", valueType: "16", label: "Enervation" },
  { value: "48", valueType: "16", label: "Entangle" },
  { value: "49", valueType: "16", label: "Fear" },
  { value: "50", valueType: "16", label: "Feeblemind" },
  { value: "51", valueType: "16", label: "Finger of Death" },
  { value: "52", valueType: "16", label: "Fire Storm" },
  { value: "53", valueType: "16", label: "Fireball" },
  { value: "54", valueType: "16", label: "Flame Arrow" },
  { value: "55", valueType: "16", label: "Flame Lash" },
  { value: "56", valueType: "16", label: "Flame Strike" },
  { value: "57", valueType: "16", label: "Freedom of Movement" },
  { value: "59", valueType: "16", label: "Grease" },
  { value: "60", valueType: "16", label: "Greater Dispelling" },
  { value: "62", valueType: "16", label: "Greater Planar Binding" },
  { value: "64", valueType: "16", label: "Greater Shadow Conjuration" },
  { value: "65", valueType: "16", label: "Greater Spell Breach" },
  { value: "68", valueType: "16", label: "Hammer of the Gods" },
  { value: "69", valueType: "16", label: "Harm" },
  { value: "71", valueType: "16", label: "Heal" },
  { value: "72", valueType: "16", label: "Healing Circle" },
  { value: "73", valueType: "16", label: "Hold Animal" },
  { value: "74", valueType: "16", label: "Hold Monster" },
  { value: "75", valueType: "16", label: "Hold Person" },
  { value: "78", valueType: "16", label: "Implosion" },
  { value: "79", valueType: "16", label: "Improved Invisibility" },
  { value: "80", valueType: "16", label: "Incendiary Cloud" },
  { value: "82", valueType: "16", label: "Invisibility Purge" },
  { value: "84", valueType: "16", label: "Lesser Dispel" },
  { value: "86", valueType: "16", label: "Lesser Planar Binding" },
  { value: "88", valueType: "16", label: "Lesser Spell Breach" },
  { value: "91", valueType: "16", label: "Lightning Bolt" },
  { value: "97", valueType: "16", label: "Magic Missile" },
  { value: "100", valueType: "16", label: "Mass Blindness/Deafness" },
  { value: "101", valueType: "16", label: "Mass Charm" },
  { value: "104", valueType: "16", label: "Mass Heal" },
  { value: "105", valueType: "16", label: "Melf's Acid Arrow" },
  { value: "106", valueType: "16", label: "Meteor Swarm" },
  { value: "108", valueType: "16", label: "Mind Fog" },
  { value: "112", valueType: "16", label: "Mordenkainen's Disjunction" },
  { value: "116", valueType: "16", label: "Phantasmal Killer" },
  { value: "117", valueType: "16", label: "Planar Binding" },
  { value: "118", valueType: "16", label: "Poison" },
  { value: "120", valueType: "16", label: "Power Word, Kill" },
  { value: "121", valueType: "16", label: "Power Word, Stun" },
  { value: "124", valueType: "16", label: "Prismatic Spray" },
  { value: "131", valueType: "16", label: "Ray of Enfeeblement" },
  { value: "132", valueType: "16", label: "Ray of Frost" },
  { value: "142", valueType: "16", label: "Scare" },
  { value: "143", valueType: "16", label: "Searing Light" },
  { value: "145", valueType: "16", label: "Shades" },
  { value: "146", valueType: "16", label: "Shadow Conjuration" },
  { value: "150", valueType: "16", label: "Silence" },
  { value: "151", valueType: "16", label: "Slay Living" },
  { value: "152", valueType: "16", label: "Sleep" },
  { value: "153", valueType: "16", label: "Slow" },
  { value: "154", valueType: "16", label: "Sound Burst" },
  { value: "158", valueType: "16", label: "Stinking Cloud" },
  { value: "159", valueType: "16", label: "Stoneskin" },
  { value: "160", valueType: "16", label: "Storm of Vengeance" },
  { value: "161", valueType: "16", label: "Sunbeam" },
  { value: "165", valueType: "16", label: "Virtue" },
  { value: "166", valueType: "16", label: "Wail of the Banshee" },
  { value: "167", valueType: "16", label: "Web" },
  { value: "168", valueType: "16", label: "Weird" },
  { value: "169", valueType: "16", label: "Word of Faith" },
  { value: "171", valueType: "16", label: "Magic Circle against Alignment (5)" },
  { value: "173", valueType: "16", label: "Eagle's Splendor" },
  { value: "174", valueType: "16", label: "Owl's Wisdom" },
  { value: "175", valueType: "16", label: "Fox's Cunning" },
  { value: "176", valueType: "16", label: "Greater Eagle's Splendor" },
  { value: "177", valueType: "16", label: "Greater Owl's Wisdom" },
  { value: "178", valueType: "16", label: "Greater Fox's Cunning" },
  { value: "179", valueType: "16", label: "Greater Bull's Strength" },
  { value: "180", valueType: "16", label: "Greater Cat's Grace" },
  { value: "181", valueType: "16", label: "Greater Endurance" },
  { value: "182", valueType: "16", label: "Aura of Vitality (13)" },
  { value: "183", valueType: "16", label: "War Cry (7)" },
  { value: "184", valueType: "16", label: "Regenerate (13)" },
  { value: "185", valueType: "16", label: "Evard's Black Tentacles (7)" },
  { value: "186", valueType: "16", label: "Legend Lore (5)" },
  { value: "187", valueType: "16", label: "Find Traps (3)" },
  { value: "188", valueType: "16", label: "Divine Favor" },
  { value: "189", valueType: "16", label: "True Strike" },
  { value: "190", valueType: "16", label: "Flare" },
  { value: "191", valueType: "16", label: "Shield" },
  { value: "192", valueType: "16", label: "Acid Splash" },
  { value: "193", valueType: "16", label: "Quillfire" },
  { value: "194", valueType: "16", label: "Sunburst" },
  { value: "195", valueType: "16", label: "Banishment" },
  { value: "196", valueType: "16", label: "Inflict Minor Wounds" },
  { value: "197", valueType: "16", label: "Inflict Light Wounds" },
  { value: "198", valueType: "16", label: "Inflict Moderate Wounds" },
  { value: "199", valueType: "16", label: "Inflict Serious Wounds" },
  { value: "200", valueType: "16", label: "Inflict Critical Wounds" },
  { value: "201", valueType: "16", label: "Drown" },
  { value: "202", valueType: "16", label: "Electric Jolt" },
  { value: "203", valueType: "16", label: "Firebrand" },
  { value: "204", valueType: "16", label: "Dirge" },
  { value: "205", valueType: "16", label: "Inferno" },
  { value: "206", valueType: "16", label: "Isaac's Lesser Missile Storm" },
  { value: "207", valueType: "16", label: "Isaac's Greater Missile Storm" },
  { value: "208", valueType: "16", label: "Bane" },
  { value: "209", valueType: "16", label: "Spike Growth" },
  { value: "210", valueType: "16", label: "Tasha's Hideous Laughter" },
  { value: "211", valueType: "16", label: "Bigby's Forceful Hand" },
  { value: "212", valueType: "16", label: "Bigby's Grasping Hand" },
  { value: "213", valueType: "16", label: "Bigby's Clenched Fist" },
  { value: "214", valueType: "16", label: "Bigby's Crushing Hand" },
  { value: "215", valueType: "16", label: "Sleep" },
  { value: "216", valueType: "16", label: "Flesh to Stone" },
  { value: "217", valueType: "16", label: "Stone to Flesh" },
  { value: "218", valueType: "16", label: "Breath, Petrification" },
  { value: "219", valueType: "16", label: "Touch, Petrification" },
  { value: "220", valueType: "16", label: "Gaze, Petrification" },
  { value: "221", valueType: "16", label: "Crumble" },
  { value: "222", valueType: "16", label: "Infestation of Maggots" },
  { value: "223", valueType: "16", label: "Healing Sting" },
  { value: "224", valueType: "16", label: "Great Thunderclap" },
  { value: "225", valueType: "16", label: "Ball Lightning" },
  { value: "226", valueType: "16", label: "Battletide" },
  { value: "227", valueType: "16", label: "Combust" },
  { value: "228", valueType: "16", label: "Gedlee's Electric Loop" },
  { value: "229", valueType: "16", label: "Horizikaul's Boom" },
  { value: "230", valueType: "16", label: "Mestil's Acid Breath" },
  { value: "231", valueType: "16", label: "Scintillating Sphere" },
  { value: "232", valueType: "16", label: "Undeath to Death" },
  { value: "233", valueType: "16", label: "Vine Mine" },
  { value: "234", valueType: "16", label: "Ice Dagger" },
  { value: "235", valueType: "16", label: "Stonehold" },
  { value: "236", valueType: "16", label: "Glyph of Warding" },
  { value: "237", valueType: "16", label: "Cloud of Bewilderment" },
  { value: "238", valueType: "16", label: "Captivating Song" },
  { value: "239", valueType: "16", label: "Psionic Mind Blast 10m Radius" },
  { value: "240", valueType: "16", label: "Bigby's Interposing Hand" },
  { value: "1", valueType: "17", label: "Spike" },
  { value: "2", valueType: "17", label: "Holy" },
  { value: "3", valueType: "17", label: "Tangle" },
  { value: "4", valueType: "17", label: "Blob of Acid" },
  { value: "5", valueType: "17", label: "Fire" },
  { value: "6", valueType: "17", label: "Electrical" },
  { value: "7", valueType: "17", label: "Gas" },
  { value: "8", valueType: "17", label: "Frost" },
  { value: "9", valueType: "17", label: "Acid Splash" },
  { value: "10", valueType: "17", label: "Sonic" },
  { value: "11", valueType: "17", label: "Negative" },
  { value: "1", valueType: "18", label: "Dim (5m)" },
  { value: "2", valueType: "18", label: "Low (10m)" },
  { value: "3", valueType: "18", label: "Normal (15m)" },
  { value: "4", valueType: "18", label: "Bright (20m)" },
  { value: "1", valueType: "19", label: "1d2 Damage" },
  { value: "2", valueType: "19", label: "1d3 Damage" },
  { value: "3", valueType: "19", label: "1d4 Damage" },
  { value: "4", valueType: "19", label: "2d4 Damage" },
  { value: "5", valueType: "19", label: "3d4 Damage" },
  { value: "6", valueType: "19", label: "4d4 Damage" },
  { value: "7", valueType: "19", label: "5d4 Damage" },
  { value: "8", valueType: "19", label: "1d6 Damage" },
  { value: "9", valueType: "19", label: "2d6 Damage" },
  { value: "10", valueType: "19", label: "3d6 Damage" },
  { value: "11", valueType: "19", label: "4d6 Damage" },
  { value: "12", valueType: "19", label: "5d6 Damage" },
  { value: "13", valueType: "19", label: "6d6 Damage" },
  { value: "14", valueType: "19", label: "7d6 Damage" },
  { value: "15", valueType: "19", label: "8d6 Damage" },
  { value: "16", valueType: "19", label: "9d6 Damage" },
  { value: "17", valueType: "19", label: "10d6 Damage" },
  { value: "18", valueType: "19", label: "1d8 Damage" },
  { value: "19", valueType: "19", label: "2d8 Damage" },
  { value: "20", valueType: "19", label: "3d8 Damage" },
  { value: "21", valueType: "19", label: "4d8 Damage" },
  { value: "22", valueType: "19", label: "5d8 Damage" },
  { value: "23", valueType: "19", label: "6d8 Damage" },
  { value: "24", valueType: "19", label: "7d8 Damage" },
  { value: "25", valueType: "19", label: "8d8 Damage" },
  { value: "26", valueType: "19", label: "9d8 Damage" },
  { value: "27", valueType: "19", label: "10d8 Damage" },
  { value: "28", valueType: "19", label: "1d10 Damage" },
  { value: "29", valueType: "19", label: "2d10 Damage" },
  { value: "30", valueType: "19", label: "3d10 Damage" },
  { value: "31", valueType: "19", label: "4d10 Damage" },
  { value: "32", valueType: "19", label: "5d10 Damage" },
  { value: "33", valueType: "19", label: "6d10 Damage" },
  { value: "34", valueType: "19", label: "7d10 Damage" },
  { value: "35", valueType: "19", label: "8d10 Damage" },
  { value: "36", valueType: "19", label: "9d10 Damage" },
  { value: "37", valueType: "19", label: "10d10 Damage" },
  { value: "38", valueType: "19", label: "1d12 Damage" },
  { value: "39", valueType: "19", label: "2d12 Damage" },
  { value: "40", valueType: "19", label: "3d12 Damage" },
  { value: "41", valueType: "19", label: "4d12 Damage" },
  { value: "42", valueType: "19", label: "5d12 Damage" },
  { value: "43", valueType: "19", label: "6d12 Damage" },
  { value: "44", valueType: "19", label: "7d12 Damage" },
  { value: "45", valueType: "19", label: "8d12 Damage" },
  { value: "46", valueType: "19", label: "9d12 Damage" },
  { value: "47", valueType: "19", label: "10d12 Damage" },
  { value: "48", valueType: "19", label: "1d20 Damage" },
  { value: "49", valueType: "19", label: "2d20 Damage" },
  { value: "50", valueType: "19", label: "3d20 Damage" },
  { value: "51", valueType: "19", label: "4d20 Damage" },
  { value: "52", valueType: "19", label: "5d20 Damage" },
  { value: "53", valueType: "19", label: "6d20 Damage" },
  { value: "54", valueType: "19", label: "7d20 Damage" },
  { value: "55", valueType: "19", label: "8d20 Damage" },
  { value: "56", valueType: "19", label: "9d20 Damage" },
  { value: "57", valueType: "19", label: "10d20 Damage" },
  { value: "1", valueType: "20", label: "-1" },
  { value: "2", valueType: "20", label: "-2" },
  { value: "3", valueType: "20", label: "-3" },
  { value: "4", valueType: "20", label: "-4" },
  { value: "5", valueType: "20", label: "-5" },
  { value: "1", valueType: "21", label: "-1" },
  { value: "2", valueType: "21", label: "-2" },
  { value: "3", valueType: "21", label: "-3" },
  { value: "4", valueType: "21", label: "-4" },
  { value: "5", valueType: "21", label: "-5" },
  { value: "6", valueType: "21", label: "-6" },
  { value: "7", valueType: "21", label: "-7" },
  { value: "8", valueType: "21", label: "-8" },
  { value: "9", valueType: "21", label: "-9" },
  { value: "10", valueType: "21", label: "-10" },
  { value: "11", valueType: "21", label: "-11" },
  { value: "12", valueType: "21", label: "-12" },
  { value: "13", valueType: "21", label: "-13" },
  { value: "14", valueType: "21", label: "-14" },
  { value: "15", valueType: "21", label: "-15" },
  { value: "16", valueType: "21", label: "-16" },
  { value: "17", valueType: "21", label: "-17" },
  { value: "18", valueType: "21", label: "-18" },
  { value: "19", valueType: "21", label: "-19" },
  { value: "20", valueType: "21", label: "-20" },
  { value: "21", valueType: "21", label: "-21" },
  { value: "22", valueType: "21", label: "-22" },
  { value: "23", valueType: "21", label: "-23" },
  { value: "24", valueType: "21", label: "-24" },
  { value: "25", valueType: "21", label: "-25" },
  { value: "26", valueType: "21", label: "-26" },
  { value: "27", valueType: "21", label: "-27" },
  { value: "28", valueType: "21", label: "-28" },
  { value: "29", valueType: "21", label: "-29" },
  { value: "30", valueType: "21", label: "-30" },
  { value: "31", valueType: "21", label: "-31" },
  { value: "32", valueType: "21", label: "-32" },
  { value: "33", valueType: "21", label: "-33" },
  { value: "34", valueType: "21", label: "-34" },
  { value: "35", valueType: "21", label: "-35" },
  { value: "36", valueType: "21", label: "-36" },
  { value: "37", valueType: "21", label: "-37" },
  { value: "38", valueType: "21", label: "-38" },
  { value: "39", valueType: "21", label: "-39" },
  { value: "40", valueType: "21", label: "-40" },
  { value: "41", valueType: "21", label: "-41" },
  { value: "42", valueType: "21", label: "-42" },
  { value: "43", valueType: "21", label: "-43" },
  { value: "44", valueType: "21", label: "-44" },
  { value: "45", valueType: "21", label: "-45" },
  { value: "46", valueType: "21", label: "-46" },
  { value: "47", valueType: "21", label: "-47" },
  { value: "48", valueType: "21", label: "-48" },
  { value: "49", valueType: "21", label: "-49" },
  { value: "50", valueType: "21", label: "-50" },
  { value: "1", valueType: "22", label: "5% Damage Vulnerability" },
  { value: "2", valueType: "22", label: "10% Damage Vulnerability" },
  { value: "3", valueType: "22", label: "25% Damage Vulnerability" },
  { value: "4", valueType: "22", label: "50% Damage Vulnerability" },
  { value: "5", valueType: "22", label: "75% Damage Vulnerability" },
  { value: "6", valueType: "22", label: "90% Damage Vulnerability" },
  { value: "7", valueType: "22", label: "100% Damage Vulnerability" },
  { value: "1", valueType: "23", label: "Level 1 or Lower" },
  { value: "2", valueType: "23", label: "Level 2 or Lower" },
  { value: "3", valueType: "23", label: "Level 3 or Lower" },
  { value: "4", valueType: "23", label: "Level 4 or Lower" },
  { value: "5", valueType: "23", label: "Level 5 or Lower" },
  { value: "6", valueType: "23", label: "Level 6 or Lower" },
  { value: "7", valueType: "23", label: "Level 7 or Lower" },
  { value: "8", valueType: "23", label: "Level 8 or Lower" },
  { value: "9", valueType: "23", label: "Level 9 or Lower" },
  { value: "0", valueType: "24", label: "DC=14" },
  { value: "1", valueType: "24", label: "DC=16" },
  { value: "2", valueType: "24", label: "DC=18" },
  { value: "3", valueType: "24", label: "DC=20" },
  { value: "4", valueType: "24", label: "DC=22" },
  { value: "5", valueType: "24", label: "DC=24" },
  { value: "6", valueType: "24", label: "DC=26" },
  { value: "1", valueType: "25", label: "+1" },
  { value: "2", valueType: "25", label: "+2" },
  { value: "3", valueType: "25", label: "+3" },
  { value: "4", valueType: "25", label: "+4" },
  { value: "5", valueType: "25", label: "+5" },
  { value: "6", valueType: "25", label: "+6" },
  { value: "7", valueType: "25", label: "+7" },
  { value: "8", valueType: "25", label: "+8" },
  { value: "9", valueType: "25", label: "+9" },
  { value: "10", valueType: "25", label: "+10" },
  { value: "11", valueType: "25", label: "+11" },
  { value: "12", valueType: "25", label: "+12" },
  { value: "13", valueType: "25", label: "+13" },
  { value: "14", valueType: "25", label: "+14" },
  { value: "15", valueType: "25", label: "+15" },
  { value: "16", valueType: "25", label: "+16" },
  { value: "17", valueType: "25", label: "+17" },
  { value: "18", valueType: "25", label: "+18" },
  { value: "19", valueType: "25", label: "+19" },
  { value: "20", valueType: "25", label: "+20" },
  { value: "21", valueType: "25", label: "+21" },
  { value: "22", valueType: "25", label: "+22" },
  { value: "23", valueType: "25", label: "+23" },
  { value: "24", valueType: "25", label: "+24" },
  { value: "25", valueType: "25", label: "+25" },
  { value: "26", valueType: "25", label: "+26" },
  { value: "27", valueType: "25", label: "+27" },
  { value: "28", valueType: "25", label: "+28" },
  { value: "29", valueType: "25", label: "+29" },
  { value: "30", valueType: "25", label: "+30" },
  { value: "31", valueType: "25", label: "+31" },
  { value: "32", valueType: "25", label: "+32" },
  { value: "33", valueType: "25", label: "+33" },
  { value: "34", valueType: "25", label: "+34" },
  { value: "35", valueType: "25", label: "+35" },
  { value: "36", valueType: "25", label: "+36" },
  { value: "37", valueType: "25", label: "+37" },
  { value: "38", valueType: "25", label: "+38" },
  { value: "39", valueType: "25", label: "+39" },
  { value: "40", valueType: "25", label: "+40" },
  { value: "41", valueType: "25", label: "+41" },
  { value: "42", valueType: "25", label: "+42" },
  { value: "43", valueType: "25", label: "+43" },
  { value: "44", valueType: "25", label: "+44" },
  { value: "45", valueType: "25", label: "+45" },
  { value: "46", valueType: "25", label: "+46" },
  { value: "47", valueType: "25", label: "+47" },
  { value: "48", valueType: "25", label: "+48" },
  { value: "49", valueType: "25", label: "+49" },
  { value: "50", valueType: "25", label: "+50" },
  { value: "0", valueType: "26", label: "Level 1" },
  { value: "1", valueType: "26", label: "Level 2" },
  { value: "2", valueType: "26", label: "Level 3" },
  { value: "3", valueType: "26", label: "Level 4" },
  { value: "4", valueType: "26", label: "Level 5" },
  { value: "5", valueType: "26", label: "Level 6" },
  { value: "6", valueType: "26", label: "Level 7" },
  { value: "7", valueType: "26", label: "Level 8" },
  { value: "8", valueType: "26", label: "Level 9" },
  { value: "9", valueType: "26", label: "Level 10" },
  { value: "10", valueType: "26", label: "Level 11" },
  { value: "11", valueType: "26", label: "Level 12" },
  { value: "12", valueType: "26", label: "Level 13" },
  { value: "13", valueType: "26", label: "Level 14" },
  { value: "14", valueType: "26", label: "Level 15" },
  { value: "15", valueType: "26", label: "Level 16" },
  { value: "16", valueType: "26", label: "Level 17" },
  { value: "17", valueType: "26", label: "Level 18" },
  { value: "18", valueType: "26", label: "Level 19" },
  { value: "19", valueType: "26", label: "Level 20" },
  { value: "20", valueType: "26", label: "Level 21" },
  { value: "21", valueType: "26", label: "Level 22" },
  { value: "22", valueType: "26", label: "Level 23" },
  { value: "23", valueType: "26", label: "Level 24" },
  { value: "24", valueType: "26", label: "Level 25" },
  { value: "25", valueType: "26", label: "Level 26" },
  { value: "26", valueType: "26", label: "Level 27" },
  { value: "27", valueType: "26", label: "Level 28" },
  { value: "28", valueType: "26", label: "Level 29" },
  { value: "29", valueType: "26", label: "Level 30" },
  { value: "30", valueType: "26", label: "Level 31" },
  { value: "31", valueType: "26", label: "Level 32" },
  { value: "32", valueType: "26", label: "Level 33" },
  { value: "33", valueType: "26", label: "Level 34" },
  { value: "34", valueType: "26", label: "Level 35" },
  { value: "35", valueType: "26", label: "Level 36" },
  { value: "36", valueType: "26", label: "Level 37" },
  { value: "37", valueType: "26", label: "Level 38" },
  { value: "38", valueType: "26", label: "Level 39" },
  { value: "39", valueType: "26", label: "Level 40" },
  { value: "0", valueType: "27", label: "-50%" },
  { value: "1", valueType: "27", label: "-45%" },
  { value: "2", valueType: "27", label: "-40%" },
  { value: "3", valueType: "27", label: "-35%" },
  { value: "4", valueType: "27", label: "-30%" },
  { value: "5", valueType: "27", label: "-25%" },
  { value: "6", valueType: "27", label: "-20%" },
  { value: "7", valueType: "27", label: "-15%" },
  { value: "8", valueType: "27", label: "-10%" },
  { value: "9", valueType: "27", label: "-05%" },
  { value: "10", valueType: "27", label: "+05%" },
  { value: "11", valueType: "27", label: "+10%" },
  { value: "12", valueType: "27", label: "+15%" },
  { value: "13", valueType: "27", label: "+20%" },
  { value: "14", valueType: "27", label: "+25%" },
  { value: "15", valueType: "27", label: "+30%" },
  { value: "16", valueType: "27", label: "+35%" },
  { value: "17", valueType: "27", label: "+40%" },
  { value: "18", valueType: "27", label: "+45%" },
  { value: "19", valueType: "27", label: "+50%" },
  { value: "0", valueType: "28", label: "Unknown" },
  { value: "1", valueType: "28", label: "Adamantine" },
  { value: "2", valueType: "28", label: "Brass" },
  { value: "3", valueType: "28", label: "Bronze" },
  { value: "4", valueType: "28", label: "Carbon" },
  { value: "5", valueType: "28", label: "Cold Iron" },
  { value: "6", valueType: "28", label: "Copper" },
  { value: "7", valueType: "28", label: "Darksteel" },
  { value: "8", valueType: "28", label: "Gold" },
  { value: "9", valueType: "28", label: "Iron" },
  { value: "10", valueType: "28", label: "Lead" },
  { value: "11", valueType: "28", label: "Mithral" },
  { value: "12", valueType: "28", label: "Platinum" },
  { value: "13", valueType: "28", label: "Silver" },
  { value: "14", valueType: "28", label: "Silver, Alchemical" },
  { value: "15", valueType: "28", label: "Steel" },
  { value: "16", valueType: "28", label: "Bone" },
  { value: "17", valueType: "28", label: "Hide" },
  { value: "18", valueType: "28", label: "Hide, Salamander" },
  { value: "19", valueType: "28", label: "Hide, Umber Hulk" },
  { value: "20", valueType: "28", label: "Hide, Wyvern" },
  { value: "21", valueType: "28", label: "Hide, Dragon, Black" },
  { value: "22", valueType: "28", label: "Hide, Dragon, Blue" },
  { value: "23", valueType: "28", label: "Hide, Dragon, Brass" },
  { value: "24", valueType: "28", label: "Hide, Dragon, Bronze" },
  { value: "25", valueType: "28", label: "Hide, Dragon, Copper" },
  { value: "26", valueType: "28", label: "Hide, Dragon, Gold" },
  { value: "27", valueType: "28", label: "Hide, Dragon, Green" },
  { value: "28", valueType: "28", label: "Hide, Dragon, Red" },
  { value: "29", valueType: "28", label: "Hide, Dragon, Silver" },
  { value: "30", valueType: "28", label: "Hide, Dragon, White" },
  { value: "31", valueType: "28", label: "Leather" },
  { value: "32", valueType: "28", label: "Scale" },
  { value: "33", valueType: "28", label: "Cloth" },
  { value: "34", valueType: "28", label: "Cotton" },
  { value: "35", valueType: "28", label: "Silk" },
  { value: "36", valueType: "28", label: "Wool" },
  { value: "37", valueType: "28", label: "Wood" },
  { value: "38", valueType: "28", label: "Wood, Ironwood" },
  { value: "39", valueType: "28", label: "Wood, Duskwood" },
  { value: "40", valueType: "28", label: "Wood, Darkwood, Zalantar" },
  { value: "41", valueType: "28", label: "Wood, Ash" },
  { value: "42", valueType: "28", label: "Wood, Yew" },
  { value: "43", valueType: "28", label: "Wood, Oak" },
  { value: "44", valueType: "28", label: "Wood, Pine" },
  { value: "45", valueType: "28", label: "Wood, Cedar" },
  { value: "46", valueType: "28", label: "Elemental" },
  { value: "47", valueType: "28", label: "Elemental, Air" },
  { value: "48", valueType: "28", label: "Elemental, Earth" },
  { value: "49", valueType: "28", label: "Elemental, Fire" },
  { value: "50", valueType: "28", label: "Elemental, Water" },
  { value: "51", valueType: "28", label: "Gem" },
  { value: "52", valueType: "28", label: "Gem, Alexandrite" },
  { value: "53", valueType: "28", label: "Gem, Amethyst" },
  { value: "54", valueType: "28", label: "Gem, Aventurine" },
  { value: "55", valueType: "28", label: "Gem, Beljuril" },
  { value: "56", valueType: "28", label: "Gem, Bloodstone" },
  { value: "57", valueType: "28", label: "Gem, Blue Diamond" },
  { value: "58", valueType: "28", label: "Gem, Canary Diamond" },
  { value: "59", valueType: "28", label: "Gem, Diamond" },
  { value: "60", valueType: "28", label: "Gem, Emerald" },
  { value: "61", valueType: "28", label: "Gem, Fire Agate" },
  { value: "62", valueType: "28", label: "Gem, Fire Opal" },
  { value: "63", valueType: "28", label: "Gem, Flourspar" },
  { value: "64", valueType: "28", label: "Gem, Garnet" },
  { value: "65", valueType: "28", label: "Gem, Greenstone" },
  { value: "66", valueType: "28", label: "Gem, Jacinth" },
  { value: "67", valueType: "28", label: "Gem, Kings Tear" },
  { value: "68", valueType: "28", label: "Gem, Malachite" },
  { value: "69", valueType: "28", label: "Gem, Obsidian" },
  { value: "70", valueType: "28", label: "Gem, Phenalope" },
  { value: "71", valueType: "28", label: "Gem, Rogue Stone" },
  { value: "72", valueType: "28", label: "Gem, Ruby" },
  { value: "73", valueType: "28", label: "Gem, Sapphire" },
  { value: "74", valueType: "28", label: "Gem, Star Sapphire" },
  { value: "75", valueType: "28", label: "Gem, Topaz" },
  { value: "76", valueType: "28", label: "Gem, Crystal, Deep" },
  { value: "77", valueType: "28", label: "Gem, Crystal, Mundane" },
  { value: "0", valueType: "29", label: "Unknown" },
  { value: "1", valueType: "29", label: "Destroyed" },
  { value: "2", valueType: "29", label: "Ruined" },
  { value: "3", valueType: "29", label: "Very Poor" },
  { value: "4", valueType: "29", label: "Poor" },
  { value: "5", valueType: "29", label: "Below Average" },
  { value: "6", valueType: "29", label: "Average" },
  { value: "7", valueType: "29", label: "Above Average" },
  { value: "8", valueType: "29", label: "Good" },
  { value: "9", valueType: "29", label: "Very Good" },
  { value: "10", valueType: "29", label: "Excellent" },
  { value: "11", valueType: "29", label: "Masterwork" },
  { value: "12", valueType: "29", label: "Godlike" },
  { value: "13", valueType: "29", label: "Raw" },
  { value: "14", valueType: "29", label: "Cut" },
  { value: "15", valueType: "29", label: "Polished" },
  { value: "0", valueType: "30", label: "Unknown" },
  { value: "1", valueType: "30", label: "Cursed" },
];
