import { DropdownListItem } from ".";

export const Music: DropdownListItem[] = [
  { value: "0", label: "(No Music Track)()" },
  { value: "1", label: "Rural Day 1(mus_ruralday1)" },
  { value: "2", label: "Rural Day 2(mus_ruralday2)" },
  { value: "3", label: "Rural Night(mus_ruralnite)" },
  { value: "4", label: "Forest Day 1(mus_forestday1)" },
  { value: "5", label: "Forest Day 2(mus_forestday2)" },
  { value: "6", label: "Forest Night(mus_forestnite)" },
  { value: "7", label: "Generic Dungeon(mus_gendungeon1)" },
  { value: "8", label: "Sewer (mus_sewer)" },
  { value: "9", label: "Mines 1(mus_mines1)" },
  { value: "10", label: "Mines 2(mus_mines2)" },
  { value: "11", label: "Crypt 1(mus_crypt1)" },
  { value: "12", label: "Crypt 2(mus_crypt2)" },
  { value: "13", label: "Evil Dungeon 1(mus_evildungeon1)" },
  { value: "14", label: "Evil Dungeon 2(mus_evildungeon2)" },
  { value: "15", label: "City Slum Day(mus_cityslumday)" },
  { value: "16", label: "City Slum Night(mus_cityslumnite)" },
  { value: "17", label: "City Docks Day(mus_citydockday)" },
  { value: "18", label: "City Docks Night(mus_citydocknite)" },
  { value: "19", label: "City Wealthy(mus_citywealthy)" },
  { value: "20", label: "City Marketplace (mus_citymarket)" },
  { value: "21", label: "City Night(mus_citynite)" },
  { value: "22", label: "Tavern 1(mus_tavern1)" },
  { value: "23", label: "Tavern 2(mus_tavern2)" },
  { value: "24", label: "Tavern 3(mus_tavern3)" },
  { value: "25", label: "Generic Wealthy House(mus_richhouse)" },
  { value: "26", label: "Generic Store(mus_store)" },
  { value: "27", label: "Good Temple(mus_templegood)" },
  { value: "28", label: "Evil Temple(mus_templeevil)" },
  { value: "29", label: "NWN City Theme(mus_theme_nwn)" },
  { value: "30", label: "NWN Chapter 1(mus_theme_chap1)" },
  { value: "31", label: "NWN Chapter 2 (mus_theme_chap2)" },
  { value: "32", label: "NWN Chapter 3(mus_theme_chap3)" },
  { value: "33", label: "NWN Chapter 4(mus_theme_chap4)" },
  { value: "34", label: "Rural Combat 1(mus_bat_rural1)" },
  { value: "35", label: "Forest Combat 1(mus_bat_forest1)" },
  { value: "36", label: "Forest Combat 2(mus_bat_forest2)" },
  { value: "37", label: "Dungeon Combat 1(mus_bat_dung1)" },
  { value: "38", label: "Dungeon Combat 2(mus_bat_dung2)" },
  { value: "39", label: "Dungeon Combat 3(mus_bat_dung3)" },
  { value: "40", label: "City Combat 1(mus_bat_city1)" },
  { value: "41", label: "City Combat 2(mus_bat_city2)" },
  { value: "42", label: "City Combat 3(mus_bat_city3)" },
  { value: "43", label: "Boss Combat City (mus_bat_citboss)" },
  { value: "44", label: "Boss Combat Forest(mus_bat_forboss)" },
  { value: "45", label: "Boss Lizardfolk(mus_bat_lizboss)" },
  { value: "46", label: "Dragon Combat(mus_bat_dragon)" },
  { value: "47", label: "Combat Aribeth(mus_bat_aribeth)" },
  { value: "48", label: "Final Boss Combat Source Stone(mus_bat_endboss)" },
  { value: "49", label: "Good Temple 2(mus_templegood2)" },
  { value: "50", label: "Generic Castle Interior(mus_castle)" },
  { value: "51", label: "Aribeth Theme 1(mus_theme_aribgd)" },
  { value: "52", label: "Aribeth Theme 2(mus_theme_aribev)" },
  { value: "53", label: "Theme Aarin Gend(mus_theme_argend)" },
  { value: "54", label: "Theme Maugrim(mus_theme_maugrm)" },
  { value: "55", label: "Theme Morag(mus_theme_morag)" },
  { value: "56", label: "Tavern 4(mus_tavern4)" },
  { value: "57", label: "Desert Combat(mus_bat_x0desert)" },
  { value: "58", label: "Desert Day(mus_x0desertday)" },
  { value: "59", label: "Winter Day(mus_x0winterday)" },
  { value: "60", label: "Fight! Fight!(mus_bat_x0winter)" },
  { value: "61", label: "Desert Night(mus_x0desertngt)" },
  { value: "62", label: "XP2 - Theme(mus_x2theme)" },
  { value: "63", label: "XP2 - Waterdeep(mus_x2waterdeep)" },
  { value: "64", label: "XP2 - Undermountain(mus_x2undermtn)" },
  { value: "65", label: "XP2 - Rebel Camp(mus_x2rebelcamp)" },
  { value: "66", label: "XP2 - Beholder Caves(mus_x2fireplane)" },
  { value: "67", label: "XP2 - Queen of the Shattered Mirror(mus_x2queen)" },
  { value: "68", label: "XP2 - Chapter 3(mus_x2frozenhell)" },
  { value: "69", label: "XP2 - Dracolich(mus_x2draco)" },
  { value: "70", label: "XP2 - Battle, Small(mus_bat_x2small)" },
  { value: "71", label: "XP2 - Battle, Medium(mus_bat_x2med)" },
  { value: "72", label: "XP2 - Battle, Large(mus_bat_x2large)" },
  { value: "73", label: "XP2 - Battle, Chapter 3(mus_bat_x2hell)" },
  { value: "74", label: "XP2 - Battle, Matron(mus_bat_x2boss1)" },
  { value: "75", label: "XP2 - Battle, Final(mus_bat_x2boss2)" },
  { value: "76", label: "PM - Kingmaker Theme(mus_dd_kingmaker)" },
  { value: "77", label: "PM - ShadowGuard Theme(mus_dd_shadowgua)" },
  { value: "78", label: "PM - Witch's Wake Theme(mus_dd_witchwake)" },
  { value: "79", label: "PM - Pirates Theme(mus_dd_islands)" },
  { value: "80", label: "PM - Pirates Theme Variation(mus_dd_pirates)" },
  { value: "81", label: "PM - Infinite Dungeons(mus_dd_infdun)" },
  { value: "82", label: "PM - Wyvern Crown Ogma(mus_wc_ogma)" },
  { value: "83", label: "PM - Wyvern Crown Open Road(mus_wc_openroad)" },
  { value: "84", label: "PM - Wyvern Crown Smoke and Ash(mus_wc_smokeash)" },
  { value: "85", label: "PM - Wyvern Crown Rural(mus_wc_rural)" },
  { value: "86", label: "PM - Wyvern Crown Rural Guitar(mus_wc_ruralg)" },
  { value: "87", label: "PM - Wyvern Crown Tears(mus_wc_tears)" },
  { value: "88", label: "PM - Wyvern Crown Battle Chase(mus_bat_wcchase)" },
  { value: "89", label: "PM - Wyvern Crown Theme(mus_wc_theme)" },
  { value: "90", label: "PM - Wyvern Crown Armchair(mus_wc_armchair)" },
  { value: "91", label: "PM - Wyvern Crown Battle(mus_bat_wcbattle)" },
  { value: "92", label: "PM - Wyvern Crown Solace(mus_wc_solace)" },
  { value: "93", label: "PM - Wyvern Crown Knighted(mus_wc_knighted)" },
  { value: "94", label: "PM - Wyvern Crown Opening(mus_wc_opening)" },
  { value: "95", label: "PM - Wyvern Crown Morfen(mus_wc_morfen)" },
  { value: "96", label: "Bad Strref(mus_pmp01_)" },
  { value: "97", label: "Bad Strref(mus_pmp02_)" },
  { value: "98", label: "Bad Strref(mus_pmp03_)" },
  { value: "99", label: "Bad Strref(mus_pmp04_)" },
  { value: "100", label: "Bad Strref(mus_pmp05_)" },
  { value: "101", label: "Bad Strref(mus_pmp06_)" },
  { value: "102", label: "Bad Strref(mus_pmp07_)" },
  { value: "103", label: "Bad Strref(mus_pmp08_)" },
  { value: "104", label: "Bad Strref(mus_pmp09_)" },
  { value: "105", label: "Bad Strref(mus_pmp10_)" },
  { value: "106", label: "Bad Strref(mus_pmp11_)" },
  { value: "107", label: "Bad Strref(mus_pmp12_)" },
  { value: "108", label: "Bad Strref(mus_pmp13_)" },
  { value: "109", label: "Bad Strref(mus_pmp14_)" },
  { value: "110", label: "Bad Strref(mus_pmp15_)" },
  { value: "111", label: "Bad Strref(mus_pmp16_)" },
  { value: "112", label: "Bad Strref(mus_pmp17_)" },
  { value: "113", label: "Bad Strref(mus_pmp18_)" },
  { value: "114", label: "Bad Strref(mus_pmp19_)" },
  { value: "115", label: "Bad Strref(mus_pmp20_)" },
  { value: "116", label: "Bad Strref(mus_pmp21_)" },
  { value: "117", label: "Bad Strref(mus_pmp22_)" },
  { value: "118", label: "Bad Strref(mus_pmp23_)" },
  { value: "119", label: "Bad Strref(mus_pmp24_)" },
  { value: "120", label: "Bad Strref(mus_pmp25_)" },
  { value: "121", label: "Bad Strref(mus_pmp26_)" },
  { value: "122", label: "Bad Strref(mus_pmp27_)" },
  { value: "123", label: "Bad Strref(mus_pmp28_)" },
  { value: "124", label: "Bad Strref(mus_pmp29_)" },
  { value: "125", label: "Bad Strref(mus_pmp30_)" },
  { value: "126", label: "Bad Strref(mus_pmp31_)" },
  { value: "127", label: "Bad Strref(mus_pmp32_)" },
  { value: "128", label: "Bad Strref(mus_pmp33_)" },
  { value: "129", label: "Bad Strref(mus_pmp34_)" },
  { value: "130", label: "Bad Strref(mus_pmp35_)" },
  { value: "131", label: "Bad Strref(mus_pmp36_)" },
  { value: "132", label: "Bad Strref(mus_pmp37_)" },
  { value: "133", label: "Bad Strref(mus_pmp38_)" },
];
