import { DropdownListItem } from ".";

export const SoundSet: DropdownListItem[] = [
  { value: "0", label: "Aasimar, Male" },
  { value: "1", label: "Archon, Hound" },
  { value: "2", label: "Archon, Lantern" },
  { value: "4", label: "Badger" },
  { value: "5", label: "Badger, Dire" },
  { value: "6", label: "Bat" },
  { value: "7", label: "Bear" },
  { value: "8", label: "Bear, Dire" },
  { value: "9", label: "Beetle" },
  { value: "10", label: "Boar" },
  { value: "11", label: "Boar, Dire" },
  { value: "12", label: "Bugbear" },
  { value: "13", label: "Bugbear Chieftain" },
  { value: "14", label: "Bugbear Shaman" },
  { value: "15", label: "Cat" },
  { value: "16", label: "Cat, Dire Tiger" },
  { value: "17", label: "Cat, Krenshar" },
  { value: "18", label: "Cat, Lion" },
  { value: "19", label: "Cat, Panther" },
  { value: "20", label: "Celestial Avenger" },
  { value: "21", label: "Chicken" },
  { value: "936", label: "Cow" },
  { value: "23", label: "Curst" },
  { value: "24", label: "Deer" },
  { value: "25", label: "Demon" },
  { value: "26", label: "Devourer" },
  { value: "27", label: "Dog" },
  { value: "28", label: "Doom Knight" },
  { value: "29", label: "Dragon, Old" },
  { value: "30", label: "Dragon, Young" },
  { value: "31", label: "Dryad" },
  { value: "32", label: "Elemental, Air" },
  { value: "33", label: "Elemental, Earth" },
  { value: "34", label: "Elemental, Fire" },
  { value: "35", label: "Elemental, Water" },
  { value: "36", label: "Ettercap" },
  { value: "37", label: "Fairy" },
  { value: "38", label: "Falcon" },
  { value: "39", label: "Gargoyle" },
  { value: "40", label: "Ghoul" },
  { value: "41", label: "Ghoul Lord" },
  { value: "42", label: "Giant, Common" },
  { value: "43", label: "Giant, Noble" },
  { value: "44", label: "Goblin" },
  { value: "45", label: "Goblin Chieftain" },
  { value: "46", label: "Goblin Shaman" },
  { value: "47", label: "Golem, Bone" },
  { value: "48", label: "Golem, Flesh" },
  { value: "49", label: "Golem, Iron" },
  { value: "50", label: "Golem, Stone" },
  { value: "51", label: "Grey Render" },
  { value: "52", label: "Hell Hound" },
  { value: "53", label: "Hook Horror" },
  { value: "54", label: "Helmed Horror" },
  { value: "55", label: "Invisible Stalker" },
  { value: "56", label: "Lich" },
  { value: "57", label: "Lizardfolk, Female" },
  { value: "58", label: "Lizardfolk, Female Chief" },
  { value: "59", label: "Lizardfolk, Female Mage" },
  { value: "60", label: "Lizardfolk, Male" },
  { value: "61", label: "Lizardfolk, Male Chief" },
  { value: "62", label: "Lizardfolk, Male Mage" },
  { value: "63", label: "Mephit" },
  { value: "64", label: "Minotaur" },
  { value: "65", label: "Minotaur, Chieftain" },
  { value: "66", label: "Minotaur, Shaman" },
  { value: "67", label: "Mohrg" },
  { value: "68", label: "Mummy, Common" },
  { value: "69", label: "Mummy, Greater" },
  { value: "70", label: "Ogre" },
  { value: "71", label: "Ogre Chieftain" },
  { value: "72", label: "Ogre Mage" },
  { value: "73", label: "Orc" },
  { value: "74", label: "Orc Chieftain" },
  { value: "75", label: "Orc Shaman" },
  { value: "76", label: "Rakshasa, Male" },
  { value: "77", label: "Raven" },
  { value: "78", label: "Shadow" },
  { value: "79", label: "Skeleton" },
  { value: "80", label: "Skeleton, Chieftain" },
  { value: "81", label: "Skeleton, Mage" },
  { value: "82", label: "Skeleton, Warrior" },
  { value: "83", label: "Slaad, Powerful" },
  { value: "84", label: "Slaad, Weaker" },
  { value: "85", label: "Spider, Giant" },
  { value: "86", label: "Spider, Dire" },
  { value: "87", label: "Spider, Phase" },
  { value: "88", label: "Spider, Sword" },
  { value: "89", label: "Spider, Wraith" },
  { value: "90", label: "Succubus" },
  { value: "91", label: "Tiefling, Female" },
  { value: "92", label: "Troll" },
  { value: "93", label: "Troll, Chieftain" },
  { value: "94", label: "Troll, Shaman" },
  { value: "95", label: "Umber Hulk" },
  { value: "96", label: "Vampire" },
  { value: "97", label: "Vrock" },
  { value: "98", label: "Werecat" },
  { value: "99", label: "Wererat" },
  { value: "100", label: "Werewolf" },
  { value: "101", label: "Wight" },
  { value: "102", label: "Will-O-Wisp" },
  { value: "103", label: "Wolf" },
  { value: "104", label: "Wolf, Dire" },
  { value: "105", label: "Wolf, Winter" },
  { value: "106", label: "Worg" },
  { value: "107", label: "Wraith" },
  { value: "108", label: "Yuan-ti, Female" },
  { value: "912", label: "Zombie" },
  { value: "110", label: "Zombie, Tyrant Fog" },
  { value: "111", label: "Zombie Warrior" },
  { value: "112", label: "Human, Female, Barbarian" },
  { value: "113", label: "Human, Male, Barbarian, Stupid" },
  { value: "114", label: "Half-Orc, Male, Chieftain" },
  { value: "115", label: "Human, Male, Barbarian, Warrior" },
  { value: "116", label: "Human, Male, Older, Muttering Beggar" },
  { value: "117", label: "Human, Male, Older, Street Prophet" },
  { value: "118", label: "Human, Male, Typical Brash Scumbag" },
  { value: "119", label: "Human, Male, Typical Low-Class Villain" },
  { value: "120", label: "Child, Female" },
  { value: "121", label: "Child, Male, Pleasant" },
  { value: "122", label: "Child, Male, Brat" },
  { value: "123", label: "Human, Male, Typical Cleric" },
  { value: "124", label: "Human, Male, Older, Melancholy" },
  { value: "125", label: "Elf, Male, Cleric" },
  { value: "126", label: "Human, Male, Noble, Young and Arrogant" },
  { value: "127", label: "Human, Female, Older, Strange Hermit" },
  { value: "128", label: "Elf, Female, Typical" },
  { value: "129", label: "Human, Male, Older, Confident Leader" },
  { value: "130", label: "Dwarf, Male, Veteran" },
  { value: "131", label: "Elf, Male, Brooding" },
  { value: "132", label: "Elf, Male, Typical" },
  { value: "133", label: "Human, Female, Evil, Fanatic" },
  { value: "134", label: "Human, Male, Evil, Fanatic" },
  { value: "135", label: "Elf, Female, Sensible" },
  { value: "136", label: "Human, Female, Barmaid, Flirty" },
  { value: "137", label: "Elf, Female, Commoner, Pleasant" },
  { value: "138", label: "Human, Male, Older, World-Weary" },
  { value: "139", label: "Human, Male, Commoner, Uneducated" },
  { value: "140", label: "Human, Male, Typical Druid" },
  { value: "141", label: "Dwarf, Male, Older, Grouch" },
  { value: "142", label: "Gnome, Male, Annoying" },
  { value: "143", label: "Gnome, Male, Pleasant" },
  { value: "144", label: "Halfling, Female, Sensible" },
  { value: "145", label: "Halfling, Male, Typical" },
  { value: "146", label: "Human, Male, Evil, Sly Assassin" },
  { value: "147", label: "Human, Male, Evil, Methodical Villain" },
  { value: "148", label: "Human, Male, Evil, Typical Fighter" },
  { value: "149", label: "Human, Female, Middle-Age Commoner" },
  { value: "150", label: "Human, Female, Older Commoner" },
  { value: "151", label: "Human, Female, Young, Pleasant" },
  { value: "152", label: "Human, Male, Commoner, Older" },
  { value: "153", label: "Elf, Male, Upper-Class" },
  { value: "154", label: "Elf, Female, Guard" },
  { value: "155", label: "Elf, Male, Guard, Mature Officer" },
  { value: "156", label: "Human, Male, Guard, Good, Rough" },
  { value: "157", label: "Human, Female, Noble, Caring" },
  { value: "158", label: "Human, Female, Noble, Snobbish" },
  { value: "159", label: "Human, Male, Noble, Snobbish" },
  { value: "160", label: "Human, Male, Noble, Older, Uncaring" },
  { value: "161", label: "Human, Male, Veteran Paladin" },
  { value: "162", label: "Halfling, Female, Typical" },
  { value: "163", label: "Dwarf, Male, Typical" },
  { value: "164", label: "Gnome, Male, Typical" },
  { value: "165", label: "Elf, Male, Slight, Lilting" },
  { value: "166", label: "Human, Female, Courtesan, Friendly" },
  { value: "167", label: "Human, Female, Courtesan, Obvious" },
  { value: "168", label: "Human, Female, Courtesan, Accent" },
  { value: "169", label: "Human, Male, Gigolo, Seductive" },
  { value: "170", label: "Human, Male, Gigolo, Smarmy" },
  { value: "171", label: "Human, Male, Stoic Ranger" },
  { value: "172", label: "Human, Male, Veteran Rogue" },
  { value: "173", label: "Human, Male, Unsavory Shopkeep" },
  { value: "174", label: "Human, Male, Older Shopkeep" },
  { value: "175", label: "Human, Male, Retired Adventurer" },
  { value: "176", label: "Half-Orc, Female, Lout" },
  { value: "177", label: "Human, Male, Bully" },
  { value: "178", label: "Gnome, Male, Older" },
  { value: "179", label: "Dwarf, Male, Evil Thug" },
  { value: "180", label: "Elf, Female, Wizard" },
  { value: "181", label: "Human, Male, Wizard, Old" },
  { value: "183", label: "Human, Male, Older Slave" },
  { value: "184", label: "Human, Male, Commoner, Toady" },
  { value: "185", label: "Human, Male, Drunk" },
  { value: "186", label: "Human, Male, Guard, Gruff" },
  { value: "187", label: "Human, Male, Barbarian, Good" },
  { value: "188", label: "Human, Female, Guard, Sedos" },
  { value: "189", label: "Human, Male, Teen" },
  { value: "190", label: "Human, Male, Guard, Arrogant" },
  { value: "191", label: "Human, Male, Wizard" },
  { value: "192", label: "Half-Orc, Male, Gruff Lout" },
  { value: "193", label: "Human, Male, Average Joe" },
  { value: "194", label: "Human, Female, Noble, Unfriendly" },
  { value: "195", label: "Human, Male, Farmer" },
  { value: "196", label: "Halfelf, Male, Agitated" },
  { value: "197", label: "Nymph/Dryad, Arwyl" },
  { value: "198", label: "Minotaur, Zor" },
  { value: "199", label: "Celestial, Female, Guardian" },
  { value: "200", label: "Spirit, male, Zelieph" },
  { value: "201", label: "Imp, Ebrax" },
  { value: "202", label: "Lich, Karlat" },
  { value: "203", label: "Goblin King" },
  { value: "204", label: "Orc, Pompous" },
  { value: "205", label: "Succubus, Manipulative" },
  { value: "206", label: "Dragon, Female, Green Akula" },
  { value: "207", label: "Dragon, Female, Brass Gorg" },
  { value: "208", label: "Dragon, Male, Red Klauth" },
  { value: "209", label: "Lizardfolk, Male Fanatical" },
  { value: "210", label: "Linu La'neral" },
  { value: "211", label: "Sharwyn" },
  { value: "212", label: "Daelan Red Tiger" },
  { value: "213", label: "Tomi Grin Undergallows" },
  { value: "214", label: "Grimgnaw" },
  { value: "215", label: "Boddyknock Glinckle" },
  { value: "216", label: "Male, Brash Persistent" },
  { value: "217", label: "Male, Boisterous Goodnatured" },
  { value: "218", label: "Male, Brooding Dark Hero" },
  { value: "219", label: "Male, Violent Fighter" },
  { value: "220", label: "Female, Noble Scholar" },
  { value: "221", label: "Male, Large Rowdy" },
  { value: "222", label: "Male, High-strung Evangelist" },
  { value: "223", label: "Male, Reserved Guardian" },
  { value: "224", label: "Male, Pious Scholar" },
  { value: "225", label: "Female, Noble Matron" },
  { value: "226", label: "Female, Guardian Reserved" },
  { value: "227", label: "Female, Innocent Idealist" },
  { value: "228", label: "Male, Manic Psychotic" },
  { value: "229", label: "Male, Mature Swashbuckler" },
  { value: "230", label: "Aribeth" },
  { value: "231", label: "Haedraline" },
  { value: "232", label: "Maugrim" },
  { value: "233", label: "Morag" },
  { value: "234", label: "Nasher" },
  { value: "235", label: "Fenthick" },
  { value: "236", label: "Desther" },
  { value: "237", label: "Wraith, Drawl" },
  { value: "238", label: "Intellect Devourer Victim" },
  { value: "239", label: "Dragon, Male, White Evil Guardian" },
  { value: "240", label: "Yuan-Ti, Female, Gulnan" },
  { value: "241", label: "Aarin Gend" },
  { value: "242", label: "Female, Fighter" },
  { value: "243", label: "Female, Cold Killer" },
  { value: "244", label: "Female, Seductress" },
  { value: "245", label: "Female, Brutish Thug" },
  { value: "246", label: "Kobold" },
  { value: "247", label: "Kobold, Thug" },
  { value: "248", label: "Kobold, Shaman" },
  { value: "249", label: "Rat" },
  { value: "250", label: "Rat, Dire" },
  { value: "251", label: "Gnoll" },
  { value: "252", label: "Gnoll, Shaman" },
  { value: "253", label: "Hobgoblin" },
  { value: "254", label: "Hobgoblin, Wizard" },
  { value: "255", label: "Devil" },
  { value: "256", label: "Maggris, the Hive Mother" },
  { value: "257", label: "Wereboar" },
  { value: "258", label: "Gem Golem" },
  { value: "259", label: "Horse" },
  { value: "949", label: "Snake" },
  { value: "261", label: "Mechanical" },
  { value: "306", label: "Giant, Frost (Female)" },
  { value: "307", label: "Giant, Fire (Female)" },
  { value: "308", label: "Medusa" },
  { value: "311", label: "Asabi Warrior" },
  { value: "313", label: "Stinger Warrior" },
  { value: "317", label: "Formian Warrior" },
  { value: "320", label: "Sphinx" },
  { value: "323", label: "Gorgon" },
  { value: "324", label: "Cockatrice" },
  { value: "953", label: "Basilisk" },
  { value: "330", label: "Faerie Dragon" },
  { value: "331", label: "Pseudodragon" },
  { value: "332", label: "Wyrmling" },
  { value: "342", label: "Human, Male, Desert Warrior" },
  { value: "343", label: "Lich, Mage" },
  { value: "344", label: "Elf, Male, Wizard" },
  { value: "345", label: "Medusa, Handmaid" },
  { value: "346", label: "Deekin Scalesinger" },
  { value: "347", label: "Dorna Trapspringer" },
  { value: "348", label: "Drogan Droganson" },
  { value: "349", label: "Heurodis" },
  { value: "350", label: "J'Nah" },
  { value: "351", label: "Katriana" },
  { value: "352", label: "Human, Male, Blackguard" },
  { value: "353", label: "Elf, Female, Noble" },
  { value: "354", label: "Mischa Waymeet" },
  { value: "355", label: "Half-Orc, Female, Baroness" },
  { value: "356", label: "Xanos" },
  { value: "357", label: "Female, Berserker" },
  { value: "358", label: "Female, Feisty" },
  { value: "359", label: "Female, Mature Commander" },
  { value: "360", label: "Female, Playful" },
  { value: "361", label: "Female, Quiet Leader" },
  { value: "363", label: "Male, Dumb Hero" },
  { value: "364", label: "Male, Power-Hungry" },
  { value: "365", label: "Male, Prankster" },
  { value: "366", label: "Male, Sociopath" },
  { value: "367", label: "Male, Stealth Specialist" },
  { value: "368", label: "Male, Neutral Warrior" },
  { value: "369", label: "Ashtara" },
  { value: "370", label: "Asabi Thrall" },
  { value: "371", label: "Ayala" },
  { value: "372", label: "Beholder" },
  { value: "373", label: "Beholder, Mage" },
  { value: "374", label: "Beholder, Eyeball" },
  { value: "375", label: "Mephistopheles, Large" },
  { value: "376", label: "Dracolich" },
  { value: "377", label: "Drider" },
  { value: "378", label: "Drider, Chief" },
  { value: "379", label: "Drow, Rebel" },
  { value: "380", label: "Drow, Wizard" },
  { value: "381", label: "Drow, Matron" },
  { value: "382", label: "Duergar, Slaver" },
  { value: "383", label: "Duergar, Chief" },
  { value: "384", label: "Mindflayer" },
  { value: "385", label: "Deep Rothe" },
  { value: "387", label: "Harpy" },
  { value: "388", label: "Golem, Mithril" },
  { value: "389", label: "Golem, Adamantium" },
  { value: "390", label: "Demon, Bebilith" },
  { value: "391", label: "Golem, Organic" },
  { value: "392", label: "Golem, Metal" },
  { value: "393", label: "Dragon, Prismatic" },
  { value: "394", label: "Avariel, Male" },
  { value: "395", label: "Avariel, Female" },
  { value: "396", label: "Demilich" },
  { value: "397", label: "Alhoon" },
  { value: "398", label: "Valsharess" },
  { value: "399", label: "Quarry Boss" },
  { value: "400", label: "Arden Swift" },
  { value: "401", label: "Sensei Dharvana" },
  { value: "402", label: "Sleeping Man" },
  { value: "403", label: "Knower of Places" },
  { value: "404", label: "Knower of Names" },
  { value: "405", label: "Deekin XP2" },
  { value: "406", label: "Durnan" },
  { value: "407", label: "The GateKeeper" },
  { value: "408", label: "Mephisopheles" },
  { value: "409", label: "Daelan XP2" },
  { value: "410", label: "Linu XP2" },
  { value: "411", label: "Sharwyn XP2" },
  { value: "412", label: "Tomi XP2" },
  { value: "413", label: "Valen Shadowbreath" },
  { value: "414", label: "Nathyrra" },
  { value: "415", label: "The Genie" },
  { value: "416", label: "Legendary Weapon" },
  { value: "417", label: "Aribeth XP2 Paladin" },
  { value: "418", label: "Male, Good Wizard" },
  { value: "419", label: "Male, Typical Fighter" },
  { value: "420", label: "Male, Archer" },
  { value: "421", label: "Female, Rogue" },
  { value: "422", label: "Female, Healer" },
  { value: "423", label: "Female, Maiden" },
  { value: "424", label: "Mhaere" },
  { value: "425", label: "White Thesta" },
  { value: "426", label: "Grovel" },
  { value: "427", label: "The Fairy Queen" },
  { value: "428", label: "The Ogre Boss" },
  { value: "429", label: "Sobrey" },
  { value: "430", label: "Agarly" },
  { value: "431", label: "Berger" },
  { value: "432", label: "Halaster" },
  { value: "433", label: "Female, Adventurer" },
  { value: "434", label: "Armand" },
  { value: "435", label: "Deva" },
  { value: "436", label: "Drow Seer" },
  { value: "437", label: "Drow Imloth" },
  { value: "438", label: "Drow Matron2" },
  { value: "439", label: "Boatman" },
  { value: "440", label: "Slave Leader" },
  { value: "441", label: "Dragon, Shadow" },
  { value: "442", label: "Golem, Demonflesh" },
  { value: "443", label: "Gelatinious Cube" },
  { value: "444", label: "Aribeth XP2 Blackguard" },
  { value: "445", label: "Sea Hag" },
  { value: "446", label: "Bulette" },
  { value: "447", label: "Troglodyte" },
  { value: "448", label: "Troglodyte Warrior" },
  { value: "449", label: "Troglodyte Cleric" },
  { value: "451", label: "Seagull" },
  { value: "452", label: "Parrot" },
  { value: "453", label: "Shark" },
  { value: "850", label: "Mechanical*" },
  { value: "901", label: "Viper*" },
  { value: "852", label: "Slime*" },
  { value: "853", label: "Treant*" },
  { value: "854", label: "Cat, Black*" },
  { value: "855", label: "Monodrone*" },
  { value: "935", label: "Horse*" },
  { value: "895", label: "CODI: Parai**" },
  { value: "896", label: "CODI: Secundus**" },
  { value: "897", label: "CODI: Primus**" },
  { value: "898", label: "CODI: Marut**" },
  { value: "899", label: "CODI: Mane**" },
  { value: "924", label: "Construct" },
  { value: "925", label: "Bone Skin" },
  { value: "937", label: "Animal" },
  { value: "934", label: "Deity" },
  { value: "946", label: "Reptilian" },
  { value: "950", label: "Magical Beast" },
  { value: "951", label: "Outsider" },
  { value: "952", label: "Undead" },
  { value: "957", label: "Dragon" },
  { value: "961", label: "Aberration" },
  { value: "65535", label: "None" },
];
