export const Spells = [
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "0",
    label: "Acid Fog",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "845",
    label: "Acid Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "424",
    label: "Acid Splash",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "853",
    label: "Agannazzar's Scorcher",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "2",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "1",
    label: "Aid",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "442",
    label: "Amplify",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "2",
    label: "Animate Dead",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "2",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "429",
    label: "Aura of Glory",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "562",
    label: "Aura of Glory - Cursed",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "761",
    label: "Aura of Hellfire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "372",
    label: "Aura of Vitality",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "323",
    label: "Aura versus Alignment",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "363",
    label: "Awaken",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "140",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "170",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "85",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "764",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "162",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "730",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "699",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "136",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "103",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "108",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "109",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "112",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "68",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "106",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "22",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "12",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "7",
    label: "Bad Strref",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "436",
    label: "Balagarn's Iron Horn",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1005",
    label: "Baleful Polymorph",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "850",
    label: "Baleful Transposition",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "516",
    label: "Ball Lightning",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "449",
    label: "Bane",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "430",
    label: "Banishment",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "3",
    label: "Barkskin",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "517",
    label: "Battletide",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "851",
    label: "Benign Transposition",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "4",
    label: "Bestow Curse",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "462",
    label: "Bigby's Clenched Fist",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "463",
    label: "Bigby's Crushing Hand",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "460",
    label: "Bigby's Forceful Hand",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "461",
    label: "Bigby's Grasping Hand",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "459",
    label: "Bigby's Interposing Hand",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "533",
    label: "Black Blade of Disaster",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "541",
    label: "Blackstaff",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "5",
    label: "Blade Barrier",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "535",
    label: "Blade Thirst",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "0",
    value: "1060",
    label: "Bladeweave",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "6",
    label: "Bless",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "537",
    label: "Bless Weapon",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1044",
    label: "Blighted Vines",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "8",
    label: "Blindness/Deafness",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "1033",
    label: "Blizzard",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "422",
    label: "Blood Frenzy",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1010",
    label: "Bodak's Glare",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1063",
    label: "Body of True Flame",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1037",
    label: "Body of the Sun",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "423",
    label: "Bombardment",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "2",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "9",
    label: "Bull's Strength",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1065",
    label: "Burning Bonds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "10",
    label: "Burning Hands",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "1041",
    label: "Burning Tempest",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "1034",
    label: "Burst of Glacial Wrath",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "1055",
    label: "Cacophonic Burst",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "11",
    label: "Call Lightning",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "0",
    value: "421",
    label: "Camouflage",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "2",
    value: "13",
    label: "Cat's Grace",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "14",
    label: "Chain Lightning",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "15",
    label: "Charm Monster",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "16",
    label: "Charm Person",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "17",
    label: "Charm Person or Animal",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1076",
    label: "Choir of Recovery",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "18",
    label: "Circle of Death",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "19",
    label: "Circle of Doom",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "20",
    label: "Clairaudience/Clairvoyance",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "21",
    label: "Clarity",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "569",
    label: "Cloud of Bewilderment",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "23",
    label: "Cloudkill",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "846",
    label: "Cold Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "24",
    label: "Color Spray",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "518",
    label: "Combust",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "25",
    label: "Cone of Cold",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "26",
    label: "Confusion",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "27",
    label: "Contagion",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "419",
    label: "Continual Flame",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "877",
    label: "Continual Flame (Blue)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "878",
    label: "Continual Flame (Orange)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "879",
    label: "Continual Flame (Purple)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "28",
    label: "Control Undead",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1046",
    label: "Corpse Explosion",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "29",
    label: "Create Greater Undead",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "564",
    label: "Create ShadowFiend",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "30",
    label: "Create Undead",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "364",
    label: "Creeping Doom",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "512",
    label: "Crumble",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1019",
    label: "Crushing Despair",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "4",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "31",
    label: "Cure Critical Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "567",
    label: "Cure Critical Wounds - Others",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "1",
    dataDruid: "1",
    dataPaladin: "1",
    dataRanger: "1",
    dataWizSorc: "0",
    value: "32",
    label: "Cure Light Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "33",
    label: "Cure Minor Wounds",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "3",
    dataPaladin: "3",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "34",
    label: "Cure Moderate Wounds",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "4",
    dataPaladin: "4",
    dataRanger: "4",
    dataWizSorc: "0",
    value: "35",
    label: "Cure Serious Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "548",
    label: "Darkfire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "688",
    label: "Darkness",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "36",
    label: "Darkness",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "37",
    label: "Daze",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "536",
    label: "Deafening Clang",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "519",
    label: "Death Armor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "383",
    label: "Death Domain, Negative Plane Avatar",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "5",
    dataPaladin: "4",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "38",
    label: "Death Ward",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "39",
    label: "Delayed Blast Fireball",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "366",
    label: "Destruction",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "445",
    label: "Dirge",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "1043",
    label: "Disintegrate",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "40",
    label: "Dismissal",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "4",
    dataPaladin: "3",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "41",
    label: "Dispel Magic",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "458",
    label: "Displacement",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "1002",
    label: "Disrobe",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "414",
    label: "Divine Favor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "42",
    label: "Divine Power",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "43",
    label: "Dominate Animal",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "44",
    label: "Dominate Monster",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "45",
    label: "Dominate Person",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "46",
    label: "Doom",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "437",
    label: "Drown",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "2",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "354",
    label: "Eagle's Splendor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "426",
    label: "Earthquake",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "439",
    label: "Electric Jolt",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "847",
    label: "Electric Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "47",
    label: "Elemental Shield",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "48",
    label: "Elemental Swarm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "49",
    label: "Endurance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "1",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "50",
    label: "Endure Elements",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "369",
    label: "Energy Buffer",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "51",
    label: "Energy Drain",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "52",
    label: "Enervation",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "0",
    value: "53",
    label: "Entangle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "418",
    label: "Entropic Shield",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "121",
    label: "Ethereal Visage",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "375",
    label: "Evard's Black Tentacles",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "566",
    label: "Evil Blight",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "456",
    label: "Expeditious Retreat",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "716",
    label: "Extract Brain",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "1014",
    label: "False Life",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "1004",
    label: "Falsify Self",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1071",
    label: "Fascinate",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "54",
    label: "Fear",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "808",
    label: "Fear",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "55",
    label: "Feeblemind",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "377",
    label: "Find Traps",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "56",
    label: "Finger of Death",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "848",
    label: "Fire Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "57",
    label: "Fire Storm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "58",
    label: "Fireball",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "440",
    label: "Firebrand",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "1038",
    label: "Fireburst",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "59",
    label: "Flame Arrow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "60",
    label: "Flame Lash",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "61",
    label: "Flame Strike",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "542",
    label: "Flame Weapon",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1040",
    label: "Flamespear",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "416",
    label: "Flare",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "485",
    label: "Flesh to Stone",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "356",
    label: "Fox's Cunning",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "4",
    dataPaladin: "4",
    dataRanger: "4",
    dataWizSorc: "0",
    value: "62",
    label: "Freedom of Movement",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "63",
    label: "Gate",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "520",
    label: "Gedlee's Electric Loop",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "120",
    label: "Ghostly Visage",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "64",
    label: "Ghoul Touch",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "65",
    label: "Globe of Invulnerability",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "549",
    label: "Glyph of Warding",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "715",
    label: "Golem Slam",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "1",
    value: "66",
    label: "Grease",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "515",
    label: "Great Thunderclap",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "360",
    label: "Greater Bull's Strength",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "361",
    label: "Greater Cat's Grace",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "6",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "67",
    label: "Greater Dispelling",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "357",
    label: "Greater Eagle's Splendor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "362",
    label: "Greater Endurance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "1039",
    label: "Greater Fireburst",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "359",
    label: "Greater Fox's Cunning",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "1077",
    label: "Greater Life Shift",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "453",
    label: "Greater Magic Fang",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "3",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "545",
    label: "Greater Magic Weapon",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "358",
    label: "Greater Owl's Wisdom",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "69",
    label: "Greater Planar Binding",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "70",
    label: "Greater Restoration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "443",
    label: "Greater Sanctuary",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "71",
    label: "Greater Shadow Conjuration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "350",
    label: "Greater Shadow Conjuration, Acid Arrow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "351",
    label: "Greater Shadow Conjuration, Ghostly Visage",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "353",
    label: "Greater Shadow Conjuration, Minor Globe of Invulnerability",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "349",
    label: "Greater Shadow Conjuration, Summon Shadow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "352",
    label: "Greater Shadow Conjuration, Web",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1032",
    label: "Greater Shout",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "72",
    label: "Greater Spell Breach",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "73",
    label: "Greater Spell Mantle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "74",
    label: "Greater Stoneskin",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "75",
    label: "Gust of Wind",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1066",
    label: "Hail of Fire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "76",
    label: "Hammer of the Gods",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "77",
    label: "Harm",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "78",
    label: "Haste",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "563",
    label: "Haste-Slow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "79",
    label: "Heal",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "5",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "80",
    label: "Healing Circle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "514",
    label: "Healing Sting",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "762",
    label: "Hell Inferno",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "0",
    value: "81",
    label: "Hold Animal",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "82",
    label: "Hold Monster",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "83",
    label: "Hold Person",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "84",
    label: "Holy Aura",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "4",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "538",
    label: "Holy Sword",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "521",
    label: "Horizikaul's Boom",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "367",
    label: "Horrid Wilting",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1003",
    label: "Hypothermia",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "543",
    label: "Ice Dagger",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "368",
    label: "Ice Storm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1074",
    label: "Ice Wall",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "86",
    label: "Identify",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "87",
    label: "Implosion",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "88",
    label: "Improved Invisibility",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "89",
    label: "Incendiary Cloud",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1064",
    label: "Incinerating Pillar",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "446",
    label: "Inferno",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "513",
    label: "Infestation of Maggots",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "435",
    label: "Inflict Critical Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "432",
    label: "Inflict Light Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "431",
    label: "Inflict Minor Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "433",
    label: "Inflict Moderate Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "434",
    label: "Inflict Serious Wounds",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "90",
    label: "Invisibility",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "91",
    label: "Invisibility Purge",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "92",
    label: "Invisibility Sphere",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "522",
    label: "Ironguts",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "448",
    label: "Isaac's Greater Missile Storm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "447",
    label: "Isaac's Lesser Missile Storm",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1057",
    label: "Joyful Noise",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "539",
    label: "Keen Edge",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "93",
    label: "Knock",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1000",
    label: "Land Womb",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "376",
    label: "Legend Lore",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "840",
    label: "Lesser Acid Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "841",
    label: "Lesser Cold Orb",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "94",
    label: "Lesser Dispel",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "842",
    label: "Lesser Electric Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "843",
    label: "Lesser Fire Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "95",
    label: "Lesser Mind Blank",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "96",
    label: "Lesser Planar Binding",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "97",
    label: "Lesser Restoration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "844",
    label: "Lesser Sonic Orb",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "98",
    label: "Lesser Spell Breach",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "99",
    label: "Lesser Spell Mantle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1047",
    label: "Life Shift",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "100",
    label: "Light",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "872",
    label: "Light (Blue)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "873",
    label: "Light (Orange)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "874",
    label: "Light (Purple)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "875",
    label: "Light (Red)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "876",
    label: "Light (Yellow)",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "101",
    label: "Lightning Bolt",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "102",
    label: "Mage Armor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1042",
    label: "Mage Hand",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "3",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "322",
    label: "Magic Circle against Alignment",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "104",
    label: "Magic Circle against Evil",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "105",
    label: "Magic Circle against Good",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "0",
    value: "452",
    label: "Magic Fang",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "107",
    label: "Magic Missile",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "546",
    label: "Magic Vestment",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "544",
    label: "Magic Weapon",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "110",
    label: "Mass Blindness/Deafness",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "854",
    label: "Mass Bull's Strength",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "4",
    dataWizSorc: "0",
    value: "455",
    label: "Mass Camouflage",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "855",
    label: "Mass Cat's Grace",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "111",
    label: "Mass Charm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "864",
    label: "Mass Cure Critical Wounds",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "5",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "861",
    label: "Mass Cure Light Wounds",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "862",
    label: "Mass Cure Moderate Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "863",
    label: "Mass Cure Serious Wounds",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "856",
    label: "Mass Eagle Splendor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "857",
    label: "Mass Endurance",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "858",
    label: "Mass Fox's Cunning",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "113",
    label: "Mass Haste",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "114",
    label: "Mass Heal",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "868",
    label: "Mass Inflict Critical Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "865",
    label: "Mass Inflict Light Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "866",
    label: "Mass Inflict Moderate Wounds",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "867",
    label: "Mass Inflict Serious Wounds",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "2",
    dataRanger: "2",
    dataWizSorc: "2",
    value: "1023",
    label: "Mass Light",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "859",
    label: "Mass Owl's Wisdom",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "4",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "4",
    value: "860",
    label: "Mass Ultravision",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "115",
    label: "Melf's Acid Arrow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "523",
    label: "Mestil's Acid Breath",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "524",
    label: "Mestil's Acid Sheath",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "116",
    label: "Meteor Swarm",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "117",
    label: "Mind Blank",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "118",
    label: "Mind Fog",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "119",
    label: "Minor Globe of Invulnerability",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1087",
    label: "Mirror Image",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "525",
    label: "Monstrous Regeneration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "122",
    label: "Mordenkainen's Disjunction",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "871",
    label: "Mordenkainen's Magnificent Mansion",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "123",
    label: "Mordenkainen's Sword",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "124",
    label: "Nature's Balance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "370",
    label: "Negative Energy Burst",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "125",
    label: "Negative Energy Protection",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "371",
    label: "Negative Energy Ray",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "4",
    dataDruid: "3",
    dataPaladin: "4",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "126",
    label: "Neutralize Poison",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "809",
    label: "Oath of Wrath",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "0",
    value: "420",
    label: "One with the Land",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1068",
    label: "Open / Close",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "438",
    label: "Owl's Insight",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "355",
    label: "Owl's Wisdom",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "127",
    label: "Phantasmal Killer",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "451",
    label: "Planar Ally",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "128",
    label: "Planar Binding",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "129",
    label: "Poison",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "852",
    label: "Polar Ray",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "4",
    dataWizSorc: "4",
    value: "130",
    label: "Polymorph Self",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "390",
    label: "Polymorph, Fey",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "387",
    label: "Polymorph, Giant Spider",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "388",
    label: "Polymorph, Troll",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "389",
    label: "Polymorph, Umber Hulk",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "391",
    label: "Polymorph, Zombie",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "131",
    label: "Power Word, Kill",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "132",
    label: "Power Word, Stun",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "3",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "133",
    label: "Prayer",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "134",
    label: "Premonition",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "135",
    label: "Prismatic Spray",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "382",
    label: "Protection Domain, Divine Protection",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "321",
    label: "Protection from Alignment",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "3",
    value: "137",
    label: "Protection from Elements",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "138",
    label: "Protection from Evil",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "139",
    label: "Protection from Good",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "141",
    label: "Protection from Spells",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "425",
    label: "Quillfire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1067",
    label: "Raging Inferno",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "142",
    label: "Raise Dead",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "143",
    label: "Ray of Enfeeblement",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "144",
    label: "Ray of Frost",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "374",
    label: "Regenerate",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "3",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "145",
    label: "Remove Blindness/Deafness",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "146",
    label: "Remove Curse",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "0",
    value: "147",
    label: "Remove Disease",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "148",
    label: "Remove Fear",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "2",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "149",
    label: "Remove Paralysis",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "2",
    dataRanger: "1",
    dataWizSorc: "2",
    value: "150",
    label: "Resist Elements",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "151",
    label: "Resistance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "4",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "152",
    label: "Restoration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "568",
    label: "Restoration - Other",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "153",
    label: "Resurrection",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "385",
    label: "Rogue's Cunning",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "154",
    label: "Sanctuary",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "155",
    label: "Scare",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "526",
    label: "Scintillating Sphere",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "3",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "156",
    label: "Searing Light",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "157",
    label: "See Invisibility",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "158",
    label: "Shades",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "340",
    label: "Shades, Cone of Cold",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "341",
    label: "Shades, Fireball",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "342",
    label: "Shades, Stoneskin",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "343",
    label: "Shades, Wall of Fire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "159",
    label: "Shadow Conjuration",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "345",
    label: "Shadow Conjuration, Darkness",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "346",
    label: "Shadow Conjuration, Invisibility",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "347",
    label: "Shadow Conjuration, Mage Armor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "348",
    label: "Shadow Conjuration, Magic Missile",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "344",
    label: "Shadow Conjuration, Summon Shadow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "160",
    label: "Shadow Shield",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "769",
    label: "Shadow attack",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "802",
    label: "Shadow attack",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "161",
    label: "Shapechange",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "394",
    label: "Shapechange, Balor",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "395",
    label: "Shapechange, Death Slaad",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "393",
    label: "Shapechange, Fire Giant",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "396",
    label: "Shapechange, Iron Golem",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "392",
    label: "Shapechange, Red Dragon",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "1082",
    label: "Shards of Winter",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "534",
    label: "Shelgarn's Persistent Blade",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "417",
    label: "Shield",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "1",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "450",
    label: "Shield of Faith",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "1031",
    label: "Shout",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "163",
    label: "Silence",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "164",
    label: "Slay Living",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "0",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "1",
    value: "165",
    label: "Sleep",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "166",
    label: "Slow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1086",
    label: "Slow Time",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1058",
    label: "Song of Discord",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "849",
    label: "Sonic Orb",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "167",
    label: "Sound Burst",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "169",
    label: "Spell Mantle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "168",
    label: "Spell Resistance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "454",
    label: "Spike Growth",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "171",
    label: "Stinking Cloud",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "2",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "527",
    label: "Stone Bones",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "486",
    label: "Stone to Flesh",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "547",
    label: "Stonehold",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "172",
    label: "Stoneskin",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "173",
    label: "Storm of Vengeance",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "381",
    label: "Strength Domain, Divine Strength",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "379",
    label: "Summon Celestial",
  },
  {
    dataType: "1",
    dataBard: "1",
    dataCleric: "1",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "1",
    value: "174",
    label: "Summon Creature I",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "2",
    dataPaladin: "0",
    dataRanger: "2",
    dataWizSorc: "2",
    value: "175",
    label: "Summon Creature II",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "3",
    dataDruid: "3",
    dataPaladin: "0",
    dataRanger: "3",
    dataWizSorc: "3",
    value: "176",
    label: "Summon Creature III",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "4",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "4",
    dataWizSorc: "4",
    value: "177",
    label: "Summon Creature IV",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "9",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "178",
    label: "Summon Creature IX",
  },
  {
    dataType: "1",
    dataBard: "5",
    dataCleric: "5",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "179",
    label: "Summon Creature V",
  },
  {
    dataType: "1",
    dataBard: "6",
    dataCleric: "6",
    dataDruid: "6",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "180",
    label: "Summon Creature VI",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "7",
    value: "181",
    label: "Summon Creature VII",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "182",
    label: "Summon Creature VIII",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "324",
    label: "Summon Shadow",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "183",
    label: "Sunbeam",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "427",
    label: "Sunburst",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1062",
    label: "Swap Gender",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1052",
    label: "Symbol of Death",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "8",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1053",
    label: "Symbol of Sleep",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "8",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1027",
    label: "Synthesis",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "457",
    label: "Tasha's Hideous Laughter",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "184",
    label: "Tenser's Transformation",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "565",
    label: "Tide of Battle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "185",
    label: "Time Stop",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "4",
    dataWizSorc: "0",
    value: "1080",
    label: "Tree Shape",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "384",
    label: "Trickery Domain, Divine Trickery",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "7",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "186",
    label: "True Seeing",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "1",
    value: "415",
    label: "True Strike",
  },
  {
    dataType: "1",
    dataBard: "2",
    dataCleric: "2",
    dataDruid: "1",
    dataPaladin: "0",
    dataRanger: "1",
    dataWizSorc: "2",
    value: "365",
    label: "Ultravision",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "6",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "528",
    label: "Undeath to Death",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "444",
    label: "Undeath's Eternal Foe",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "5",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "6",
    value: "1006",
    label: "Unhallowed Soil",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "187",
    label: "Unholy Aura",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "3",
    value: "188",
    label: "Vampiric Touch",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "529",
    label: "Vine Mine",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "532",
    label: "Vine Mine, Camouflage",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "530",
    label: "Vine Mine, Entangle",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "531",
    label: "Vine Mine, Hamper Movement",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "1",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "189",
    label: "Virtue",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "190",
    label: "Wail of the Banshee",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "5",
    value: "1016",
    label: "Wall of Dispel Magic",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "5",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "191",
    label: "Wall of Fire",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "8",
    value: "1017",
    label: "Wall of Greater Dispel Magic",
  },
  {
    dataType: "1",
    dataBard: "4",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "373",
    label: "War Cry",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "380",
    label: "War Domain, Battle Mastery",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "2",
    value: "192",
    label: "Web",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "9",
    value: "193",
    label: "Weird",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "0",
    dataDruid: "4",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "4",
    value: "1075",
    label: "Wind Wall",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "9",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "1025",
    label: "Wings of the Phoenix",
  },
  {
    dataType: "1",
    dataBard: "0",
    dataCleric: "7",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "194",
    label: "Word of Faith",
  },
  {
    dataType: "1",
    dataBard: "3",
    dataCleric: "0",
    dataDruid: "0",
    dataPaladin: "0",
    dataRanger: "0",
    dataWizSorc: "0",
    value: "441",
    label: "Wounding Whispers",
  },
];
