export const Tilesets = [
  { label: "Classic Dungeon", value: "cdlif" },
  { label: "Dungeon [CEP]", value: "tde01" },
  { label: "Dwarven Chasms", value: "isc04" },
  { label: "Eye of the Beholder", value: "tei01" },
  { label: "Mines and Caverns [CEP]", value: "tdm01" },
  { label: "Sea Caves", value: "tdt01" },
  { label: "Sen's Icy Caverns", value: "sic01" },
  { label: "Sen's Mines and Caverns", value: "scv01" },
  { label: "Sen's Underdark", value: "sdg01" },
  { label: "Underdark [CEP]", value: "ttu01" },
  { label: "Versatile Dungeon", value: "tvd" },
  { label: "Catacombs", value: "twl04" },
  { label: "Sewers", value: "tds01" },
  { label: "Steamworks", value: "tsw01" },
  { label: "Undercity Sewer", value: "isc02" },
  { label: "Barrows Interior", value: "tbw01" },
  { label: "Beholder Interior [CEP]", value: "tib01" },
  { label: "Crypts [CEP]", value: "tdc01" },
  { label: "Deep Dungeon", value: "isc01" },
  { label: "Ruins", value: "tdr01" },
  { label: "Barren Lands", value: "isc03" },
  { label: "Desert [CEP]", value: "ttd01" },
  { label: "Desert, Babylon [CTP]", value: "tced0" },
  { label: "Forest [CEP]", value: "ttf01" },
  { label: "Frozen Waste [CEP]", value: "tti01" },
  { label: "Medieval Forest", value: "tfm01" },
  { label: "Rural Grass [CEP]", value: "ttr01" },
  { label: "Rural Winter [CEP]", value: "tts01" },
  { label: "Swamps [CEP]", value: "zkw01" },
  { label: "Tropical", value: "ttz01" },
  { label: "Urban Wasteland", value: "wlu01" },
  { label: "Wild Woods", value: "ttw01" },
  { label: "Wildlands", value: "twl01" },
  { label: "Wildlands Winter", value: "twl02" },
  { label: "Worms Cypress Bayou", value: "wcs10" },
  { label: "Worms Dense Jungle", value: "wdj01" },
  { label: "Worms Desert Plains", value: "wdp01" },
  { label: "Worms Fantasy Interiors", value: "wdd04" },
  { label: "Worms Forest Summer", value: "wsf10" },
  { label: "Worms Jungle Mountains", value: "tjj01" },
  { label: "Worms Mirkwood Swamps", value: "wms01" },
  { label: "Worms Outer Limits", value: "wcc01" },
  { label: "Worms Scorched Earth", value: "wlf01" },
  { label: "Worms Undersea", value: "wut01" },
  { label: "Aztec Exterior", value: "tze01" },
  { label: "Castle Exterior, Rural", value: "tno01" },
  { label: "City Exterior [CEP]", value: "tcn01" },
  { label: "Complete Rural/City", value: "tcr10" },
  { label: "Elven Treetop City", value: "thf02" },
  { label: "Gothic Estates", value: "gg" },
  { label: "Medieval City", value: "tcm01" },
  { label: "Medieval Rural", value: "trm01" },
  { label: "Modern Suburbs", value: "udp1" },
  { label: "Oriental Rural", value: "ori01" },
  { label: "Sigil, Exterior [CODI]", value: "tps01" },
  { label: "Castle Interior 1 [CEP]", value: "tic01" },
  { label: "Castle Interior 2", value: "tni02" },
  { label: "City Interior 1 [CEP]", value: "tin01" },
  { label: "City Interior 2", value: "tni01" },
  { label: "Drow Interior [CEP]", value: "tid01" },
  { label: "Elven Interiors, Marble", value: "bvi80" },
  { label: "Elven Interiors, Wooden", value: "pie23" },
  { label: "Fancy Castle", value: "fla01" },
  { label: "Fort Interior", value: "twc03" },
  { label: "Gothic Interior", value: "gi" },
  { label: "Illithid Interior", value: "tii01" },
  { label: "Medieval Keep Interior", value: "tei02" },
  { label: "Modern Office Interiors", value: "udp2" },
  { label: "NWN2 Houses", value: "tms02" },
  { label: "Oriental Interior", value: "ori02" },
  { label: "Sen's Rural Inn", value: "sic11" },
  { label: "Sigil, Stern Interior [CODI]", value: "thv01" },
  { label: "SJ Wood Interior", value: "tis01" },
  { label: "White Marble Castle", value: "mbc30" },
  { label: "Workshop", value: "wks01" },
  { label: "Arena", value: "tte30" },
  { label: "Future, Secret Base", value: "tcdh0" },
  { label: "PHoD Bunker 1", value: "fifi1" },
  { label: "PHoD Bunker 2", value: "fifi2" },
  { label: "PHoD Bunker 3", value: "fifi3" },
  { label: "PHoD Metal Vault Interior", value: "mbc31" },
  { label: "PHoD Metal Wasteland 1", value: "tsr02" },
  { label: "PHoD Vault - Ancient", value: "phodd" },
  { label: "PHoD Vault - Exotic", value: "phoda" },
  { label: "PHoD Vault - Lumpy", value: "phode" },
  { label: "PHoD Vault - Murky", value: "phodf" },
  { label: "PHoD Vault - Strange", value: "phodb" },
  { label: "PHoD Vault - Tainted", value: "phodc" },
  { label: "Ship Interior", value: "nex01" },
  { label: "Starship Interiors", value: "shp02" },
  { label: "Worms Wagon Travel Interior", value: "tms01" },
];
