import { DropdownListItem } from ".";

export const TrapTypes: DropdownListItem[] = [
  { value: "41", label: "Acid Splash Trap, Average" },
  { value: "43", label: "Acid Splash Trap, Deadly" },
  { value: "40", label: "Acid Splash Trap, Minor" },
  { value: "42", label: "Acid Splash Trap, Strong" },
  { value: "13", label: "Acid Trap, Average" },
  { value: "15", label: "Acid Trap, Deadly" },
  { value: "12", label: "Acid Trap, Minor" },
  { value: "14", label: "Acid Trap, Strong" },
  { value: "21", label: "Electrical Trap, Average" },
  { value: "23", label: "Electrical Trap, Deadly" },
  { value: "44", label: "Electrical Trap, Epic" },
  { value: "20", label: "Electrical Trap, Minor" },
  { value: "22", label: "Electrical Trap, Strong" },
  { value: "17", label: "Fire Trap, Average" },
  { value: "19", label: "Fire Trap, Deadly" },
  { value: "45", label: "Fire Trap, Epic" },
  { value: "16", label: "Fire Trap, Minor" },
  { value: "18", label: "Fire Trap, Strong" },
  { value: "29", label: "Frost Trap, Average" },
  { value: "31", label: "Frost Trap, Deadly" },
  { value: "46", label: "Frost Trap, Epic" },
  { value: "28", label: "Frost Trap, Minor" },
  { value: "30", label: "Frost Trap, Strong" },
  { value: "25", label: "Gas Trap, Average" },
  { value: "27", label: "Gas Trap, Deadly" },
  { value: "24", label: "Gas Trap, Minor" },
  { value: "26", label: "Gas Trap, Strong" },
  { value: "5", label: "Holy Trap, Average" },
  { value: "4", label: "Holy Trap, Minor" },
  { value: "6", label: "Holy Trap, Strong" },
  { value: "7", label: "Holy Trap. Deadly" },
  { value: "33", label: "Negative Trap, Average" },
  { value: "35", label: "Negative Trap, Deadly" },
  { value: "32", label: "Negative Trap, Minor" },
  { value: "34", label: "Negative Trap, Strong" },
  { value: "37", label: "Sonic Trap, Average" },
  { value: "39", label: "Sonic Trap, Deadly" },
  { value: "47", label: "Sonic Trap, Epic" },
  { value: "36", label: "Sonic Trap, Minor" },
  { value: "38", label: "Sonic Trap, Strong" },
  { value: "1", label: "Spike Trap, Average" },
  { value: "3", label: "Spike Trap, Deadly" },
  { value: "0", label: "Spike Trap, Minor" },
  { value: "2", label: "Spike Trap, Strong" },
  { value: "9", label: "Tangle Trap, Average" },
  { value: "11", label: "Tangle Trap, Deadly" },
  { value: "8", label: "Tangle Trap, Minor" },
  { value: "10", label: "Tangle Trap, Strong" },
];
